package remote.wise.client.EventSubscriptionService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Sep 04 10:34:48 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "EventSubscriptionService")
@XmlSeeAlso({ObjectFactory.class})
public interface EventSubscriptionService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetEventSubscription", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.EventSubscriptionService.GetEventSubscription")
    @WebMethod(operationName = "GetEventSubscription", action = "GetEventSubscription")
    @ResponseWrapper(localName = "GetEventSubscriptionResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.EventSubscriptionService.GetEventSubscriptionResponse")
    public java.util.List<remote.wise.client.EventSubscriptionService.EventSubscriptionRespContract> getEventSubscription(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.EventSubscriptionService.EventSubscriptionReqContract reqObj
    ) throws CustomFault;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "SetEventSubscription", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.EventSubscriptionService.SetEventSubscription")
    @WebMethod(operationName = "SetEventSubscription", action = "SetEventSubscription")
    @ResponseWrapper(localName = "SetEventSubscriptionResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.EventSubscriptionService.SetEventSubscriptionResponse")
    public java.lang.String setEventSubscription(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.EventSubscriptionService.EventSubscriptionReqContract reqObj
    ) throws CustomFault;
}
