
/*
 * 
 */

package remote.wise.client.PendingTenancyCreationService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Mar 13 18:48:50 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "PendingTenancyCreationServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/PendingTenancyCreationService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class PendingTenancyCreationServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "PendingTenancyCreationServiceService");
    public final static QName PendingTenancyCreationServicePort = new QName("http://webservice.service.wise.remote/", "PendingTenancyCreationServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/PendingTenancyCreationService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/PendingTenancyCreationService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public PendingTenancyCreationServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PendingTenancyCreationServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PendingTenancyCreationServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public PendingTenancyCreationServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public PendingTenancyCreationServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public PendingTenancyCreationServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns PendingTenancyCreationService
     */
    @WebEndpoint(name = "PendingTenancyCreationServicePort")
    public PendingTenancyCreationService getPendingTenancyCreationServicePort() {
        return super.getPort(PendingTenancyCreationServicePort, PendingTenancyCreationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PendingTenancyCreationService
     */
    @WebEndpoint(name = "PendingTenancyCreationServicePort")
    public PendingTenancyCreationService getPendingTenancyCreationServicePort(WebServiceFeature... features) {
        return super.getPort(PendingTenancyCreationServicePort, PendingTenancyCreationService.class, features);
    }

}
