package remote.wise.client.DeleteLandmarkService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Mar 12 15:43:27 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "DeleteLandmarkService")
@XmlSeeAlso({ObjectFactory.class})
public interface DeleteLandmarkService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "SetDeleteLandmark", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.DeleteLandmarkService.SetDeleteLandmark")
    @WebMethod(operationName = "SetDeleteLandmark", action = "SetDeleteLandmark")
    @ResponseWrapper(localName = "SetDeleteLandmarkResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.DeleteLandmarkService.SetDeleteLandmarkResponse")
    public java.lang.String setDeleteLandmark(
        @WebParam(name = "RespObj", targetNamespace = "")
        remote.wise.client.DeleteLandmarkService.DeleteLandmarkRespContract respObj
    ) throws CustomFault;
}
