
/*
 * 
 */

package remote.wise.client.PricolTransactionDetailService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue May 21 09:57:15 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "PricolTransactionDetailServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/PricolTransactionDetailService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class PricolTransactionDetailServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "PricolTransactionDetailServiceService");
    public final static QName PricolTransactionDetailServicePort = new QName("http://webservice.service.wise.remote/", "PricolTransactionDetailServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/PricolTransactionDetailService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/PricolTransactionDetailService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public PricolTransactionDetailServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PricolTransactionDetailServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PricolTransactionDetailServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public PricolTransactionDetailServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public PricolTransactionDetailServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public PricolTransactionDetailServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns PricolTransactionDetailService
     */
    @WebEndpoint(name = "PricolTransactionDetailServicePort")
    public PricolTransactionDetailService getPricolTransactionDetailServicePort() {
        return super.getPort(PricolTransactionDetailServicePort, PricolTransactionDetailService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PricolTransactionDetailService
     */
    @WebEndpoint(name = "PricolTransactionDetailServicePort")
    public PricolTransactionDetailService getPricolTransactionDetailServicePort(WebServiceFeature... features) {
        return super.getPort(PricolTransactionDetailServicePort, PricolTransactionDetailService.class, features);
    }

}
