package remote.wise.client.AssetEventLogService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Jul 03 11:49:45 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "AssetEventLogService")
@XmlSeeAlso({ObjectFactory.class})
public interface AssetEventLogService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetAssetEventLog", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.AssetEventLogService.GetAssetEventLog")
    @WebMethod(operationName = "GetAssetEventLog", action = "GetAssetEventLog")
    @ResponseWrapper(localName = "GetAssetEventLogResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.AssetEventLogService.GetAssetEventLogResponse")
    public java.util.List<remote.wise.client.AssetEventLogService.AssetEventRespContract> getAssetEventLog(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.AssetEventLogService.AssetEventLogReqContract reqObj
    ) throws CustomFault;
}
