
/*
 * 
 */

package remote.wise.client.AssetEventLogService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Jul 03 11:49:45 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "AssetEventLogServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/AssetEventLogService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class AssetEventLogServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "AssetEventLogServiceService");
    public final static QName AssetEventLogServicePort = new QName("http://webservice.service.wise.remote/", "AssetEventLogServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/AssetEventLogService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/AssetEventLogService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public AssetEventLogServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AssetEventLogServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AssetEventLogServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public AssetEventLogServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public AssetEventLogServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public AssetEventLogServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns AssetEventLogService
     */
    @WebEndpoint(name = "AssetEventLogServicePort")
    public AssetEventLogService getAssetEventLogServicePort() {
        return super.getPort(AssetEventLogServicePort, AssetEventLogService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AssetEventLogService
     */
    @WebEndpoint(name = "AssetEventLogServicePort")
    public AssetEventLogService getAssetEventLogServicePort(WebServiceFeature... features) {
        return super.getPort(AssetEventLogServicePort, AssetEventLogService.class, features);
    }

}
