package remote.wise.client.AssetGroupService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Jun 11 17:43:30 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "AssetGroupService")
@XmlSeeAlso({ObjectFactory.class})
public interface AssetGroupService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "SetCustomAssetGroup", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.AssetGroupService.SetCustomAssetGroup")
    @WebMethod(operationName = "SetCustomAssetGroup", action = "SetCustomAssetGroup")
    @ResponseWrapper(localName = "SetCustomAssetGroupResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.AssetGroupService.SetCustomAssetGroupResponse")
    public remote.wise.client.AssetGroupService.AssetGroupReqContract setCustomAssetGroup(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.AssetGroupService.AssetGroupRespContract reqObj
    ) throws CustomFault;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetCustomAssetGroup", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.AssetGroupService.GetCustomAssetGroup")
    @WebMethod(operationName = "GetCustomAssetGroup", action = "GetCustomAssetGroup")
    @ResponseWrapper(localName = "GetCustomAssetGroupResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.AssetGroupService.GetCustomAssetGroupResponse")
    public java.util.List<remote.wise.client.AssetGroupService.AssetGroupRespContract> getCustomAssetGroup(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.AssetGroupService.AssetGroupReqContract reqObj
    ) throws CustomFault;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "DeleteCustomAssetGroup", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.AssetGroupService.DeleteCustomAssetGroup")
    @WebMethod(operationName = "DeleteCustomAssetGroup", action = "DeleteCustomAssetGroup")
    @ResponseWrapper(localName = "DeleteCustomAssetGroupResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.AssetGroupService.DeleteCustomAssetGroupResponse")
    public java.lang.String deleteCustomAssetGroup(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.AssetGroupService.AssetGroupRespContract reqObj
    ) throws CustomFault;
}
