
/*
 * 
 */

package remote.wise.client.AlertThresholdSettingsService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Mar 12 15:06:57 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "AlertThresholdSettingsServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/AlertThresholdSettingsService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class AlertThresholdSettingsServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "AlertThresholdSettingsServiceService");
    public final static QName AlertThresholdServicePort = new QName("http://webservice.service.wise.remote/", "AlertThresholdServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/AlertThresholdSettingsService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/AlertThresholdSettingsService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public AlertThresholdSettingsServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AlertThresholdSettingsServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AlertThresholdSettingsServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public AlertThresholdSettingsServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public AlertThresholdSettingsServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public AlertThresholdSettingsServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns AlertThresholdService
     */
    @WebEndpoint(name = "AlertThresholdServicePort")
    public AlertThresholdService getAlertThresholdServicePort() {
        return super.getPort(AlertThresholdServicePort, AlertThresholdService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AlertThresholdService
     */
    @WebEndpoint(name = "AlertThresholdServicePort")
    public AlertThresholdService getAlertThresholdServicePort(WebServiceFeature... features) {
        return super.getPort(AlertThresholdServicePort, AlertThresholdService.class, features);
    }

}
