
/*
 * 
 */

package remote.wise.client.AlertDetailsService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Thu Apr 18 16:56:25 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "AlertDetailsServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/AlertDetailsService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class AlertDetailsServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "AlertDetailsServiceService");
    public final static QName AlertDetailsServicePort = new QName("http://webservice.service.wise.remote/", "AlertDetailsServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/AlertDetailsService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/AlertDetailsService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public AlertDetailsServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AlertDetailsServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AlertDetailsServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public AlertDetailsServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public AlertDetailsServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public AlertDetailsServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns AlertDetailsService
     */
    @WebEndpoint(name = "AlertDetailsServicePort")
    public AlertDetailsService getAlertDetailsServicePort() {
        return super.getPort(AlertDetailsServicePort, AlertDetailsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AlertDetailsService
     */
    @WebEndpoint(name = "AlertDetailsServicePort")
    public AlertDetailsService getAlertDetailsServicePort(WebServiceFeature... features) {
        return super.getPort(AlertDetailsServicePort, AlertDetailsService.class, features);
    }

}
