package remote.wise.client.AlertDetailsService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Thu Apr 18 16:56:25 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "AlertDetailsService")
@XmlSeeAlso({ObjectFactory.class})
public interface AlertDetailsService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "setAlertComments", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.AlertDetailsService.SetAlertComments")
    @WebMethod(action = "setAlertComments")
    @ResponseWrapper(localName = "setAlertCommentsResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.AlertDetailsService.SetAlertCommentsResponse")
    public java.lang.String setAlertComments(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.AlertDetailsService.AlertDetailsRespContract reqObj
    ) throws CustomFault;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetAlertDetails", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.AlertDetailsService.GetAlertDetails")
    @WebMethod(operationName = "GetAlertDetails", action = "GetAlertDetails")
    @ResponseWrapper(localName = "GetAlertDetailsResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.AlertDetailsService.GetAlertDetailsResponse")
    public remote.wise.client.AlertDetailsService.AlertDetailsRespContract getAlertDetails(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.AlertDetailsService.AlertDetailsReqContract reqObj
    ) throws CustomFault;
}
