
/*
 * 
 */

package remote.wise.client.HAJassetDetailsService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed May 27 18:36:12 IST 2015
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "HAJassetDetailsServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/HAJassetDetailsService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class HAJassetDetailsServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "HAJassetDetailsServiceService");
    public final static QName HAJassetDetailsServicePort = new QName("http://webservice.service.wise.remote/", "HAJassetDetailsServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/HAJassetDetailsService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/HAJassetDetailsService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public HAJassetDetailsServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HAJassetDetailsServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HAJassetDetailsServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public HAJassetDetailsServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public HAJassetDetailsServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public HAJassetDetailsServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns HAJassetDetailsService
     */
    @WebEndpoint(name = "HAJassetDetailsServicePort")
    public HAJassetDetailsService getHAJassetDetailsServicePort() {
        return super.getPort(HAJassetDetailsServicePort, HAJassetDetailsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HAJassetDetailsService
     */
    @WebEndpoint(name = "HAJassetDetailsServicePort")
    public HAJassetDetailsService getHAJassetDetailsServicePort(WebServiceFeature... features) {
        return super.getPort(HAJassetDetailsServicePort, HAJassetDetailsService.class, features);
    }

}
