
/*
 * 
 */

package remote.wise.client.ForgotLoginIDService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Mon Apr 08 09:19:01 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "ForgotLoginIDServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/ForgotLoginIDService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class ForgotLoginIDServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "ForgotLoginIDServiceService");
    public final static QName ForgotLoginIDServicePort = new QName("http://webservice.service.wise.remote/", "ForgotLoginIDServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/ForgotLoginIDService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/ForgotLoginIDService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public ForgotLoginIDServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ForgotLoginIDServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ForgotLoginIDServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ForgotLoginIDServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public ForgotLoginIDServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public ForgotLoginIDServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ForgotLoginIDService
     */
    @WebEndpoint(name = "ForgotLoginIDServicePort")
    public ForgotLoginIDService getForgotLoginIDServicePort() {
        return super.getPort(ForgotLoginIDServicePort, ForgotLoginIDService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ForgotLoginIDService
     */
    @WebEndpoint(name = "ForgotLoginIDServicePort")
    public ForgotLoginIDService getForgotLoginIDServicePort(WebServiceFeature... features) {
        return super.getPort(ForgotLoginIDServicePort, ForgotLoginIDService.class, features);
    }

}
