package remote.wise.client.LandmarkActivityReportService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Mon Sep 16 12:46:57 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "LandmarkActivityReportService")
@XmlSeeAlso({ObjectFactory.class})
public interface LandmarkActivityReportService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetLandmarkActivityReport", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.LandmarkActivityReportService.GetLandmarkActivityReport")
    @WebMethod(operationName = "GetLandmarkActivityReport", action = "GetLandmarkActivityReport")
    @ResponseWrapper(localName = "GetLandmarkActivityReportResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.LandmarkActivityReportService.GetLandmarkActivityReportResponse")
    public java.util.List<remote.wise.client.LandmarkActivityReportService.LandmarkActivityReportRespContract> getLandmarkActivityReport(
        @WebParam(name = "ReqObj", targetNamespace = "")
        remote.wise.client.LandmarkActivityReportService.LandmarkActivityReportReqContract reqObj
    );
}
