package remote.wise.EAintegration.clientPackage.AssetSaleFromD2C;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Sep 03 10:10:07 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "AssetSaleFromD2Cservice")
@XmlSeeAlso({ObjectFactory.class})
public interface AssetSaleFromD2Cservice {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "assetSaleFromDealerToCust", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.EAintegration.clientPackage.AssetSaleFromD2C.AssetSaleFromDealerToCust")
    @WebMethod(action = "assetSaleFromDealerToCust")
    @ResponseWrapper(localName = "assetSaleFromDealerToCustResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.EAintegration.clientPackage.AssetSaleFromD2C.AssetSaleFromDealerToCustResponse")
    public java.lang.String assetSaleFromDealerToCust(
        @WebParam(name = "sellerCode", targetNamespace = "")
        java.lang.String sellerCode,
        @WebParam(name = "buyerCode", targetNamespace = "")
        java.lang.String buyerCode,
        @WebParam(name = "dealerCode", targetNamespace = "")
        java.lang.String dealerCode,
        @WebParam(name = "serialNumber", targetNamespace = "")
        java.lang.String serialNumber,
        @WebParam(name = "transferDate", targetNamespace = "")
        java.lang.String transferDate,
        @WebParam(name = "messageId", targetNamespace = "")
        java.lang.String messageId,
        @WebParam(name = "fileRef", targetNamespace = "")
        java.lang.String fileRef,
        @WebParam(name = "process", targetNamespace = "")
        java.lang.String process,
        @WebParam(name = "reprocessJobCode", targetNamespace = "")
        java.lang.String reprocessJobCode
    );
}
