
/*
 * 
 */

package remote.wise.EAintegration.clientPackage.AssetSaleFromD2C;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Sep 03 10:10:07 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "AssetSaleFromD2CserviceService", 
                  wsdlLocation = "http://localhost:27000/WISE/AssetSaleFromD2Cservice?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class AssetSaleFromD2CserviceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "AssetSaleFromD2CserviceService");
    public final static QName AssetSaleFromD2CservicePort = new QName("http://webservice.service.wise.remote/", "AssetSaleFromD2CservicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/AssetSaleFromD2Cservice?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/AssetSaleFromD2Cservice?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public AssetSaleFromD2CserviceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AssetSaleFromD2CserviceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AssetSaleFromD2CserviceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public AssetSaleFromD2CserviceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public AssetSaleFromD2CserviceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public AssetSaleFromD2CserviceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns AssetSaleFromD2Cservice
     */
    @WebEndpoint(name = "AssetSaleFromD2CservicePort")
    public AssetSaleFromD2Cservice getAssetSaleFromD2CservicePort() {
        return super.getPort(AssetSaleFromD2CservicePort, AssetSaleFromD2Cservice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AssetSaleFromD2Cservice
     */
    @WebEndpoint(name = "AssetSaleFromD2CservicePort")
    public AssetSaleFromD2Cservice getAssetSaleFromD2CservicePort(WebServiceFeature... features) {
        return super.getPort(AssetSaleFromD2CservicePort, AssetSaleFromD2Cservice.class, features);
    }

}
