package remote.wise.EAintegration.clientPackage.AssetPersonalityService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Fri Jul 26 17:36:05 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "AssetPersonalityService")
@XmlSeeAlso({ObjectFactory.class})
public interface AssetPersonalityService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "SetAssetPersonalityDetails", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.EAintegration.clientPackage.AssetPersonalityService.SetAssetPersonalityDetails")
    @WebMethod(operationName = "SetAssetPersonalityDetails", action = "SetAssetPersonalityDetails")
    @ResponseWrapper(localName = "SetAssetPersonalityDetailsResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.EAintegration.clientPackage.AssetPersonalityService.SetAssetPersonalityDetailsResponse")
    public java.lang.String setAssetPersonalityDetails(
        @WebParam(name = "engineNumber", targetNamespace = "")
        java.lang.String engineNumber,
        @WebParam(name = "assetGroupCode", targetNamespace = "")
        java.lang.String assetGroupCode,
        @WebParam(name = "assetTypeCode", targetNamespace = "")
        java.lang.String assetTypeCode,
        @WebParam(name = "engineTypeCode", targetNamespace = "")
        java.lang.String engineTypeCode,
        @WebParam(name = "assetBuiltDate", targetNamespace = "")
        java.lang.String assetBuiltDate,
        @WebParam(name = "make", targetNamespace = "")
        java.lang.String make,
        @WebParam(name = "fuelCapacity", targetNamespace = "")
        java.lang.String fuelCapacity,
        @WebParam(name = "serialNumber", targetNamespace = "")
        java.lang.String serialNumber,
        @WebParam(name = "messageId", targetNamespace = "")
        java.lang.String messageId,
        @WebParam(name = "fileRef", targetNamespace = "")
        java.lang.String fileRef,
        @WebParam(name = "process", targetNamespace = "")
        java.lang.String process,
        @WebParam(name = "reprocessJobCode", targetNamespace = "")
        java.lang.String reprocessJobCode
    );
}
