
/*
 * 
 */

package remote.wise.EAintegration.clientPackage.AssetPersonalityService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Fri Jul 26 17:36:05 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "AssetPersonalityServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/AssetPersonalityService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class AssetPersonalityServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "AssetPersonalityServiceService");
    public final static QName AssetPersonalityServicePort = new QName("http://webservice.service.wise.remote/", "AssetPersonalityServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/AssetPersonalityService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/AssetPersonalityService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public AssetPersonalityServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AssetPersonalityServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AssetPersonalityServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public AssetPersonalityServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public AssetPersonalityServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public AssetPersonalityServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns AssetPersonalityService
     */
    @WebEndpoint(name = "AssetPersonalityServicePort")
    public AssetPersonalityService getAssetPersonalityServicePort() {
        return super.getPort(AssetPersonalityServicePort, AssetPersonalityService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AssetPersonalityService
     */
    @WebEndpoint(name = "AssetPersonalityServicePort")
    public AssetPersonalityService getAssetPersonalityServicePort(WebServiceFeature... features) {
        return super.getPort(AssetPersonalityServicePort, AssetPersonalityService.class, features);
    }

}
