package remote.wise.client.UserAlertsService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Mon Apr 27 15:18:46 IST 2015
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "UserAlertsService")
@XmlSeeAlso({ObjectFactory.class})
public interface UserAlertsService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetUserAlerts", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.UserAlertsService.GetUserAlerts")
    @WebMethod(operationName = "GetUserAlerts", action = "GetUserAlerts")
    @ResponseWrapper(localName = "GetUserAlertsResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.UserAlertsService.GetUserAlertsResponse")
    public java.util.List<remote.wise.client.UserAlertsService.UserAlertsRespContract> getUserAlerts(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.UserAlertsService.UserAlertsReqContract reqObj
    ) throws CustomFault;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "setUserAlerts", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.UserAlertsService.SetUserAlerts")
    @WebMethod(action = "setUserAlerts")
    @ResponseWrapper(localName = "setUserAlertsResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.UserAlertsService.SetUserAlertsResponse")
    public java.lang.String setUserAlerts(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.UserAlertsService.UserAlertsCloserRespContract reqObj
    ) throws CustomFault;
}
