package remote.wise.client.SMSAlertDetailsService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Fri Dec 05 09:37:28 IST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "SMSAlertsDetailService")
@XmlSeeAlso({ObjectFactory.class})
public interface SMSAlertsDetailService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSMSAlertDetails", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.SMSAlertDetailsService.GetSMSAlertDetails")
    @WebMethod(action = "getSMSAlertDetails")
    @ResponseWrapper(localName = "getSMSAlertDetailsResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.SMSAlertDetailsService.GetSMSAlertDetailsResponse")
    public java.util.List<remote.wise.client.SMSAlertDetailsService.SmsAlertsRespContract> getSMSAlertDetails(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.SMSAlertDetailsService.SmsAlertDetailReqContract reqObj
    );
}
