
/*
 * 
 */

package remote.wise.client.DeviceDiagnosticService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed May 14 17:12:50 IST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "DeviceDiagnosticServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/DeviceDiagnosticService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class DeviceDiagnosticServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "DeviceDiagnosticServiceService");
    public final static QName DeviceDiagnosticServicePort = new QName("http://webservice.service.wise.remote/", "DeviceDiagnosticServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/DeviceDiagnosticService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/DeviceDiagnosticService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public DeviceDiagnosticServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DeviceDiagnosticServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeviceDiagnosticServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public DeviceDiagnosticServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public DeviceDiagnosticServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public DeviceDiagnosticServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns DeviceDiagnosticService
     */
    @WebEndpoint(name = "DeviceDiagnosticServicePort")
    public DeviceDiagnosticService getDeviceDiagnosticServicePort() {
        return super.getPort(DeviceDiagnosticServicePort, DeviceDiagnosticService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeviceDiagnosticService
     */
    @WebEndpoint(name = "DeviceDiagnosticServicePort")
    public DeviceDiagnosticService getDeviceDiagnosticServicePort(WebServiceFeature... features) {
        return super.getPort(DeviceDiagnosticServicePort, DeviceDiagnosticService.class, features);
    }

}
