
package remote.wise.client.DeviceDiagnosticService;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed May 14 17:12:50 IST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */

@WebFault(name = "FileNotFoundException", targetNamespace = "http://webservice.service.wise.remote/")
public class FileNotFoundException_Exception extends Exception {
    public static final long serialVersionUID = 20140514171250L;
    
    private remote.wise.client.DeviceDiagnosticService.FileNotFoundException fileNotFoundException;

    public FileNotFoundException_Exception() {
        super();
    }
    
    public FileNotFoundException_Exception(String message) {
        super(message);
    }
    
    public FileNotFoundException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public FileNotFoundException_Exception(String message, remote.wise.client.DeviceDiagnosticService.FileNotFoundException fileNotFoundException) {
        super(message);
        this.fileNotFoundException = fileNotFoundException;
    }

    public FileNotFoundException_Exception(String message, remote.wise.client.DeviceDiagnosticService.FileNotFoundException fileNotFoundException, Throwable cause) {
        super(message, cause);
        this.fileNotFoundException = fileNotFoundException;
    }

    public remote.wise.client.DeviceDiagnosticService.FileNotFoundException getFaultInfo() {
        return this.fileNotFoundException;
    }
}
