
package remote.wise.client.DeviceDiagnosticService;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed May 14 17:12:49 IST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */

@WebFault(name = "ParseException", targetNamespace = "http://webservice.service.wise.remote/")
public class ParseException_Exception extends Exception {
    public static final long serialVersionUID = 20140514171249L;
    
    private remote.wise.client.DeviceDiagnosticService.ParseException parseException;

    public ParseException_Exception() {
        super();
    }
    
    public ParseException_Exception(String message) {
        super(message);
    }
    
    public ParseException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ParseException_Exception(String message, remote.wise.client.DeviceDiagnosticService.ParseException parseException) {
        super(message);
        this.parseException = parseException;
    }

    public ParseException_Exception(String message, remote.wise.client.DeviceDiagnosticService.ParseException parseException, Throwable cause) {
        super(message, cause);
        this.parseException = parseException;
    }

    public remote.wise.client.DeviceDiagnosticService.ParseException getFaultInfo() {
        return this.parseException;
    }
}
