version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 900
      runas: root
  AfterInstall:
    - location: scripts/deploy_docker.sh
      timeout: 900
      runas: root
  ValidateService:
    - location: scripts/validate_container.sh
      timeout: 900
      runas: root
