version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: Scripts/before_install.sh
      timeout: 900
      runas: root
  AfterInstall:
    - location: Scripts/deploy_docker.sh
      timeout: 900
      runas: root
  ValidateService:
    - location: Scripts/validate_container.sh
      timeout: 900
      runas: root
