version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo "Installing dependencies..."
      - java -version

  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - mkdir -p build/classes
      - mkdir -p lib

      # Copy the reverseGeocoding.jar to the lib directory
      - cp reverseGeocoding.jar lib/reverseGeocoding.jar

      # Verify the contents of the JAR file
      - jar tf lib/reverseGeocoding.jar

      # Logging (Log4j)
      - wget https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-core/2.20.0/log4j-core-2.20.0.jar -O lib/log4j-core-2.20.0.jar
      - wget https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-api/2.20.0/log4j-api-2.20.0.jar -O lib/log4j-api-2.20.0.jar

      # Hibernate
      - cp hibernate-c3p0-4.1.1.Final.jar lib/hibernate-c3p0-4.1.1.Final.jar
      - jar tf lib/hibernate-c3p0-4.1.1.Final.jar

      # JSON libraries
      - wget https://repo1.maven.org/maven2/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar -O lib/json-simple-1.1.1.jar
      - wget https://repo1.maven.org/maven2/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar -O lib/gson-2.10.1.jar

      # Jackson 1.x (for org.codehaus.jackson)
      - wget https://repo1.maven.org/maven2/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar -O lib/jackson-mapper-asl-1.9.13.jar
      - wget https://repo1.maven.org/maven2/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar -O lib/jackson-core-asl-1.9.13.jar

      # JAX-RS API
      - wget https://repo1.maven.org/maven2/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.jar -O lib/javax.ws.rs-api-2.1.jar

      # Commons IO & Codec
      - wget https://repo1.maven.org/maven2/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar -O lib/commons-io-2.11.0.jar
      - wget https://repo1.maven.org/maven2/commons-codec/commons-codec/1.15/commons-codec-1.15.jar -O lib/commons-codec-1.15.jar

      # RabbitMQ
      - wget https://repo1.maven.org/maven2/com/rabbitmq/amqp-client/5.16.0/amqp-client-5.16.0.jar -O lib/amqp-client-5.16.0.jar

      # JasperReports
      - wget https://repo1.maven.org/maven2/net/sf/jasperreports/jasperreports/6.20.0/jasperreports-6.20.0.jar -O lib/jasperreports-6.20.0.jar

      # JavaMail (javax.mail and activation)
      - wget https://repo1.maven.org/maven2/com/sun/mail/javax.mail/1.6.2/javax.mail-1.6.2.jar -O lib/javax.mail-1.6.2.jar
      - wget https://repo1.maven.org/maven2/javax/activation/activation/1.1.1/activation-1.1.1.jar -O lib/activation-1.1.1.jar

      # JMS API
      - wget https://repo1.maven.org/maven2/javax/jms/javax.jms-api/2.0.1/javax.jms-api-2.0.1.jar -O lib/javax.jms-api-2.0.1.jar

      # Kafka (old consumer API and dependencies)
      - wget https://repo1.maven.org/maven2/org/apache/kafka/kafka_2.12/0.10.2.2/kafka_2.12-0.10.2.2.jar -O lib/kafka_2.12-0.10.2.2.jar
      - wget https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/0.10.2.2/kafka-clients-0.10.2.2.jar -O lib/kafka-clients-0.10.2.2.jar
      - wget https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.1/scala-library-2.12.1.jar -O lib/scala-library-2.12.1.jar

      # Guava
      - wget https://repo1.maven.org/maven2/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar -O lib/guava-31.1-jre.jar

      # MySQL JDBC Driver
      - wget https://repo1.maven.org/maven2/mysql/mysql-connector-java/5.1.49/mysql-connector-java-5.1.49.jar -O lib/mysql-connector-java-5.1.49.jar

      # Jedis (Redis client)
      - wget https://repo1.maven.org/maven2/redis/clients/jedis/3.7.1/jedis-3.7.1.jar -O lib/jedis-3.7.1.jar
      - wget https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.12.0/commons-pool2-2.12.0.jar -O lib/commons-pool2-2.12.0.jar

      # JXL (Java Excel API)
      - wget https://repo1.maven.org/maven2/net/sourceforge/jexcelapi/jxl/2.6.12/jxl-2.6.12.jar -O lib/jxl-2.6.12.jar

      # ANTLR v3
      - wget https://repo1.maven.org/maven2/org/antlr/antlr/3.5.2/antlr-3.5.2.jar -O lib/antlr-3.5.2.jar

      # Apache Commons Lang
      - wget https://repo1.maven.org/maven2/commons-lang/commons-lang/2.6/commons-lang-2.6.jar -O lib/commons-lang-2.6.jar

      # Servlet API
      - wget https://repo1.maven.org/maven2/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar -O lib/javax.servlet-api-3.1.0.jar

      # Apache HttpClient and dependencies
      - wget https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.5.14/httpclient-4.5.14.jar -O lib/httpclient-4.5.14.jar
      - wget https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar -O lib/httpcore-4.4.16.jar
      - wget https://repo1.maven.org/maven2/commons-logging/commons-logging/1.2/commons-logging-1.2.jar -O lib/commons-logging-1.2.jar

      # org.json
      - wget https://repo1.maven.org/maven2/org/json/json/20230618/json-20230618.jar -O lib/json-20230618.jar

      # OpenCSV
      - wget https://repo1.maven.org/maven2/com/opencsv/opencsv/5.8/opencsv-5.8.jar -O lib/opencsv-5.8.jar

      # Jackson Annotations
      - wget https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.15.2/jackson-annotations-2.15.2.jar -O lib/jackson-annotations-2.15.2.jar

      # Apache XML Serializer (xerces/xalan)
      - wget https://repo1.maven.org/maven2/xml-apis/xml-apis/1.4.01/xml-apis-1.4.01.jar -O lib/xml-apis-1.4.01.jar
      - wget https://repo1.maven.org/maven2/xerces/xercesImpl/2.12.2/xercesImpl-2.12.2.jar -O lib/xercesImpl-2.12.2.jar

      # iText PDF
      - wget https://repo1.maven.org/maven2/com/itextpdf/itextpdf/5.5.13.3/itextpdf-5.5.13.3.jar -O lib/itextpdf-5.5.13.3.jar

      # net.sf.json and dependencies
      - wget https://repo1.maven.org/maven2/net/sf/json-lib/json-lib/2.4/json-lib-2.4-jdk15.jar -O lib/json-lib-2.4-jdk15.jar
      - wget https://repo1.maven.org/maven2/commons-beanutils/commons-beanutils/1.9.4/commons-beanutils-1.9.4.jar -O lib/commons-beanutils-1.9.4.jar
      - wget https://repo1.maven.org/maven2/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar -O lib/commons-collections-3.2.2.jar
      - wget https://repo1.maven.org/maven2/net/sf/ezmorph/ezmorph/1.0.6/ezmorph-1.0.6.jar -O lib/ezmorph-1.0.6.jar

      # JJWT (JSON Web Token)
      - wget https://repo1.maven.org/maven2/io/jsonwebtoken/jjwt/0.12.3/jjwt-0.12.3.jar -O lib/jjwt-0.12.3.jar
      - wget https://repo1.maven.org/maven2/io/jsonwebtoken/jjwt-api/0.12.3/jjwt-api-0.12.3.jar -O lib/jjwt-api-0.12.3.jar
      - wget https://repo1.maven.org/maven2/io/jsonwebtoken/jjwt-impl/0.12.3/jjwt-impl-0.12.3.jar -O lib/jjwt-impl-0.12.3.jar
      - wget https://repo1.maven.org/maven2/io/jsonwebtoken/jjwt-jackson/0.12.3/jjwt-jackson-0.12.3.jar -O lib/jjwt-jackson-0.12.3.jar

      # RNGOM (for org.kohsuke.rngom.ast.builder)
      - wget https://repo1.maven.org/maven2/com/thaiopensource/jing/20091111/jing-20091111.jar -O lib/jing-20091111.jar

      # JAXB (for com.sun.xml.bind.*)
      - wget https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-impl/2.3.3/jaxb-impl-2.3.3.jar -O lib/jaxb-impl-2.3.3.jar
      - wget https://repo1.maven.org/maven2/javax/xml/bind/jaxb-api/2.3.1/jaxb-api-2.3.1.jar -O lib/jaxb-api-2.3.1.jar
      - wget https://repo1.maven.org/maven2/org/glassfish/jaxb/jaxb-runtime/2.3.3/jaxb-runtime-2.3.3.jar -O lib/jaxb-runtime-2.3.3.jar

      # Trang (for org.kohsuke.rngom.ast.builder.Include)
      - wget https://repo1.maven.org/maven2/com/thaiopensource/trang/20091111/trang-20091111.jar -O lib/trang-20091111.jar

      # Add JPA API
      - wget https://repo1.maven.org/maven2/javax/persistence/javax.persistence-api/2.2/javax.persistence-api-2.2.jar -O lib/javax.persistence-api-2.2.jar

      # Add Hibernate Core (if using Hibernate)
      - wget https://repo1.maven.org/maven2/org/hibernate/hibernate-core/3.6.10.Final/hibernate-core-3.6.10.Final.jar -O lib/hibernate-core-3.6.10.Final.jar

      # Compile with all dependencies
      - find src -name "*.java" > sources.txt
      - cat sources.txt
      - javac -encoding ISO-8859-1 -d build/classes -cp "lib/*" @sources.txt

  build:
    commands:
      - echo "Building EAR file..."
      - mkdir -p build/ear
      - cp -r WebContent/* build/ear/
      - cd build/ear
      - jar -cvf wise.ear *
      - ls -l wise.ear
      - cd ../..
      - echo "EAR file created successfully."

  post_build:
    commands:
      - echo "Fetching the latest artifact from S3 bucket..."
      - mkdir -p build/ear
      - latest_file=$(aws s3api list-objects-v2 --bucket buildartif --query 'sort_by(Contents, &LastModified)[-1].Key' --output text)
      - echo "Latest file in S3: $latest_file"
      - aws s3 cp s3://buildartif/$latest_file build/ear/latest.zip
      - unzip build/ear/latest.zip -d build/ear
      - ls -l build/ear/wise.ear

      - echo "Retrieving GitHub token from Secrets Manager"
      - export GITHUB_TOKEN=$(aws secretsmanager get-secret-value --secret-id LLApplicationToken --query SecretString --output text | jq -r .GITHUB_TOKEN)
      - |
        if [ -z "$GITHUB_TOKEN" ]; then
          echo "Failed to retrieve GitHub token."
          exit 1
        fi

      - echo "Logging in to GitHub Container Registry"
      - echo $GITHUB_TOKEN | docker login ghcr.io -u sabbasani259 --password-stdin

      - echo "Building Docker image with the EAR file..."
      - docker build -t ghcr.io/sabbasani259/wise-ear:latest --build-arg EAR_FILE=build/ear/wise.ear -f docker/Dockerfile .

      - echo "Pushing Docker image to GHCR..."
      - docker push ghcr.io/sabbasani259/wise-ear:latest

      - echo "Docker image pushed to GHCR."

artifacts:
  files:
    - build/ear/wise.ear
  discard-paths: yes
