version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo "Installing dependencies..."
      - java -version

pre_build:
  commands:
    - echo "Starting pre-build phase..."
    - mkdir -p build/classes
    - mkdir -p lib
    # Logging
    - wget https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-core/2.20.0/log4j-core-2.20.0.jar -O lib/log4j-core-2.20.0.jar
    - wget https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-api/2.20.0/log4j-api-2.20.0.jar -O lib/log4j-api-2.20.0.jar
    # Hibernate
    - wget https://repo1.maven.org/maven2/org/hibernate/hibernate-core/5.6.15.Final/hibernate-core-5.6.15.Final.jar -O lib/hibernate-core-5.6.15.Final.jar
    # JSON
    - wget https://repo1.maven.org/maven2/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar -O lib/json-simple-1.1.1.jar
    - wget https://repo1.maven.org/maven2/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar -O lib/gson-2.10.1.jar
    # JAX-RS
    - wget https://repo1.maven.org/maven2/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.jar -O lib/javax.ws.rs-api-2.1.jar
    # Commons IO & Codec
    - wget https://repo1.maven.org/maven2/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar -O lib/commons-io-2.11.0.jar
    - wget https://repo1.maven.org/maven2/org/apache/commons/codec/commons-codec/1.16.0/commons-codec-1.16.0.jar -O lib/commons-codec-1.16.0.jar
    # RabbitMQ
    - wget https://repo1.maven.org/maven2/com/rabbitmq/amqp-client/5.16.0/amqp-client-5.16.0.jar -O lib/amqp-client-5.16.0.jar
    # JasperReports
    - wget https://repo1.maven.org/maven2/net/sf/jasperreports/jasperreports/6.20.0/jasperreports-6.20.0.jar -O lib/jasperreports-6.20.0.jar
    # JavaMail
    - wget https://repo1.maven.org/maven2/com/sun/mail/jakarta.mail/2.0.1/jakarta.mail-2.0.1.jar -O lib/jakarta.mail-2.0.1.jar
    # Kafka
    - wget https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.7.0/kafka-clients-3.7.0.jar -O lib/kafka-clients-3.7.0.jar
    # Find sources and compile
    - find src -name "*.java" > sources.txt
    - cat sources.txt
    - javac -encoding ISO-8859-1 -d build/classes -cp "lib/*" @sources.txt

  build:
    commands:
      - echo "Building EAR file..."
      - mkdir -p build/ear
      - cp -r WebContent/* build/ear/
      - cd build/ear
      - jar -cvf application.ear *
      - cd ../..
      - echo "EAR file created successfully."

  post_build:
    commands:
      - echo "Uploading EAR file to S3..."
      - |
        BUCKET_NAME=$(aws s3api list-buckets --query "Buckets[?contains(Name, 'ap-south-1')].Name | [0]" --output text)
        aws s3 cp build/ear/application.ear s3://$BUCKET_NAME/
      - echo "Upload completed."

artifacts:
  files:
    - build/ear/application.ear
  discard-paths: yes
