version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo "Installing dependencies..."
      - java -version

  pre_build:
  commands:
    - echo "Starting pre-build phase..."
    - mkdir -p build/classes
    # Download JAX-RS API jar (or copy from somewhere)
    - mkdir -p lib
    - wget https://repo1.maven.org/maven2/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.jar -O lib/javax.ws.rs-api-2.1.jar
    # Add other Jersey jars similarly
    - find src -name "*.java" > sources.txt
    - cat sources.txt
    - javac -encoding ISO-8859-1 -d build/classes -cp "lib/*" @sources.txt

  build:
    commands:
      - echo "Building EAR file..."
      - mkdir -p build/ear
      - cp -r WebContent/* build/ear/
      - cd build/ear
      - jar -cvf application.ear *
      - cd ../..
      - echo "EAR file created successfully."

  post_build:
    commands:
      - echo "Uploading EAR file to S3..."
      - |
        BUCKET_NAME=$(aws s3api list-buckets --query "Buckets[?contains(Name, 'ap-south-1')].Name | [0]" --output text)
        aws s3 cp build/ear/application.ear s3://$BUCKET_NAME/
      - echo "Upload completed."

artifacts:
  files:
    - build/ear/application.ear
  discard-paths: yes
