
/*
 * 
 */

package remote.wise.client.UserPreferenceService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Mar 12 16:50:38 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "UserPreferenceServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/UserPreferenceService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class UserPreferenceServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "UserPreferenceServiceService");
    public final static QName UserPreferenceServicePort = new QName("http://webservice.service.wise.remote/", "UserPreferenceServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/UserPreferenceService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/UserPreferenceService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public UserPreferenceServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UserPreferenceServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserPreferenceServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public UserPreferenceServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public UserPreferenceServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public UserPreferenceServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns UserPreferenceService
     */
    @WebEndpoint(name = "UserPreferenceServicePort")
    public UserPreferenceService getUserPreferenceServicePort() {
        return super.getPort(UserPreferenceServicePort, UserPreferenceService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserPreferenceService
     */
    @WebEndpoint(name = "UserPreferenceServicePort")
    public UserPreferenceService getUserPreferenceServicePort(WebServiceFeature... features) {
        return super.getPort(UserPreferenceServicePort, UserPreferenceService.class, features);
    }

}
