package remote.wise.client.StockSummaryService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Mon Jul 08 11:53:53 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "StockSummaryService")
@XmlSeeAlso({ObjectFactory.class})
public interface StockSummaryService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetStockSummary", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.StockSummaryService.GetStockSummary")
    @WebMethod(operationName = "GetStockSummary", action = "GetStockSummary")
    @ResponseWrapper(localName = "GetStockSummaryResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.StockSummaryService.GetStockSummaryResponse")
    public java.util.List<remote.wise.client.StockSummaryService.StockSummaryRespContract> getStockSummary(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.StockSummaryService.StockSummaryReqContract reqObj
    ) throws CustomFault;
}
