package remote.wise.client.EventTypeService;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Mar 09 16:19:35 IST 2016
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "EventTypeService")
@XmlSeeAlso({ObjectFactory.class})
public interface EventTypeService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetEventTypes", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.EventTypeService.GetEventTypes")
    @WebMethod(operationName = "GetEventTypes", action = "GetEventTypes")
    @ResponseWrapper(localName = "GetEventTypesResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.EventTypeService.GetEventTypesResponse")
    public java.util.List<remote.wise.client.EventTypeService.EventTypeRespContract> getEventTypes() throws CustomFault;
}
