package remote.wise.client.RegConfirmationService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed May 14 19:07:34 IST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "RegConfirmationService")
@XmlSeeAlso({ObjectFactory.class})
public interface RegConfirmationService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "SetRegConfirmation", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.RegConfirmationService.SetRegConfirmation")
    @WebMethod(operationName = "SetRegConfirmation", action = "SetRegConfirmation")
    @ResponseWrapper(localName = "SetRegConfirmationResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.RegConfirmationService.SetRegConfirmationResponse")
    public java.lang.String setRegConfirmation(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.RegConfirmationService.RegConfirmationRespContract reqObj
    ) throws CustomFault;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "DeleteRegistrationConfirmation", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.RegConfirmationService.DeleteRegistrationConfirmation")
    @WebMethod(operationName = "DeleteRegistrationConfirmation", action = "DeleteRegistrationConfirmation")
    @ResponseWrapper(localName = "DeleteRegistrationConfirmationResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.RegConfirmationService.DeleteRegistrationConfirmationResponse")
    public java.lang.String deleteRegistrationConfirmation(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.RegConfirmationService.RegConfirmationRespContract reqObj
    ) throws CustomFault;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetRegistrationConfirmation", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.RegConfirmationService.GetRegistrationConfirmation")
    @WebMethod(operationName = "GetRegistrationConfirmation", action = "GetRegistrationConfirmation")
    @ResponseWrapper(localName = "GetRegistrationConfirmationResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.RegConfirmationService.GetRegistrationConfirmationResponse")
    public remote.wise.client.RegConfirmationService.RegConfirmationRespContract getRegistrationConfirmation(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.RegConfirmationService.RegConfirmationReqContract reqObj
    ) throws CustomFault;
}
