
/*
 * 
 */

package remote.wise.client.RegConfirmationService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed May 14 19:07:34 IST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "RegConfirmationServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/RegConfirmationService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class RegConfirmationServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "RegConfirmationServiceService");
    public final static QName RegConfirmationServicePort = new QName("http://webservice.service.wise.remote/", "RegConfirmationServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/RegConfirmationService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/RegConfirmationService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public RegConfirmationServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RegConfirmationServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegConfirmationServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public RegConfirmationServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public RegConfirmationServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public RegConfirmationServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns RegConfirmationService
     */
    @WebEndpoint(name = "RegConfirmationServicePort")
    public RegConfirmationService getRegConfirmationServicePort() {
        return super.getPort(RegConfirmationServicePort, RegConfirmationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegConfirmationService
     */
    @WebEndpoint(name = "RegConfirmationServicePort")
    public RegConfirmationService getRegConfirmationServicePort(WebServiceFeature... features) {
        return super.getPort(RegConfirmationServicePort, RegConfirmationService.class, features);
    }

}
