
/*
 * 
 */

package remote.wise.client.NotificationSummaryReportService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Nov 06 11:26:55 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "NotificationSummaryReportServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/NotificationSummaryReportService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class NotificationSummaryReportServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "NotificationSummaryReportServiceService");
    public final static QName NotificationSummaryReportServicePort = new QName("http://webservice.service.wise.remote/", "NotificationSummaryReportServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/NotificationSummaryReportService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/NotificationSummaryReportService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public NotificationSummaryReportServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NotificationSummaryReportServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NotificationSummaryReportServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public NotificationSummaryReportServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public NotificationSummaryReportServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public NotificationSummaryReportServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns NotificationSummaryReportService
     */
    @WebEndpoint(name = "NotificationSummaryReportServicePort")
    public NotificationSummaryReportService getNotificationSummaryReportServicePort() {
        return super.getPort(NotificationSummaryReportServicePort, NotificationSummaryReportService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NotificationSummaryReportService
     */
    @WebEndpoint(name = "NotificationSummaryReportServicePort")
    public NotificationSummaryReportService getNotificationSummaryReportServicePort(WebServiceFeature... features) {
        return super.getPort(NotificationSummaryReportServicePort, NotificationSummaryReportService.class, features);
    }

}
