package remote.wise.client.NotificationSummaryReportService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Nov 06 11:26:55 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "NotificationSummaryReportService")
@XmlSeeAlso({ObjectFactory.class})
public interface NotificationSummaryReportService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "NotificationSummary", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.NotificationSummaryReportService.NotificationSummary")
    @WebMethod(operationName = "NotificationSummary", action = "NotificationSummary")
    @ResponseWrapper(localName = "NotificationSummaryResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.NotificationSummaryReportService.NotificationSummaryResponse")
    public java.util.List<remote.wise.client.NotificationSummaryReportService.NotificationSummaryReportRespContract> notificationSummary(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.NotificationSummaryReportService.NotificationSummaryReportReqContract reqObj
    ) throws CustomFault;
}
