package remote.wise.client.MachineAlertsTrendDataService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Oct 09 15:07:51 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "MachineAlertsTrendDataService")
@XmlSeeAlso({ObjectFactory.class})
public interface MachineAlertsTrendDataService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getMachineAlertsTrendData", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.MachineAlertsTrendDataService.GetMachineAlertsTrendData")
    @WebMethod(action = "getMachineAlertsTrendData")
    @ResponseWrapper(localName = "getMachineAlertsTrendDataResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.MachineAlertsTrendDataService.GetMachineAlertsTrendDataResponse")
    public java.util.List<remote.wise.client.MachineAlertsTrendDataService.MachineAlertsTrendDataRespContract> getMachineAlertsTrendData(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.MachineAlertsTrendDataService.MachineAlertsTrendDataReqContract reqObj
    ) throws CustomFault;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getMachineAlertsTrendDataForAllZones", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.MachineAlertsTrendDataService.GetMachineAlertsTrendDataForAllZones")
    @WebMethod(action = "getMachineAlertsTrendDataForAllZones")
    @ResponseWrapper(localName = "getMachineAlertsTrendDataForAllZonesResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.MachineAlertsTrendDataService.GetMachineAlertsTrendDataForAllZonesResponse")
    public java.util.List<remote.wise.client.MachineAlertsTrendDataService.MachineAlertsTrendDataRespContract> getMachineAlertsTrendDataForAllZones(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.MachineAlertsTrendDataService.MachineAlertsTrendDataReqContract reqObj
    ) throws CustomFault;
}
