
/*
 * 
 */

package remote.wise.client.MachineAlertsTrendDataService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Oct 09 15:07:51 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "MachineAlertsTrendDataServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/MachineAlertsTrendDataService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class MachineAlertsTrendDataServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "MachineAlertsTrendDataServiceService");
    public final static QName MachineAlertsTrendDataServicePort = new QName("http://webservice.service.wise.remote/", "MachineAlertsTrendDataServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/MachineAlertsTrendDataService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/MachineAlertsTrendDataService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public MachineAlertsTrendDataServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MachineAlertsTrendDataServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MachineAlertsTrendDataServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public MachineAlertsTrendDataServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public MachineAlertsTrendDataServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public MachineAlertsTrendDataServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns MachineAlertsTrendDataService
     */
    @WebEndpoint(name = "MachineAlertsTrendDataServicePort")
    public MachineAlertsTrendDataService getMachineAlertsTrendDataServicePort() {
        return super.getPort(MachineAlertsTrendDataServicePort, MachineAlertsTrendDataService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MachineAlertsTrendDataService
     */
    @WebEndpoint(name = "MachineAlertsTrendDataServicePort")
    public MachineAlertsTrendDataService getMachineAlertsTrendDataServicePort(WebServiceFeature... features) {
        return super.getPort(MachineAlertsTrendDataServicePort, MachineAlertsTrendDataService.class, features);
    }

}
