package remote.EAscheduler.AssetProfile;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Fri Jun 19 11:47:57 IST 2015
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservices.EAintegration.wise.remote/", name = "AssetProfileSample")
@XmlSeeAlso({ObjectFactory.class})
public interface AssetProfileSample {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "processEAassetProfileData", targetNamespace = "http://webservices.EAintegration.wise.remote/", className = "remote.EAscheduler.AssetProfile.ProcessEAassetProfileData")
    @WebMethod(action = "processEAassetProfileData")
    @ResponseWrapper(localName = "processEAassetProfileDataResponse", targetNamespace = "http://webservices.EAintegration.wise.remote/", className = "remote.EAscheduler.AssetProfile.ProcessEAassetProfileDataResponse")
    public java.lang.String processEAassetProfileData(
        @WebParam(name = "msg", targetNamespace = "")
        java.lang.String msg
    );
}
