
package remote.wise.client.UserDetailsService;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Thu Aug 29 15:23:42 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */

@WebFault(name = "IOException", targetNamespace = "http://webservice.service.wise.remote/")
public class IOException_Exception extends Exception {
    public static final long serialVersionUID = 20130829152342L;
    
    private remote.wise.client.UserDetailsService.IOException ioException;

    public IOException_Exception() {
        super();
    }
    
    public IOException_Exception(String message) {
        super(message);
    }
    
    public IOException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public IOException_Exception(String message, remote.wise.client.UserDetailsService.IOException ioException) {
        super(message);
        this.ioException = ioException;
    }

    public IOException_Exception(String message, remote.wise.client.UserDetailsService.IOException ioException, Throwable cause) {
        super(message, cause);
        this.ioException = ioException;
    }

    public remote.wise.client.UserDetailsService.IOException getFaultInfo() {
        return this.ioException;
    }
}
