package remote.wise.client.UserDetailsService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Thu Aug 29 15:23:42 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "UserDetailsService")
@XmlSeeAlso({ObjectFactory.class})
public interface UserDetailsService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetUserDetails", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.UserDetailsService.GetUserDetails")
    @WebMethod(operationName = "GetUserDetails", action = "GetUserDetails")
    @ResponseWrapper(localName = "GetUserDetailsResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.UserDetailsService.GetUserDetailsResponse")
    public java.util.List<remote.wise.client.UserDetailsService.UserDetailsRespContract> getUserDetails(
        @WebParam(name = "userReqContract", targetNamespace = "")
        remote.wise.client.UserDetailsService.UserDetailsReqContract userReqContract
    ) throws CustomFault;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "SetUserDetails", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.UserDetailsService.SetUserDetails")
    @WebMethod(operationName = "SetUserDetails", action = "SetUserDetails")
    @ResponseWrapper(localName = "SetUserDetailsResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.UserDetailsService.SetUserDetailsResponse")
    public java.lang.String setUserDetails(
        @WebParam(name = "setUserDetails", targetNamespace = "")
        remote.wise.client.UserDetailsService.UserDetailsRespContract setUserDetails
    ) throws CustomFault, IOException_Exception;
}
