package remote.wise.client.TenancyAssetsService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Mar 13 18:59:42 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "TenancyAssetsService")
@XmlSeeAlso({ObjectFactory.class})
public interface TenancyAssetsService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetTenancyAssets", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.TenancyAssetsService.GetTenancyAssets")
    @WebMethod(operationName = "GetTenancyAssets", action = "GetTenancyAssets")
    @ResponseWrapper(localName = "GetTenancyAssetsResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.TenancyAssetsService.GetTenancyAssetsResponse")
    public remote.wise.client.TenancyAssetsService.TenancyAssetsRespContract getTenancyAssets(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.TenancyAssetsService.TenancyAssetsReqContract reqObj
    ) throws CustomFault;
}
