
/*
 * 
 */

package remote.wise.client.HAJassetLocationDetailsService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed May 27 18:37:42 IST 2015
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "HAJassetLocationDetailsServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/HAJassetLocationDetailsService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class HAJassetLocationDetailsServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "HAJassetLocationDetailsServiceService");
    public final static QName HAJassetLocationDetailsServicePort = new QName("http://webservice.service.wise.remote/", "HAJassetLocationDetailsServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/HAJassetLocationDetailsService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/HAJassetLocationDetailsService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public HAJassetLocationDetailsServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HAJassetLocationDetailsServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HAJassetLocationDetailsServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public HAJassetLocationDetailsServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public HAJassetLocationDetailsServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public HAJassetLocationDetailsServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns HAJassetLocationDetailsService
     */
    @WebEndpoint(name = "HAJassetLocationDetailsServicePort")
    public HAJassetLocationDetailsService getHAJassetLocationDetailsServicePort() {
        return super.getPort(HAJassetLocationDetailsServicePort, HAJassetLocationDetailsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HAJassetLocationDetailsService
     */
    @WebEndpoint(name = "HAJassetLocationDetailsServicePort")
    public HAJassetLocationDetailsService getHAJassetLocationDetailsServicePort(WebServiceFeature... features) {
        return super.getPort(HAJassetLocationDetailsServicePort, HAJassetLocationDetailsService.class, features);
    }

}
