
/*
 * 
 */

package remote.wise.client.CustomersCodeUnderDealerCodeService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Thu Mar 10 13:09:16 IST 2016
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "CustomersCodeUnderDealerCodeServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/CustomersCodeUnderDealerCodeService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class CustomersCodeUnderDealerCodeServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "CustomersCodeUnderDealerCodeServiceService");
    public final static QName CustomersCodeUnderDealerCodeServicePort = new QName("http://webservice.service.wise.remote/", "CustomersCodeUnderDealerCodeServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/CustomersCodeUnderDealerCodeService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/CustomersCodeUnderDealerCodeService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public CustomersCodeUnderDealerCodeServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CustomersCodeUnderDealerCodeServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomersCodeUnderDealerCodeServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CustomersCodeUnderDealerCodeServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public CustomersCodeUnderDealerCodeServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public CustomersCodeUnderDealerCodeServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns CustomersCodeUnderDealerCodeService
     */
    @WebEndpoint(name = "CustomersCodeUnderDealerCodeServicePort")
    public CustomersCodeUnderDealerCodeService getCustomersCodeUnderDealerCodeServicePort() {
        return super.getPort(CustomersCodeUnderDealerCodeServicePort, CustomersCodeUnderDealerCodeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomersCodeUnderDealerCodeService
     */
    @WebEndpoint(name = "CustomersCodeUnderDealerCodeServicePort")
    public CustomersCodeUnderDealerCodeService getCustomersCodeUnderDealerCodeServicePort(WebServiceFeature... features) {
        return super.getPort(CustomersCodeUnderDealerCodeServicePort, CustomersCodeUnderDealerCodeService.class, features);
    }

}
