
package remote.wise.client.CustomersCodeUnderDealerCodeService;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Thu Mar 10 13:09:16 IST 2016
 * Generated source version: 2.3.1-patch-01
 * 
 */

@WebFault(name = "CustomFault", targetNamespace = "http://webservice.service.wise.remote/")
public class CustomFault extends Exception {
    public static final long serialVersionUID = 20160310130916L;
    
    private java.lang.String customFault;

    public CustomFault() {
        super();
    }
    
    public CustomFault(String message) {
        super(message);
    }
    
    public CustomFault(String message, Throwable cause) {
        super(message, cause);
    }

    public CustomFault(String message, java.lang.String customFault) {
        super(message);
        this.customFault = customFault;
    }

    public CustomFault(String message, java.lang.String customFault, Throwable cause) {
        super(message, cause);
        this.customFault = customFault;
    }

    public java.lang.String getFaultInfo() {
        return this.customFault;
    }
}
