package remote.wise.client.CustomersCodeUnderDealerCodeService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Thu Mar 10 13:09:16 IST 2016
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "CustomersCodeUnderDealerCodeService")
@XmlSeeAlso({ObjectFactory.class})
public interface CustomersCodeUnderDealerCodeService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetCustomersCodeForDealer", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.CustomersCodeUnderDealerCodeService.GetCustomersCodeForDealer")
    @WebMethod(operationName = "GetCustomersCodeForDealer", action = "GetCustomersCodeForDealer")
    @ResponseWrapper(localName = "GetCustomersCodeForDealerResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.CustomersCodeUnderDealerCodeService.GetCustomersCodeForDealerResponse")
    public remote.wise.client.CustomersCodeUnderDealerCodeService.CustomerCodeForDealerCodeRespContract getCustomersCodeForDealer(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.CustomersCodeUnderDealerCodeService.CustomerCodeForDealerCodeReqContract reqObj
    ) throws CustomFault;
}
