
/*
 * 
 */

package remote.wise.client.MachineRPMBandTrendDataService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Thu Oct 17 13:02:42 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "MachineRPMBandTrendDataServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/MachineRPMBandTrendDataService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class MachineRPMBandTrendDataServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "MachineRPMBandTrendDataServiceService");
    public final static QName MachineRPMBandTrendDataServicePort = new QName("http://webservice.service.wise.remote/", "MachineRPMBandTrendDataServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/MachineRPMBandTrendDataService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/MachineRPMBandTrendDataService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public MachineRPMBandTrendDataServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MachineRPMBandTrendDataServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MachineRPMBandTrendDataServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public MachineRPMBandTrendDataServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public MachineRPMBandTrendDataServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public MachineRPMBandTrendDataServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns MachineRPMBandTrendDataService
     */
    @WebEndpoint(name = "MachineRPMBandTrendDataServicePort")
    public MachineRPMBandTrendDataService getMachineRPMBandTrendDataServicePort() {
        return super.getPort(MachineRPMBandTrendDataServicePort, MachineRPMBandTrendDataService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MachineRPMBandTrendDataService
     */
    @WebEndpoint(name = "MachineRPMBandTrendDataServicePort")
    public MachineRPMBandTrendDataService getMachineRPMBandTrendDataServicePort(WebServiceFeature... features) {
        return super.getPort(MachineRPMBandTrendDataServicePort, MachineRPMBandTrendDataService.class, features);
    }

}
