package remote.wise.client.GetDealersForZoneService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Mar 12 15:57:17 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "GetDealersForZoneService")
@XmlSeeAlso({ObjectFactory.class})
public interface GetDealersForZoneService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetDealersForZone", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.GetDealersForZoneService.GetDealersForZone")
    @WebMethod(operationName = "GetDealersForZone", action = "GetDealersForZone")
    @ResponseWrapper(localName = "GetDealersForZoneResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.GetDealersForZoneService.GetDealersForZoneResponse")
    public java.util.List<remote.wise.client.GetDealersForZoneService.DealersUnderZoneRespContract> getDealersForZone(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.GetDealersForZoneService.DealersUnderZoneReqContract reqObj
    ) throws CustomFault;
}
