package remote.wise.client.NotificationSummaryService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Jul 10 12:35:34 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "NotificationSummaryService")
@XmlSeeAlso({ObjectFactory.class})
public interface NotificationSummaryService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetNotificationSummaryService", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.NotificationSummaryService.GetNotificationSummaryService")
    @WebMethod(operationName = "GetNotificationSummaryService", action = "GetNotificationSummaryService")
    @ResponseWrapper(localName = "GetNotificationSummaryServiceResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.NotificationSummaryService.GetNotificationSummaryServiceResponse")
    public java.util.List<remote.wise.client.NotificationSummaryService.NotificationSummaryRespContract> getNotificationSummaryService(
        @WebParam(name = "reqCont", targetNamespace = "")
        remote.wise.client.NotificationSummaryService.NotificationSummaryReqContract reqCont
    ) throws CustomFault;
}
