package remote.wise.client.ReportSubscriptionService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Mon Apr 15 12:11:57 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "ReportSubscriptionService")
@XmlSeeAlso({ObjectFactory.class})
public interface ReportSubscriptionService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetReportSubscriptionService", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.ReportSubscriptionService.GetReportSubscriptionService")
    @WebMethod(operationName = "GetReportSubscriptionService", action = "GetReportSubscriptionService")
    @ResponseWrapper(localName = "GetReportSubscriptionServiceResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.ReportSubscriptionService.GetReportSubscriptionServiceResponse")
    public java.util.List<remote.wise.client.ReportSubscriptionService.ReportSubscriptionRespContract> getReportSubscriptionService(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.ReportSubscriptionService.ReportSubscriptionReqContract reqObj
    ) throws CustomFault;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "SetReportSubscriptionService", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.ReportSubscriptionService.SetReportSubscriptionService")
    @WebMethod(operationName = "SetReportSubscriptionService")
    @ResponseWrapper(localName = "SetReportSubscriptionServiceResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.ReportSubscriptionService.SetReportSubscriptionServiceResponse")
    public java.lang.String setReportSubscriptionService(
        @WebParam(name = "response", targetNamespace = "")
        java.util.List<remote.wise.client.ReportSubscriptionService.ReportSubscriptionRespContract> response
    );
}
