
/*
 * 
 */

package remote.wise.client.MapService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Sep 11 14:54:10 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "MapServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/MapService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class MapServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "MapServiceService");
    public final static QName MapServicePort = new QName("http://webservice.service.wise.remote/", "MapServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/MapService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/MapService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public MapServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MapServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MapServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public MapServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public MapServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public MapServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns MapService
     */
    @WebEndpoint(name = "MapServicePort")
    public MapService getMapServicePort() {
        return super.getPort(MapServicePort, MapService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MapService
     */
    @WebEndpoint(name = "MapServicePort")
    public MapService getMapServicePort(WebServiceFeature... features) {
        return super.getPort(MapServicePort, MapService.class, features);
    }

}
