package remote.wise.client.VinProcessingService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Mon Sep 15 16:57:42 IST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "VinProcessingService")
@XmlSeeAlso({ObjectFactory.class})
public interface VinProcessingService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "VinSearch", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.VinProcessingService.VinSearch")
    @WebMethod(operationName = "VinSearch", action = "VinSearch")
    @ResponseWrapper(localName = "VinSearchResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.VinProcessingService.VinSearchResponse")
    public java.util.List<remote.wise.client.VinProcessingService.VinSearchRespContract> vinSearch(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.VinProcessingService.VinSearchReqContract reqObj
    ) throws CustomFault;
}
