
/*
 * 
 */

package remote.wise.client.VinProcessingService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Mon Sep 15 16:57:42 IST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "VinProcessingServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/VinProcessingService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class VinProcessingServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "VinProcessingServiceService");
    public final static QName VinProcessingServicePort = new QName("http://webservice.service.wise.remote/", "VinProcessingServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/VinProcessingService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/VinProcessingService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public VinProcessingServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public VinProcessingServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VinProcessingServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public VinProcessingServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public VinProcessingServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public VinProcessingServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns VinProcessingService
     */
    @WebEndpoint(name = "VinProcessingServicePort")
    public VinProcessingService getVinProcessingServicePort() {
        return super.getPort(VinProcessingServicePort, VinProcessingService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VinProcessingService
     */
    @WebEndpoint(name = "VinProcessingServicePort")
    public VinProcessingService getVinProcessingServicePort(WebServiceFeature... features) {
        return super.getPort(VinProcessingServicePort, VinProcessingService.class, features);
    }

}
