
/*
 * 
 */

package remote.wise.client.MachineCommReportService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Fri Jan 09 11:18:23 IST 2015
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "MachineCommReportServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/MachineCommReportService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class MachineCommReportServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "MachineCommReportServiceService");
    public final static QName MachineCommReportServicePort = new QName("http://webservice.service.wise.remote/", "MachineCommReportServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/MachineCommReportService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/MachineCommReportService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public MachineCommReportServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MachineCommReportServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MachineCommReportServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public MachineCommReportServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public MachineCommReportServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public MachineCommReportServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns MachineCommReportService
     */
    @WebEndpoint(name = "MachineCommReportServicePort")
    public MachineCommReportService getMachineCommReportServicePort() {
        return super.getPort(MachineCommReportServicePort, MachineCommReportService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MachineCommReportService
     */
    @WebEndpoint(name = "MachineCommReportServicePort")
    public MachineCommReportService getMachineCommReportServicePort(WebServiceFeature... features) {
        return super.getPort(MachineCommReportServicePort, MachineCommReportService.class, features);
    }

}
