
/*
 * 
 */

package remote.wise.EAintegration.clientPackage.DealerInformationService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Jul 31 14:31:21 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "DealerInformationServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/DealerInformationService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class DealerInformationServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "DealerInformationServiceService");
    public final static QName DealerInformationServicePort = new QName("http://webservice.service.wise.remote/", "DealerInformationServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/DealerInformationService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/DealerInformationService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public DealerInformationServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DealerInformationServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DealerInformationServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public DealerInformationServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public DealerInformationServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public DealerInformationServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns DealerInformationService
     */
    @WebEndpoint(name = "DealerInformationServicePort")
    public DealerInformationService getDealerInformationServicePort() {
        return super.getPort(DealerInformationServicePort, DealerInformationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DealerInformationService
     */
    @WebEndpoint(name = "DealerInformationServicePort")
    public DealerInformationService getDealerInformationServicePort(WebServiceFeature... features) {
        return super.getPort(DealerInformationServicePort, DealerInformationService.class, features);
    }

}
