package remote.wise.EAintegration.clientPackage.DealerInformationService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Jul 31 14:31:21 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "DealerInformationService")
@XmlSeeAlso({ObjectFactory.class})
public interface DealerInformationService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "setDealerDetails", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.EAintegration.clientPackage.DealerInformationService.SetDealerDetails")
    @WebMethod(action = "setDealerDetails")
    @ResponseWrapper(localName = "setDealerDetailsResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.EAintegration.clientPackage.DealerInformationService.SetDealerDetailsResponse")
    public java.lang.String setDealerDetails(
        @WebParam(name = "dealerCode", targetNamespace = "")
        java.lang.String dealerCode,
        @WebParam(name = "dealerName", targetNamespace = "")
        java.lang.String dealerName,
        @WebParam(name = "addressLine1", targetNamespace = "")
        java.lang.String addressLine1,
        @WebParam(name = "addressLine2", targetNamespace = "")
        java.lang.String addressLine2,
        @WebParam(name = "city", targetNamespace = "")
        java.lang.String city,
        @WebParam(name = "zipCode", targetNamespace = "")
        java.lang.String zipCode,
        @WebParam(name = "state", targetNamespace = "")
        java.lang.String state,
        @WebParam(name = "zone", targetNamespace = "")
        java.lang.String zone,
        @WebParam(name = "country", targetNamespace = "")
        java.lang.String country,
        @WebParam(name = "email", targetNamespace = "")
        java.lang.String email,
        @WebParam(name = "contactNumber", targetNamespace = "")
        java.lang.String contactNumber,
        @WebParam(name = "fax", targetNamespace = "")
        java.lang.String fax,
        @WebParam(name = "JcbRoCode", targetNamespace = "")
        java.lang.String jcbRoCode,
        @WebParam(name = "messageId", targetNamespace = "")
        java.lang.String messageId,
        @WebParam(name = "fileRef", targetNamespace = "")
        java.lang.String fileRef,
        @WebParam(name = "process", targetNamespace = "")
        java.lang.String process,
        @WebParam(name = "reprocessJobCode", targetNamespace = "")
        java.lang.String reprocessJobCode
    );
}
