package remote.EAscheduler.DealerMapping;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Dec 30 10:41:04 IST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservices.EAintegration.wise.remote/", name = "DealerMappingSample")
@XmlSeeAlso({ObjectFactory.class})
public interface DealerMappingSample {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "processEAdealerMappingData", targetNamespace = "http://webservices.EAintegration.wise.remote/", className = "remote.EAscheduler.DealerMapping.ProcessEAdealerMappingData")
    @WebMethod(action = "processEAdealerMappingData")
    @ResponseWrapper(localName = "processEAdealerMappingDataResponse", targetNamespace = "http://webservices.EAintegration.wise.remote/", className = "remote.EAscheduler.DealerMapping.ProcessEAdealerMappingDataResponse")
    public java.lang.String processEAdealerMappingData(
        @WebParam(name = "msg", targetNamespace = "")
        java.lang.String msg
    );
}
