
/*
 * 
 */

package remote.wise.client.ForgotPasswordService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Thu Mar 28 09:56:18 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "ForgotPasswordServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/ForgotPasswordService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class ForgotPasswordServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "ForgotPasswordServiceService");
    public final static QName ForgotPasswordServicePort = new QName("http://webservice.service.wise.remote/", "ForgotPasswordServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/ForgotPasswordService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/ForgotPasswordService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public ForgotPasswordServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ForgotPasswordServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ForgotPasswordServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ForgotPasswordServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public ForgotPasswordServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public ForgotPasswordServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ForgotPasswordService
     */
    @WebEndpoint(name = "ForgotPasswordServicePort")
    public ForgotPasswordService getForgotPasswordServicePort() {
        return super.getPort(ForgotPasswordServicePort, ForgotPasswordService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ForgotPasswordService
     */
    @WebEndpoint(name = "ForgotPasswordServicePort")
    public ForgotPasswordService getForgotPasswordServicePort(WebServiceFeature... features) {
        return super.getPort(ForgotPasswordServicePort, ForgotPasswordService.class, features);
    }

}
