package remote.wise.client.ForgotPasswordService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Thu Mar 28 09:56:18 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "ForgotPasswordService")
@XmlSeeAlso({ObjectFactory.class})
public interface ForgotPasswordService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetForgottenPassword", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.ForgotPasswordService.GetForgottenPassword")
    @WebMethod(operationName = "GetForgottenPassword", action = "GetForgottenPassword")
    @ResponseWrapper(localName = "GetForgottenPasswordResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.ForgotPasswordService.GetForgottenPasswordResponse")
    public remote.wise.client.ForgotPasswordService.ForgotPasswordRespContract getForgottenPassword(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.ForgotPasswordService.ForgotPasswordReqContract reqObj
    ) throws CustomFault;
}
