package remote.wise.client.UnderUtilizedMachinesService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Feb 11 11:51:58 IST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "UnderUtilizedMachinesService")
@XmlSeeAlso({ObjectFactory.class})
public interface UnderUtilizedMachinesService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetUnderUtilizedMachines", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.UnderUtilizedMachinesService.GetUnderUtilizedMachines")
    @WebMethod(operationName = "GetUnderUtilizedMachines", action = "GetUnderUtilizedMachines")
    @ResponseWrapper(localName = "GetUnderUtilizedMachinesResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.UnderUtilizedMachinesService.GetUnderUtilizedMachinesResponse")
    public java.util.List<remote.wise.client.UnderUtilizedMachinesService.UnderUtilizedMachinesRespContract> getUnderUtilizedMachines(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.UnderUtilizedMachinesService.UnderUtilizedMachinesReqContract reqObj
    ) throws CustomFault;
}
