package remote.wise.client.LandmarkDetailsService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Sat Jun 08 14:35:43 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "LandmarkDetailsService")
@XmlSeeAlso({ObjectFactory.class})
public interface LandmarkDetailsService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "SetLandmarkDetails", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.LandmarkDetailsService.SetLandmarkDetails")
    @WebMethod(operationName = "SetLandmarkDetails", action = "SetLandmarkDetails")
    @ResponseWrapper(localName = "SetLandmarkDetailsResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.LandmarkDetailsService.SetLandmarkDetailsResponse")
    public remote.wise.client.LandmarkDetailsService.LandmarkDetailsReqContract setLandmarkDetails(
        @WebParam(name = "RespObj", targetNamespace = "")
        remote.wise.client.LandmarkDetailsService.LandmarkDetailsRespContract respObj
    ) throws CustomFault;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetLandmarkDetails", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.LandmarkDetailsService.GetLandmarkDetails")
    @WebMethod(operationName = "GetLandmarkDetails", action = "GetLandmarkDetails")
    @ResponseWrapper(localName = "GetLandmarkDetailsResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.LandmarkDetailsService.GetLandmarkDetailsResponse")
    public java.util.List<remote.wise.client.LandmarkDetailsService.LandmarkDetailsRespContract> getLandmarkDetails(
        @WebParam(name = "ReqObj", targetNamespace = "")
        remote.wise.client.LandmarkDetailsService.LandmarkDetailsReqContract reqObj
    ) throws CustomFault;
}
