
/*
 * 
 */

package remote.wise.client.LandmarkDetailsService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Sat Jun 08 14:35:43 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "LandmarkDetailsServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/LandmarkDetailsService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class LandmarkDetailsServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "LandmarkDetailsServiceService");
    public final static QName LandmarkDetailsServicePort = new QName("http://webservice.service.wise.remote/", "LandmarkDetailsServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/LandmarkDetailsService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/LandmarkDetailsService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public LandmarkDetailsServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LandmarkDetailsServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LandmarkDetailsServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public LandmarkDetailsServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public LandmarkDetailsServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public LandmarkDetailsServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns LandmarkDetailsService
     */
    @WebEndpoint(name = "LandmarkDetailsServicePort")
    public LandmarkDetailsService getLandmarkDetailsServicePort() {
        return super.getPort(LandmarkDetailsServicePort, LandmarkDetailsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LandmarkDetailsService
     */
    @WebEndpoint(name = "LandmarkDetailsServicePort")
    public LandmarkDetailsService getLandmarkDetailsServicePort(WebServiceFeature... features) {
        return super.getPort(LandmarkDetailsServicePort, LandmarkDetailsService.class, features);
    }

}
