package remote.wise.client.DeleteLandmarkCategoryService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Apr 24 12:10:56 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "DeleteLandmarkCategoryService")
@XmlSeeAlso({ObjectFactory.class})
public interface DeleteLandmarkCategoryService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "SetDeleteLandmarkCategory", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.DeleteLandmarkCategoryService.SetDeleteLandmarkCategory")
    @WebMethod(operationName = "SetDeleteLandmarkCategory", action = "SetDeleteLandmarkCategory")
    @ResponseWrapper(localName = "SetDeleteLandmarkCategoryResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.DeleteLandmarkCategoryService.SetDeleteLandmarkCategoryResponse")
    public java.lang.String setDeleteLandmarkCategory(
        @WebParam(name = "setDeleteLandmarkCategory", targetNamespace = "")
        remote.wise.client.DeleteLandmarkCategoryService.DeleteLandmarkCategoryRespContract setDeleteLandmarkCategory
    ) throws CustomFault;
}
