
/*
 * 
 */

package remote.wise.client.ModelService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Thu Mar 28 11:13:14 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "ModelServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/ModelService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class ModelServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "ModelServiceService");
    public final static QName ModelServicePort = new QName("http://webservice.service.wise.remote/", "ModelServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/ModelService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/ModelService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public ModelServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ModelServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ModelServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ModelServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public ModelServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public ModelServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ModelService
     */
    @WebEndpoint(name = "ModelServicePort")
    public ModelService getModelServicePort() {
        return super.getPort(ModelServicePort, ModelService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ModelService
     */
    @WebEndpoint(name = "ModelServicePort")
    public ModelService getModelServicePort(WebServiceFeature... features) {
        return super.getPort(ModelServicePort, ModelService.class, features);
    }

}
