package remote.wise.client.ModelService;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Thu Mar 28 11:13:14 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "ModelService")
@XmlSeeAlso({ObjectFactory.class})
public interface ModelService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetModelMap", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.ModelService.GetModelMap")
    @WebMethod(operationName = "GetModelMap", action = "GetModelMap")
    @ResponseWrapper(localName = "GetModelMapResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.ModelService.GetModelMapResponse")
    public remote.wise.client.ModelService.ModelResponseContract getModelMap() throws CustomFault;
}
