package remote.EAscheduler.AssetPersonality;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Fri Jun 19 11:46:09 IST 2015
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservices.EAintegration.wise.remote/", name = "AssetPersonalitySample")
@XmlSeeAlso({ObjectFactory.class})
public interface AssetPersonalitySample {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "processEAassetPersData", targetNamespace = "http://webservices.EAintegration.wise.remote/", className = "remote.EAscheduler.AssetPersonality.ProcessEAassetPersData")
    @WebMethod(action = "processEAassetPersData")
    @ResponseWrapper(localName = "processEAassetPersDataResponse", targetNamespace = "http://webservices.EAintegration.wise.remote/", className = "remote.EAscheduler.AssetPersonality.ProcessEAassetPersDataResponse")
    public java.lang.String processEAassetPersData(
        @WebParam(name = "msg", targetNamespace = "")
        java.lang.String msg
    );
}
