package remote.wise.client.DownloadAempService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Mar 13 23:18:01 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "DownloadAempService")
@XmlSeeAlso({ObjectFactory.class})
public interface DownloadAempService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetDownloadAemp", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.DownloadAempService.GetDownloadAemp")
    @WebMethod(operationName = "GetDownloadAemp", action = "GetDownloadAemp")
    @ResponseWrapper(localName = "GetDownloadAempResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.DownloadAempService.GetDownloadAempResponse")
    public java.util.List<remote.wise.client.DownloadAempService.DownloadAempRespContract> getDownloadAemp(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.DownloadAempService.DownloadAempReqContract reqObj
    ) throws CustomFault;
}
