package remote.wise.client.AssetOwnershipManagementService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Mar 13 18:32:21 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "AssetOwnershipManagementService")
@XmlSeeAlso({ObjectFactory.class})
public interface AssetOwnershipManagementService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "SetAssetOwnership", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.AssetOwnershipManagementService.SetAssetOwnership")
    @WebMethod(operationName = "SetAssetOwnership", action = "SetAssetOwnership")
    @ResponseWrapper(localName = "SetAssetOwnershipResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.AssetOwnershipManagementService.SetAssetOwnershipResponse")
    public java.lang.String setAssetOwnership(
        @WebParam(name = "reqObject", targetNamespace = "")
        remote.wise.client.AssetOwnershipManagementService.AssetOwnershipRespContract reqObject
    ) throws CustomFault;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetAssetOwnership", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.AssetOwnershipManagementService.GetAssetOwnership")
    @WebMethod(operationName = "GetAssetOwnership", action = "GetAssetOwnership")
    @ResponseWrapper(localName = "GetAssetOwnershipResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.AssetOwnershipManagementService.GetAssetOwnershipResponse")
    public remote.wise.client.AssetOwnershipManagementService.AssetOwnershipRespContract getAssetOwnership(
        @WebParam(name = "reqObject", targetNamespace = "")
        remote.wise.client.AssetOwnershipManagementService.AssetOwnershipReqContract reqObject
    ) throws CustomFault;
}
