package remote.wise.EAintegration.clientPackage.MasterServiceSchedule;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Mon Aug 05 16:45:41 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "MasterServiceSchedule")
@XmlSeeAlso({ObjectFactory.class})
public interface MasterServiceSchedule {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetMasterServiceSchedule", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.EAintegration.clientPackage.MasterServiceSchedule.GetMasterServiceSchedule")
    @WebMethod(operationName = "GetMasterServiceSchedule", action = "GetMasterServiceSchedule")
    @ResponseWrapper(localName = "GetMasterServiceScheduleResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.EAintegration.clientPackage.MasterServiceSchedule.GetMasterServiceScheduleResponse")
    public java.util.List<remote.wise.EAintegration.clientPackage.MasterServiceSchedule.MasterServiceScheduleResponseContract> getMasterServiceSchedule(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.EAintegration.clientPackage.MasterServiceSchedule.MasterServiceScheduleRequestContract reqObj
    ) throws CustomFault;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "setMasterServiceScheduleDetails", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.EAintegration.clientPackage.MasterServiceSchedule.SetMasterServiceScheduleDetails")
    @WebMethod(action = "setMasterServiceScheduleDetails")
    @ResponseWrapper(localName = "setMasterServiceScheduleDetailsResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.EAintegration.clientPackage.MasterServiceSchedule.SetMasterServiceScheduleDetailsResponse")
    public java.lang.String setMasterServiceScheduleDetails(
        @WebParam(name = "servicePlan", targetNamespace = "")
        java.lang.String servicePlan,
        @WebParam(name = "serviceName", targetNamespace = "")
        java.lang.String serviceName,
        @WebParam(name = "scheduleName", targetNamespace = "")
        java.lang.String scheduleName,
        @WebParam(name = "dbmsPartCode", targetNamespace = "")
        java.lang.String dbmsPartCode,
        @WebParam(name = "assetGroupCode", targetNamespace = "")
        java.lang.String assetGroupCode,
        @WebParam(name = "assetTypeCode", targetNamespace = "")
        java.lang.String assetTypeCode,
        @WebParam(name = "engineTypeCode", targetNamespace = "")
        java.lang.String engineTypeCode,
        @WebParam(name = "engineHours", targetNamespace = "")
        java.lang.String engineHours,
        @WebParam(name = "days", targetNamespace = "")
        java.lang.String days,
        @WebParam(name = "messageId", targetNamespace = "")
        java.lang.String messageId,
        @WebParam(name = "fileRef", targetNamespace = "")
        java.lang.String fileRef,
        @WebParam(name = "process", targetNamespace = "")
        java.lang.String process,
        @WebParam(name = "reprocessJobCode", targetNamespace = "")
        java.lang.String reprocessJobCode
    );
}
