<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="AssetPersonalitySampleService" targetNamespace="http://webservices.EAintegration.wise.remote/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://webservices.EAintegration.wise.remote/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
<import namespace="http://webservices.EAintegration.wise.remote/" schemaLocation="AssetPersonalitySampleService_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="processEAassetPersData">
    <wsdl:part name="parameters" element="tns:processEAassetPersData">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="processEAassetPersDataResponse">
    <wsdl:part name="parameters" element="tns:processEAassetPersDataResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="AssetPersonalitySample">
    <wsdl:operation name="processEAassetPersData">
      <wsdl:input name="processEAassetPersData" message="tns:processEAassetPersData">
    </wsdl:input>
      <wsdl:output name="processEAassetPersDataResponse" message="tns:processEAassetPersDataResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="AssetPersonalitySampleServiceSoapBinding" type="tns:AssetPersonalitySample">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="processEAassetPersData">
      <soap:operation soapAction="processEAassetPersData" style="document"/>
      <wsdl:input name="processEAassetPersData">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="processEAassetPersDataResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="AssetPersonalitySampleService">
    <wsdl:port name="AssetPersonalitySamplePort" binding="tns:AssetPersonalitySampleServiceSoapBinding">
      <soap:address location="http://localhost:9090/AssetPersonalitySamplePort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
