<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="RAssetSaleFromD2CSampleService" targetNamespace="http://webservices.EAintegration.wise.remote/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://webservices.EAintegration.wise.remote/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
<import namespace="http://webservices.EAintegration.wise.remote/" schemaLocation="RAssetSaleFromD2CSampleService_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="reprocessEAsaleFromD2CResponse">
    <wsdl:part name="parameters" element="tns:reprocessEAsaleFromD2CResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="reprocessEAsaleFromD2C">
    <wsdl:part name="parameters" element="tns:reprocessEAsaleFromD2C">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="RAssetSaleFromD2CSample">
    <wsdl:operation name="reprocessEAsaleFromD2C">
      <wsdl:input name="reprocessEAsaleFromD2C" message="tns:reprocessEAsaleFromD2C">
    </wsdl:input>
      <wsdl:output name="reprocessEAsaleFromD2CResponse" message="tns:reprocessEAsaleFromD2CResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="RAssetSaleFromD2CSampleServiceSoapBinding" type="tns:RAssetSaleFromD2CSample">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="reprocessEAsaleFromD2C">
      <soap:operation soapAction="reprocessEAsaleFromD2C" style="document"/>
      <wsdl:input name="reprocessEAsaleFromD2C">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="reprocessEAsaleFromD2CResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="RAssetSaleFromD2CSampleService">
    <wsdl:port name="RAssetSaleFromD2CSamplePort" binding="tns:RAssetSaleFromD2CSampleServiceSoapBinding">
      <soap:address location="http://localhost:9090/RAssetSaleFromD2CSamplePort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
