<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="RAssetGateOutSampleService" targetNamespace="http://webservices.EAintegration.wise.remote/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://webservices.EAintegration.wise.remote/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
<import namespace="http://webservices.EAintegration.wise.remote/" schemaLocation="RAssetGateOutSampleService_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="reprocessEAassetGateOut">
    <wsdl:part name="parameters" element="tns:reprocessEAassetGateOut">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="reprocessEAassetGateOutResponse">
    <wsdl:part name="parameters" element="tns:reprocessEAassetGateOutResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="RAssetGateOutSample">
    <wsdl:operation name="reprocessEAassetGateOut">
      <wsdl:input name="reprocessEAassetGateOut" message="tns:reprocessEAassetGateOut">
    </wsdl:input>
      <wsdl:output name="reprocessEAassetGateOutResponse" message="tns:reprocessEAassetGateOutResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="RAssetGateOutSampleServiceSoapBinding" type="tns:RAssetGateOutSample">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="reprocessEAassetGateOut">
      <soap:operation soapAction="reprocessEAassetGateOut" style="document"/>
      <wsdl:input name="reprocessEAassetGateOut">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="reprocessEAassetGateOutResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="RAssetGateOutSampleService">
    <wsdl:port name="RAssetGateOutSamplePort" binding="tns:RAssetGateOutSampleServiceSoapBinding">
      <soap:address location="http://localhost:9090/RAssetGateOutSamplePort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
