package remote.wise.client.AuditLogDetailsService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Mar 12 15:32:28 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "AuditLogDetailsService")
@XmlSeeAlso({ObjectFactory.class})
public interface AuditLogDetailsService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetAuditLogDetails", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.AuditLogDetailsService.GetAuditLogDetails")
    @WebMethod(operationName = "GetAuditLogDetails", action = "GetAuditLogDetails")
    @ResponseWrapper(localName = "GetAuditLogDetailsResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.AuditLogDetailsService.GetAuditLogDetailsResponse")
    public java.util.List<remote.wise.client.AuditLogDetailsService.AuditLogRespContract> getAuditLogDetails(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.AuditLogDetailsService.AuditLogReqContract reqObj
    ) throws CustomFault;
}
