
/*
 * 
 */

package remote.EAscheduler.AssetGateOut;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Fri Jun 19 11:44:03 IST 2015
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "AssetGateOutSampleService", 
                  wsdlLocation = "http://localhost:27000/WISE/AssetGateOutSample?wsdl",
                  targetNamespace = "http://webservices.EAintegration.wise.remote/") 
public class AssetGateOutSampleService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservices.EAintegration.wise.remote/", "AssetGateOutSampleService");
    public final static QName AssetGateOutSamplePort = new QName("http://webservices.EAintegration.wise.remote/", "AssetGateOutSamplePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/AssetGateOutSample?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/AssetGateOutSample?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public AssetGateOutSampleService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AssetGateOutSampleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AssetGateOutSampleService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public AssetGateOutSampleService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public AssetGateOutSampleService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public AssetGateOutSampleService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns AssetGateOutSample
     */
    @WebEndpoint(name = "AssetGateOutSamplePort")
    public AssetGateOutSample getAssetGateOutSamplePort() {
        return super.getPort(AssetGateOutSamplePort, AssetGateOutSample.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AssetGateOutSample
     */
    @WebEndpoint(name = "AssetGateOutSamplePort")
    public AssetGateOutSample getAssetGateOutSamplePort(WebServiceFeature... features) {
        return super.getPort(AssetGateOutSamplePort, AssetGateOutSample.class, features);
    }

}
