package remote.wise.client.UserAlertPreferenceService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Apr 16 13:53:19 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "UserAlertPreferenceService")
@XmlSeeAlso({ObjectFactory.class})
public interface UserAlertPreferenceService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "SetAdminPreference", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.UserAlertPreferenceService.SetAdminPreference")
    @WebMethod(operationName = "SetAdminPreference", action = "SetAdminPreference")
    @ResponseWrapper(localName = "SetAdminPreferenceResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.UserAlertPreferenceService.SetAdminPreferenceResponse")
    public java.lang.String setAdminPreference(
        @WebParam(name = "reqObj", targetNamespace = "")
        java.util.List<remote.wise.client.UserAlertPreferenceService.UserAlertPreferenceRespContract> reqObj
    ) throws CustomFault;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "SetUserAlertPreference", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.UserAlertPreferenceService.SetUserAlertPreference")
    @WebMethod(operationName = "SetUserAlertPreference", action = "SetUserAlertPreference")
    @ResponseWrapper(localName = "SetUserAlertPreferenceResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.UserAlertPreferenceService.SetUserAlertPreferenceResponse")
    public java.lang.String setUserAlertPreference(
        @WebParam(name = "reqObj", targetNamespace = "")
        java.util.List<remote.wise.client.UserAlertPreferenceService.UserAlertPreferenceRespContract> reqObj
    ) throws CustomFault;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetUserAlertPreference", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.UserAlertPreferenceService.GetUserAlertPreference")
    @WebMethod(operationName = "GetUserAlertPreference", action = "GetUserAlertPreference")
    @ResponseWrapper(localName = "GetUserAlertPreferenceResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.UserAlertPreferenceService.GetUserAlertPreferenceResponse")
    public java.util.List<remote.wise.client.UserAlertPreferenceService.UserAlertPreferenceRespContract> getUserAlertPreference(
        @WebParam(name = "arg0", targetNamespace = "")
        remote.wise.client.UserAlertPreferenceService.UserAlertPreferenceReqContract arg0
    ) throws CustomFault;
}
