
/*
 * 
 */

package remote.wise.EAintegration.clientPackage.AssetProfileService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Jul 23 15:15:11 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "AssetProfileServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/AssetProfileService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class AssetProfileServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "AssetProfileServiceService");
    public final static QName AssetProfileServicePort = new QName("http://webservice.service.wise.remote/", "AssetProfileServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/AssetProfileService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/AssetProfileService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public AssetProfileServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AssetProfileServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AssetProfileServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public AssetProfileServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public AssetProfileServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public AssetProfileServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns AssetProfileService
     */
    @WebEndpoint(name = "AssetProfileServicePort")
    public AssetProfileService getAssetProfileServicePort() {
        return super.getPort(AssetProfileServicePort, AssetProfileService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AssetProfileService
     */
    @WebEndpoint(name = "AssetProfileServicePort")
    public AssetProfileService getAssetProfileServicePort(WebServiceFeature... features) {
        return super.getPort(AssetProfileServicePort, AssetProfileService.class, features);
    }

}
