package remote.wise.EAintegration.clientPackage.AssetProfileService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Jul 23 15:15:11 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "AssetProfileService")
@XmlSeeAlso({ObjectFactory.class})
public interface AssetProfileService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "setAssetProfileDetails", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.EAintegration.clientPackage.AssetProfileService.SetAssetProfileDetails")
    @WebMethod(action = "setAssetProfileDetails")
    @ResponseWrapper(localName = "setAssetProfileDetailsResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.EAintegration.clientPackage.AssetProfileService.SetAssetProfileDetailsResponse")
    public java.lang.String setAssetProfileDetails(
        @WebParam(name = "assetGroupName", targetNamespace = "")
        java.lang.String assetGroupName,
        @WebParam(name = "assetGroupCode", targetNamespace = "")
        java.lang.String assetGroupCode,
        @WebParam(name = "messageId", targetNamespace = "")
        java.lang.String messageId,
        @WebParam(name = "fileRef", targetNamespace = "")
        java.lang.String fileRef,
        @WebParam(name = "process", targetNamespace = "")
        java.lang.String process,
        @WebParam(name = "reprocessJobCode", targetNamespace = "")
        java.lang.String reprocessJobCode
    );
}
