package remote.wise.EAintegration.clientPackage.AssetTypeService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Jul 23 15:16:52 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "AssetTypeService")
@XmlSeeAlso({ObjectFactory.class})
public interface AssetTypeService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "setAssetTypeDetails", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.EAintegration.clientPackage.AssetTypeService.SetAssetTypeDetails")
    @WebMethod(action = "setAssetTypeDetails")
    @ResponseWrapper(localName = "setAssetTypeDetailsResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.EAintegration.clientPackage.AssetTypeService.SetAssetTypeDetailsResponse")
    public java.lang.String setAssetTypeDetails(
        @WebParam(name = "assetTypeName", targetNamespace = "")
        java.lang.String assetTypeName,
        @WebParam(name = "assetTypeCode", targetNamespace = "")
        java.lang.String assetTypeCode,
        @WebParam(name = "messageId", targetNamespace = "")
        java.lang.String messageId,
        @WebParam(name = "fileRef", targetNamespace = "")
        java.lang.String fileRef,
        @WebParam(name = "process", targetNamespace = "")
        java.lang.String process,
        @WebParam(name = "reprocessJobCode", targetNamespace = "")
        java.lang.String reprocessJobCode
    );
}
