
/*
 * 
 */

package remote.wise.EAintegration.clientPackage.AssetInstallationDetails;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Mon Aug 19 11:59:03 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "InstallationDateDetailsServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/InstallationDateDetailsService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class InstallationDateDetailsServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "InstallationDateDetailsServiceService");
    public final static QName InstallationDateDetailsServicePort = new QName("http://webservice.service.wise.remote/", "InstallationDateDetailsServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/InstallationDateDetailsService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/InstallationDateDetailsService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public InstallationDateDetailsServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InstallationDateDetailsServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InstallationDateDetailsServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public InstallationDateDetailsServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public InstallationDateDetailsServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public InstallationDateDetailsServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns InstallationDateDetailsService
     */
    @WebEndpoint(name = "InstallationDateDetailsServicePort")
    public InstallationDateDetailsService getInstallationDateDetailsServicePort() {
        return super.getPort(InstallationDateDetailsServicePort, InstallationDateDetailsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InstallationDateDetailsService
     */
    @WebEndpoint(name = "InstallationDateDetailsServicePort")
    public InstallationDateDetailsService getInstallationDateDetailsServicePort(WebServiceFeature... features) {
        return super.getPort(InstallationDateDetailsServicePort, InstallationDateDetailsService.class, features);
    }

}
