package remote.wise.client.GetForgotLoginIDService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Thu Apr 18 11:20:57 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "GetForgotLoginIDService")
@XmlSeeAlso({ObjectFactory.class})
public interface GetForgotLoginIDService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "AuthenicateLoginIDOrMobileNo", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.GetForgotLoginIDService.AuthenicateLoginIDOrMobileNo")
    @WebMethod(operationName = "AuthenicateLoginIDOrMobileNo", action = "AuthenicateLoginIDOrMobileNo")
    @ResponseWrapper(localName = "AuthenicateLoginIDOrMobileNoResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.GetForgotLoginIDService.AuthenicateLoginIDOrMobileNoResponse")
    public java.lang.String authenicateLoginIDOrMobileNo(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.GetForgotLoginIDService.ForgotLoginIDReqContract reqObj
    ) throws CustomFault;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetForgotLoginIDService", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.GetForgotLoginIDService.GetForgotLoginIDService_Type")
    @WebMethod(operationName = "GetForgotLoginIDService", action = "GetForgotLoginIDService")
    @ResponseWrapper(localName = "GetForgotLoginIDServiceResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.GetForgotLoginIDService.GetForgotLoginIDServiceResponse")
    public remote.wise.client.GetForgotLoginIDService.ForgotLoginIDRespContract getForgotLoginIDService(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.GetForgotLoginIDService.ForgotLoginIDReqContract reqObj
    ) throws CustomFault;
}
