package remote.wise.client.AssetServiceScheduleService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Fri Aug 23 16:51:49 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "AssetServiceScheduleService")
@XmlSeeAlso({ObjectFactory.class})
public interface AssetServiceScheduleService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetAssetServiceScheduleService", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.AssetServiceScheduleService.GetAssetServiceScheduleService")
    @WebMethod(operationName = "GetAssetServiceScheduleService", action = "GetAssetServiceScheduleService")
    @ResponseWrapper(localName = "GetAssetServiceScheduleServiceResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.AssetServiceScheduleService.GetAssetServiceScheduleServiceResponse")
    public java.util.List<remote.wise.client.AssetServiceScheduleService.AssetServiceScheduleGetRespContract> getAssetServiceScheduleService(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.AssetServiceScheduleService.AssetServiceScheduleGetReqContract reqObj
    ) throws CustomFault;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "SetAssetServiceScheduleService", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.AssetServiceScheduleService.SetAssetServiceScheduleService")
    @WebMethod(operationName = "SetAssetServiceScheduleService", action = "SetAssetServiceScheduleService")
    @ResponseWrapper(localName = "SetAssetServiceScheduleServiceResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.AssetServiceScheduleService.SetAssetServiceScheduleServiceResponse")
    public java.lang.String setAssetServiceScheduleService(
        @WebParam(name = "setAssetServiceSchedule", targetNamespace = "")
        remote.wise.client.AssetServiceScheduleService.AssetServiceScheduleRespContract setAssetServiceSchedule
    ) throws CustomFault;
}
