
/*
 * 
 */

package remote.wise.client.AssetServiceScheduleService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Fri Aug 23 16:51:49 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "AssetServiceScheduleServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/AssetServiceScheduleService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class AssetServiceScheduleServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "AssetServiceScheduleServiceService");
    public final static QName AssetServiceScheduleServicePort = new QName("http://webservice.service.wise.remote/", "AssetServiceScheduleServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/AssetServiceScheduleService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/AssetServiceScheduleService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public AssetServiceScheduleServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AssetServiceScheduleServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AssetServiceScheduleServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public AssetServiceScheduleServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public AssetServiceScheduleServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public AssetServiceScheduleServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns AssetServiceScheduleService
     */
    @WebEndpoint(name = "AssetServiceScheduleServicePort")
    public AssetServiceScheduleService getAssetServiceScheduleServicePort() {
        return super.getPort(AssetServiceScheduleServicePort, AssetServiceScheduleService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AssetServiceScheduleService
     */
    @WebEndpoint(name = "AssetServiceScheduleServicePort")
    public AssetServiceScheduleService getAssetServiceScheduleServicePort(WebServiceFeature... features) {
        return super.getPort(AssetServiceScheduleServicePort, AssetServiceScheduleService.class, features);
    }

}
