
/*
 * 
 */

package remote.wise.EAintegration.clientPackage.EngineTypeService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Jul 23 15:17:47 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "EngineTypeServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/EngineTypeService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class EngineTypeServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "EngineTypeServiceService");
    public final static QName EngineTypeServicePort = new QName("http://webservice.service.wise.remote/", "EngineTypeServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/EngineTypeService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/EngineTypeService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public EngineTypeServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EngineTypeServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EngineTypeServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public EngineTypeServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public EngineTypeServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public EngineTypeServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns EngineTypeService
     */
    @WebEndpoint(name = "EngineTypeServicePort")
    public EngineTypeService getEngineTypeServicePort() {
        return super.getPort(EngineTypeServicePort, EngineTypeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EngineTypeService
     */
    @WebEndpoint(name = "EngineTypeServicePort")
    public EngineTypeService getEngineTypeServicePort(WebServiceFeature... features) {
        return super.getPort(EngineTypeServicePort, EngineTypeService.class, features);
    }

}
