
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Mar 19 13:36:04 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "ClearAlertsAfter24Hours", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClearAlertsAfter24Hours", namespace = "http://webservice.service.wise.remote/")

public class ClearAlertsAfter24Hours {


}

