
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Fri Aug 23 16:50:15 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "GetAssetServiceScheduleService", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetAssetServiceScheduleService", namespace = "http://webservice.service.wise.remote/")

public class GetAssetServiceScheduleService {

    @XmlElement(name = "reqObj")
    private remote.wise.service.datacontract.AssetServiceScheduleGetReqContract reqObj;

    public remote.wise.service.datacontract.AssetServiceScheduleGetReqContract getReqObj() {
        return this.reqObj;
    }

    public void setReqObj(remote.wise.service.datacontract.AssetServiceScheduleGetReqContract newReqObj)  {
        this.reqObj = newReqObj;
    }

}

