
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Jan 23 14:07:08 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "GetAlertDetailsResponse", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetAlertDetailsResponse", namespace = "http://webservice.service.wise.remote/")

public class GetAlertDetailsResponse {

    @XmlElement(name = "return")
    private remote.wise.service.datacontract.AlertDetailsRespContract _return;

    public remote.wise.service.datacontract.AlertDetailsRespContract getReturn() {
        return this._return;
    }

    public void setReturn(remote.wise.service.datacontract.AlertDetailsRespContract new_return)  {
        this._return = new_return;
    }

}

