
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Mon Dec 08 12:13:54 IST 2014
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "GetAssetDashboardDetailsResponse", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetAssetDashboardDetailsResponse", namespace = "http://webservice.service.wise.remote/")

public class GetAssetDashboardDetailsResponse {

    @XmlElement(name = "return")
    private java.util.List<remote.wise.service.datacontract.AssetDashboardRespContract> _return;

    public java.util.List<remote.wise.service.datacontract.AssetDashboardRespContract> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<remote.wise.service.datacontract.AssetDashboardRespContract> new_return)  {
        this._return = new_return;
    }

}

