
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Fri Mar 22 09:20:49 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "GetCustomersForDealer", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetCustomersForDealer", namespace = "http://webservice.service.wise.remote/")

public class GetCustomersForDealer {

    @XmlElement(name = "reqObj")
    private remote.wise.service.datacontract.CustomerForDealerReqContract reqObj;

    public remote.wise.service.datacontract.CustomerForDealerReqContract getReqObj() {
        return this.reqObj;
    }

    public void setReqObj(remote.wise.service.datacontract.CustomerForDealerReqContract newReqObj)  {
        this.reqObj = newReqObj;
    }

}

