
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Aug 13 17:35:57 IST 2014
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "GetEADetailData", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetEADetailData", namespace = "http://webservice.service.wise.remote/")

public class GetEADetailData {

    @XmlElement(name = "reqObj")
    private remote.wise.service.datacontract.EAInterfaceDetailReqContract reqObj;

    public remote.wise.service.datacontract.EAInterfaceDetailReqContract getReqObj() {
        return this.reqObj;
    }

    public void setReqObj(remote.wise.service.datacontract.EAInterfaceDetailReqContract newReqObj)  {
        this.reqObj = newReqObj;
    }

}

