
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Apr 03 16:25:33 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "GetFleetSummaryReportService", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetFleetSummaryReportService", namespace = "http://webservice.service.wise.remote/")

public class GetFleetSummaryReportService {

    @XmlElement(name = "reqObj")
    private remote.wise.service.datacontract.FleetSummaryReportReqContract reqObj;

    public remote.wise.service.datacontract.FleetSummaryReportReqContract getReqObj() {
        return this.reqObj;
    }

    public void setReqObj(remote.wise.service.datacontract.FleetSummaryReportReqContract newReqObj)  {
        this.reqObj = newReqObj;
    }

}

