
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Mon Apr 15 11:33:33 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "GetLandmarkDetails", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetLandmarkDetails", namespace = "http://webservice.service.wise.remote/")

public class GetLandmarkDetails {

    @XmlElement(name = "ReqObj")
    private remote.wise.service.datacontract.LandmarkDetailsReqContract ReqObj;

    public remote.wise.service.datacontract.LandmarkDetailsReqContract getReqObj() {
        return this.ReqObj;
    }

    public void setReqObj(remote.wise.service.datacontract.LandmarkDetailsReqContract newReqObj)  {
        this.ReqObj = newReqObj;
    }

}

