
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Fri Mar 08 17:32:03 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "GetLandmarkAsset", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetLandmarkAsset", namespace = "http://webservice.service.wise.remote/")

public class GetLandmarkAsset {

    @XmlElement(name = "arg0")
    private remote.wise.service.datacontract.LandmarkAssetReqContract arg0;

    public remote.wise.service.datacontract.LandmarkAssetReqContract getArg0() {
        return this.arg0;
    }

    public void setArg0(remote.wise.service.datacontract.LandmarkAssetReqContract newArg0)  {
        this.arg0 = newArg0;
    }

}

