
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Mar 06 16:42:06 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "GetLandmarkCategoryResponse", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetLandmarkCategoryResponse", namespace = "http://webservice.service.wise.remote/")

public class GetLandmarkCategoryResponse {

    @XmlElement(name = "return")
    private java.util.List<remote.wise.service.datacontract.LandmarkCategoryRespContract> _return;

    public java.util.List<remote.wise.service.datacontract.LandmarkCategoryRespContract> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<remote.wise.service.datacontract.LandmarkCategoryRespContract> new_return)  {
        this._return = new_return;
    }

}

