
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Thu Mar 28 11:10:30 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "GetModelMapResponse", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetModelMapResponse", namespace = "http://webservice.service.wise.remote/")

public class GetModelMapResponse {

    @XmlElement(name = "return")
    private remote.wise.service.datacontract.ModelResponseContract _return;

    public remote.wise.service.datacontract.ModelResponseContract getReturn() {
        return this._return;
    }

    public void setReturn(remote.wise.service.datacontract.ModelResponseContract new_return)  {
        this._return = new_return;
    }

}

