
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Apr 16 17:45:23 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "GetMap", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetMap", namespace = "http://webservice.service.wise.remote/")

public class GetMap {

    @XmlElement(name = "ReqObj")
    private remote.wise.service.datacontract.MapReqContract ReqObj;

    public remote.wise.service.datacontract.MapReqContract getReqObj() {
        return this.ReqObj;
    }

    public void setReqObj(remote.wise.service.datacontract.MapReqContract newReqObj)  {
        this.ReqObj = newReqObj;
    }

}

