
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Fri Aug 23 16:36:10 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "GetMachineHoursServiceReportService", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetMachineHoursServiceReportService", namespace = "http://webservice.service.wise.remote/")

public class GetMachineHoursServiceReportService {

    @XmlElement(name = "reqObj")
    private remote.wise.service.datacontract.MachineHoursServiceReportReqContract reqObj;

    public remote.wise.service.datacontract.MachineHoursServiceReportReqContract getReqObj() {
        return this.reqObj;
    }

    public void setReqObj(remote.wise.service.datacontract.MachineHoursServiceReportReqContract newReqObj)  {
        this.reqObj = newReqObj;
    }

}

