
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Feb 12 12:11:15 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "getMGLandMarkDetails", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getMGLandMarkDetails", namespace = "http://webservice.service.wise.remote/")

public class GetMGLandMarkDetails {

    @XmlElement(name = "reqObj")
    private remote.wise.service.datacontract.MGLandMarkReqContract reqObj;

    public remote.wise.service.datacontract.MGLandMarkReqContract getReqObj() {
        return this.reqObj;
    }

    public void setReqObj(remote.wise.service.datacontract.MGLandMarkReqContract newReqObj)  {
        this.reqObj = newReqObj;
    }

}

