
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Oct 09 14:53:11 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "getMachineHourMeterTrendDataResponse", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getMachineHourMeterTrendDataResponse", namespace = "http://webservice.service.wise.remote/")

public class GetMachineHourMeterTrendDataResponse {

    @XmlElement(name = "return")
    private java.util.List<remote.wise.service.datacontract.MachineHourMeterTrendDataReportRespContract> _return;

    public java.util.List<remote.wise.service.datacontract.MachineHourMeterTrendDataReportRespContract> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<remote.wise.service.datacontract.MachineHourMeterTrendDataReportRespContract> new_return)  {
        this._return = new_return;
    }

}

