
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Thu Mar 14 14:52:41 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "GetQuestionsToUser", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetQuestionsToUser", namespace = "http://webservice.service.wise.remote/")

public class GetQuestionsToUser {

    @XmlElement(name = "contactId")
    private java.lang.String contactId;

    public java.lang.String getContactId() {
        return this.contactId;
    }

    public void setContactId(java.lang.String newContactId)  {
        this.contactId = newContactId;
    }

}

