
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Thu Mar 21 15:19:23 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "GetReportMasterListServiceResponse", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetReportMasterListServiceResponse", namespace = "http://webservice.service.wise.remote/")

public class GetReportMasterListServiceResponse {

    @XmlElement(name = "return")
    private java.util.List<remote.wise.service.datacontract.ReportMasterListRespContract> _return;

    public java.util.List<remote.wise.service.datacontract.ReportMasterListRespContract> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<remote.wise.service.datacontract.ReportMasterListRespContract> new_return)  {
        this._return = new_return;
    }

}

