
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Thu Dec 04 16:37:59 IST 2014
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "getSMSAlerts", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getSMSAlerts", namespace = "http://webservice.service.wise.remote/")

public class GetSMSAlerts {

    @XmlElement(name = "reqObj")
    private remote.wise.service.datacontract.SMSAlertsReqContract reqObj;

    public remote.wise.service.datacontract.SMSAlertsReqContract getReqObj() {
        return this.reqObj;
    }

    public void setReqObj(remote.wise.service.datacontract.SMSAlertsReqContract newReqObj)  {
        this.reqObj = newReqObj;
    }

}

