
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Mon Mar 25 09:48:21 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "GetTenancyDetails", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetTenancyDetails", namespace = "http://webservice.service.wise.remote/")

public class GetTenancyDetails {

    @XmlElement(name = "reqObj")
    private remote.wise.service.datacontract.TenancyDetailsReqContract reqObj;

    public remote.wise.service.datacontract.TenancyDetailsReqContract getReqObj() {
        return this.reqObj;
    }

    public void setReqObj(remote.wise.service.datacontract.TenancyDetailsReqContract newReqObj)  {
        this.reqObj = newReqObj;
    }

}

