
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Jan 22 14:29:36 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "GetUserAssetDetails", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetUserAssetDetails", namespace = "http://webservice.service.wise.remote/")

public class GetUserAssetDetails {

    @XmlElement(name = "reqObj")
    private remote.wise.service.datacontract.UserAssetDetailsReqContract reqObj;

    public remote.wise.service.datacontract.UserAssetDetailsReqContract getReqObj() {
        return this.reqObj;
    }

    public void setReqObj(remote.wise.service.datacontract.UserAssetDetailsReqContract newReqObj)  {
        this.reqObj = newReqObj;
    }

}

