
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Jan 29 22:17:03 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "GetUnderUtilizedMachines", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetUnderUtilizedMachines", namespace = "http://webservice.service.wise.remote/")

public class GetUnderUtilizedMachines {

    @XmlElement(name = "reqObj")
    private remote.wise.service.datacontract.UnderUtilizedMachinesReqContract reqObj;

    public remote.wise.service.datacontract.UnderUtilizedMachinesReqContract getReqObj() {
        return this.reqObj;
    }

    public void setReqObj(remote.wise.service.datacontract.UnderUtilizedMachinesReqContract newReqObj)  {
        this.reqObj = newReqObj;
    }

}

