
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Thu Aug 29 15:14:09 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "GetUserDetails", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetUserDetails", namespace = "http://webservice.service.wise.remote/")

public class GetUserDetails {

    @XmlElement(name = "userReqContract")
    private remote.wise.service.datacontract.UserDetailsReqContract userReqContract;

    public remote.wise.service.datacontract.UserDetailsReqContract getUserReqContract() {
        return this.userReqContract;
    }

    public void setUserReqContract(remote.wise.service.datacontract.UserDetailsReqContract newUserReqContract)  {
        this.userReqContract = newUserReqContract;
    }

}

