
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue May 19 16:42:53 IST 2015
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "monitorWiseStatus", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "monitorWiseStatus", namespace = "http://webservice.service.wise.remote/")

public class MonitorWiseStatus {


}

