
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Apr 17 12:39:36 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "NotificationSummary", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NotificationSummary", namespace = "http://webservice.service.wise.remote/", propOrder = {"LoginId", "Period", "TenancyIdList", "MachineGroupIdList", "MachineProfileIdList", "IsmachineGroup", "ModelidList", "machineProfile", "model"})

public class NotificationSummary {

    @XmlElement(name = "LoginId")
    private java.lang.String LoginId;
    @XmlElement(name = "Period")
    private java.lang.String Period;
    @XmlElement(name = "TenancyIdList")
    private java.util.List<java.lang.Integer> TenancyIdList;
    @XmlElement(name = "MachineGroupIdList")
    private java.util.List<java.lang.Integer> MachineGroupIdList;
    @XmlElement(name = "MachineProfileIdList")
    private java.util.List<java.lang.Integer> MachineProfileIdList;
    @XmlElement(name = "IsmachineGroup")
    private boolean IsmachineGroup;
    @XmlElement(name = "ModelidList")
    private java.util.List<java.lang.Integer> ModelidList;
    @XmlElement(name = "machineProfile")
    private boolean machineProfile;
    @XmlElement(name = "model")
    private boolean model;

    public java.lang.String getLoginId() {
        return this.LoginId;
    }

    public void setLoginId(java.lang.String newLoginId)  {
        this.LoginId = newLoginId;
    }

    public java.lang.String getPeriod() {
        return this.Period;
    }

    public void setPeriod(java.lang.String newPeriod)  {
        this.Period = newPeriod;
    }

    public java.util.List<java.lang.Integer> getTenancyIdList() {
        return this.TenancyIdList;
    }

    public void setTenancyIdList(java.util.List<java.lang.Integer> newTenancyIdList)  {
        this.TenancyIdList = newTenancyIdList;
    }

    public java.util.List<java.lang.Integer> getMachineGroupIdList() {
        return this.MachineGroupIdList;
    }

    public void setMachineGroupIdList(java.util.List<java.lang.Integer> newMachineGroupIdList)  {
        this.MachineGroupIdList = newMachineGroupIdList;
    }

    public java.util.List<java.lang.Integer> getMachineProfileIdList() {
        return this.MachineProfileIdList;
    }

    public void setMachineProfileIdList(java.util.List<java.lang.Integer> newMachineProfileIdList)  {
        this.MachineProfileIdList = newMachineProfileIdList;
    }

    public boolean getIsmachineGroup() {
        return this.IsmachineGroup;
    }

    public void setIsmachineGroup(boolean newIsmachineGroup)  {
        this.IsmachineGroup = newIsmachineGroup;
    }

    public java.util.List<java.lang.Integer> getModelidList() {
        return this.ModelidList;
    }

    public void setModelidList(java.util.List<java.lang.Integer> newModelidList)  {
        this.ModelidList = newModelidList;
    }

    public boolean getMachineProfile() {
        return this.machineProfile;
    }

    public void setMachineProfile(boolean newMachineProfile)  {
        this.machineProfile = newMachineProfile;
    }

    public boolean getModel() {
        return this.model;
    }

    public void setModel(boolean newModel)  {
        this.model = newModel;
    }

}

