
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Jan 30 12:31:08 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "ParseXSD", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ParseXSD", namespace = "http://webservice.service.wise.remote/")

public class ParseXSD {

    @XmlElement(name = "confirmParsing")
    private boolean confirmParsing;

    public boolean getConfirmParsing() {
        return this.confirmParsing;
    }

    public void setConfirmParsing(boolean newConfirmParsing)  {
        this.confirmParsing = newConfirmParsing;
    }

}

