
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Feb 18 09:23:56 IST 2014
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "processDataPackets", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "processDataPackets", namespace = "http://webservice.service.wise.remote/")

public class ProcessDataPackets {

    @XmlElement(name = "msg")
    private java.lang.String msg;

    public java.lang.String getMsg() {
        return this.msg;
    }

    public void setMsg(java.lang.String newMsg)  {
        this.msg = newMsg;
    }

}

