
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Jan 29 16:37:41 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "SetAlertThreshold", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SetAlertThreshold", namespace = "http://webservice.service.wise.remote/")

public class SetAlertThreshold {

    @XmlElement(name = "reqObj")
    private java.util.List<remote.wise.service.datacontract.AlertThresholdRespContract> reqObj;

    public java.util.List<remote.wise.service.datacontract.AlertThresholdRespContract> getReqObj() {
        return this.reqObj;
    }

    public void setReqObj(java.util.List<remote.wise.service.datacontract.AlertThresholdRespContract> newReqObj)  {
        this.reqObj = newReqObj;
    }

}

