
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Apr 02 15:55:57 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "SetAssetServiceScheduleService", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SetAssetServiceScheduleService", namespace = "http://webservice.service.wise.remote/")

public class SetAssetServiceScheduleService {

    @XmlElement(name = "setAssetServiceSchedule")
    private remote.wise.service.datacontract.AssetServiceScheduleRespContract setAssetServiceSchedule;

    public remote.wise.service.datacontract.AssetServiceScheduleRespContract getSetAssetServiceSchedule() {
        return this.setAssetServiceSchedule;
    }

    public void setSetAssetServiceSchedule(remote.wise.service.datacontract.AssetServiceScheduleRespContract newSetAssetServiceSchedule)  {
        this.setAssetServiceSchedule = newSetAssetServiceSchedule;
    }

}

