
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Thu Aug 29 17:33:55 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "setAssetTypeDetails", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "setAssetTypeDetails", namespace = "http://webservice.service.wise.remote/", propOrder = {"assetTypeName", "assetTypeCode", "messageId", "fileRef", "process", "reprocessJobCode"})

public class SetAssetTypeDetails {

    @XmlElement(name = "assetTypeName")
    private java.lang.String assetTypeName;
    @XmlElement(name = "assetTypeCode")
    private java.lang.String assetTypeCode;
    @XmlElement(name = "messageId")
    private java.lang.String messageId;
    @XmlElement(name = "fileRef")
    private java.lang.String fileRef;
    @XmlElement(name = "process")
    private java.lang.String process;
    @XmlElement(name = "reprocessJobCode")
    private java.lang.String reprocessJobCode;

    public java.lang.String getAssetTypeName() {
        return this.assetTypeName;
    }

    public void setAssetTypeName(java.lang.String newAssetTypeName)  {
        this.assetTypeName = newAssetTypeName;
    }

    public java.lang.String getAssetTypeCode() {
        return this.assetTypeCode;
    }

    public void setAssetTypeCode(java.lang.String newAssetTypeCode)  {
        this.assetTypeCode = newAssetTypeCode;
    }

    public java.lang.String getMessageId() {
        return this.messageId;
    }

    public void setMessageId(java.lang.String newMessageId)  {
        this.messageId = newMessageId;
    }

    public java.lang.String getFileRef() {
        return this.fileRef;
    }

    public void setFileRef(java.lang.String newFileRef)  {
        this.fileRef = newFileRef;
    }

    public java.lang.String getProcess() {
        return this.process;
    }

    public void setProcess(java.lang.String newProcess)  {
        this.process = newProcess;
    }

    public java.lang.String getReprocessJobCode() {
        return this.reprocessJobCode;
    }

    public void setReprocessJobCode(java.lang.String newReprocessJobCode)  {
        this.reprocessJobCode = newReprocessJobCode;
    }

}

