
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Thu Aug 29 18:08:23 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "setAssetServiceSchedule", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "setAssetServiceSchedule", namespace = "http://webservice.service.wise.remote/", propOrder = {"serialNumber", "installationDate", "dealerCode", "customerCode", "messageId", "fileRef", "process", "reprocessJobCode"})

public class SetAssetServiceSchedule {

    @XmlElement(name = "serialNumber")
    private java.lang.String serialNumber;
    @XmlElement(name = "installationDate")
    private java.lang.String installationDate;
    @XmlElement(name = "dealerCode")
    private java.lang.String dealerCode;
    @XmlElement(name = "customerCode")
    private java.lang.String customerCode;
    @XmlElement(name = "messageId")
    private java.lang.String messageId;
    @XmlElement(name = "fileRef")
    private java.lang.String fileRef;
    @XmlElement(name = "process")
    private java.lang.String process;
    @XmlElement(name = "reprocessJobCode")
    private java.lang.String reprocessJobCode;

    public java.lang.String getSerialNumber() {
        return this.serialNumber;
    }

    public void setSerialNumber(java.lang.String newSerialNumber)  {
        this.serialNumber = newSerialNumber;
    }

    public java.lang.String getInstallationDate() {
        return this.installationDate;
    }

    public void setInstallationDate(java.lang.String newInstallationDate)  {
        this.installationDate = newInstallationDate;
    }

    public java.lang.String getDealerCode() {
        return this.dealerCode;
    }

    public void setDealerCode(java.lang.String newDealerCode)  {
        this.dealerCode = newDealerCode;
    }

    public java.lang.String getCustomerCode() {
        return this.customerCode;
    }

    public void setCustomerCode(java.lang.String newCustomerCode)  {
        this.customerCode = newCustomerCode;
    }

    public java.lang.String getMessageId() {
        return this.messageId;
    }

    public void setMessageId(java.lang.String newMessageId)  {
        this.messageId = newMessageId;
    }

    public java.lang.String getFileRef() {
        return this.fileRef;
    }

    public void setFileRef(java.lang.String newFileRef)  {
        this.fileRef = newFileRef;
    }

    public java.lang.String getProcess() {
        return this.process;
    }

    public void setProcess(java.lang.String newProcess)  {
        this.process = newProcess;
    }

    public java.lang.String getReprocessJobCode() {
        return this.reprocessJobCode;
    }

    public void setReprocessJobCode(java.lang.String newReprocessJobCode)  {
        this.reprocessJobCode = newReprocessJobCode;
    }

}

