
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Thu Aug 29 17:36:42 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "SetAssetPersonalityDetails", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SetAssetPersonalityDetails", namespace = "http://webservice.service.wise.remote/", propOrder = {"engineNumber", "assetGroupCode", "assetTypeCode", "engineTypeCode", "assetBuiltDate", "make", "fuelCapacity", "serialNumber", "messageId", "fileRef", "process", "reprocessJobCode"})

public class SetAssetPersonalityDetails {

    @XmlElement(name = "engineNumber")
    private java.lang.String engineNumber;
    @XmlElement(name = "assetGroupCode")
    private java.lang.String assetGroupCode;
    @XmlElement(name = "assetTypeCode")
    private java.lang.String assetTypeCode;
    @XmlElement(name = "engineTypeCode")
    private java.lang.String engineTypeCode;
    @XmlElement(name = "assetBuiltDate")
    private java.lang.String assetBuiltDate;
    @XmlElement(name = "make")
    private java.lang.String make;
    @XmlElement(name = "fuelCapacity")
    private java.lang.String fuelCapacity;
    @XmlElement(name = "serialNumber")
    private java.lang.String serialNumber;
    @XmlElement(name = "messageId")
    private java.lang.String messageId;
    @XmlElement(name = "fileRef")
    private java.lang.String fileRef;
    @XmlElement(name = "process")
    private java.lang.String process;
    @XmlElement(name = "reprocessJobCode")
    private java.lang.String reprocessJobCode;

    public java.lang.String getEngineNumber() {
        return this.engineNumber;
    }

    public void setEngineNumber(java.lang.String newEngineNumber)  {
        this.engineNumber = newEngineNumber;
    }

    public java.lang.String getAssetGroupCode() {
        return this.assetGroupCode;
    }

    public void setAssetGroupCode(java.lang.String newAssetGroupCode)  {
        this.assetGroupCode = newAssetGroupCode;
    }

    public java.lang.String getAssetTypeCode() {
        return this.assetTypeCode;
    }

    public void setAssetTypeCode(java.lang.String newAssetTypeCode)  {
        this.assetTypeCode = newAssetTypeCode;
    }

    public java.lang.String getEngineTypeCode() {
        return this.engineTypeCode;
    }

    public void setEngineTypeCode(java.lang.String newEngineTypeCode)  {
        this.engineTypeCode = newEngineTypeCode;
    }

    public java.lang.String getAssetBuiltDate() {
        return this.assetBuiltDate;
    }

    public void setAssetBuiltDate(java.lang.String newAssetBuiltDate)  {
        this.assetBuiltDate = newAssetBuiltDate;
    }

    public java.lang.String getMake() {
        return this.make;
    }

    public void setMake(java.lang.String newMake)  {
        this.make = newMake;
    }

    public java.lang.String getFuelCapacity() {
        return this.fuelCapacity;
    }

    public void setFuelCapacity(java.lang.String newFuelCapacity)  {
        this.fuelCapacity = newFuelCapacity;
    }

    public java.lang.String getSerialNumber() {
        return this.serialNumber;
    }

    public void setSerialNumber(java.lang.String newSerialNumber)  {
        this.serialNumber = newSerialNumber;
    }

    public java.lang.String getMessageId() {
        return this.messageId;
    }

    public void setMessageId(java.lang.String newMessageId)  {
        this.messageId = newMessageId;
    }

    public java.lang.String getFileRef() {
        return this.fileRef;
    }

    public void setFileRef(java.lang.String newFileRef)  {
        this.fileRef = newFileRef;
    }

    public java.lang.String getProcess() {
        return this.process;
    }

    public void setProcess(java.lang.String newProcess)  {
        this.process = newProcess;
    }

    public java.lang.String getReprocessJobCode() {
        return this.reprocessJobCode;
    }

    public void setReprocessJobCode(java.lang.String newReprocessJobCode)  {
        this.reprocessJobCode = newReprocessJobCode;
    }

}

