
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Thu Jan 24 10:17:24 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "SetCustomAssetGroup", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SetCustomAssetGroup", namespace = "http://webservice.service.wise.remote/")

public class SetCustomAssetGroup {

    @XmlElement(name = "reqObj")
    private remote.wise.service.datacontract.AssetGroupRespContract reqObj;

    public remote.wise.service.datacontract.AssetGroupRespContract getReqObj() {
        return this.reqObj;
    }

    public void setReqObj(remote.wise.service.datacontract.AssetGroupRespContract newReqObj)  {
        this.reqObj = newReqObj;
    }

}

