
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Thu Aug 29 17:35:33 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "setEngineTypeDetails", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "setEngineTypeDetails", namespace = "http://webservice.service.wise.remote/", propOrder = {"engineTypeName", "engineTypeCode", "messageId", "fileRef", "process", "reprocessJobCode"})

public class SetEngineTypeDetails {

    @XmlElement(name = "engineTypeName")
    private java.lang.String engineTypeName;
    @XmlElement(name = "engineTypeCode")
    private java.lang.String engineTypeCode;
    @XmlElement(name = "messageId")
    private java.lang.String messageId;
    @XmlElement(name = "fileRef")
    private java.lang.String fileRef;
    @XmlElement(name = "process")
    private java.lang.String process;
    @XmlElement(name = "reprocessJobCode")
    private java.lang.String reprocessJobCode;

    public java.lang.String getEngineTypeName() {
        return this.engineTypeName;
    }

    public void setEngineTypeName(java.lang.String newEngineTypeName)  {
        this.engineTypeName = newEngineTypeName;
    }

    public java.lang.String getEngineTypeCode() {
        return this.engineTypeCode;
    }

    public void setEngineTypeCode(java.lang.String newEngineTypeCode)  {
        this.engineTypeCode = newEngineTypeCode;
    }

    public java.lang.String getMessageId() {
        return this.messageId;
    }

    public void setMessageId(java.lang.String newMessageId)  {
        this.messageId = newMessageId;
    }

    public java.lang.String getFileRef() {
        return this.fileRef;
    }

    public void setFileRef(java.lang.String newFileRef)  {
        this.fileRef = newFileRef;
    }

    public java.lang.String getProcess() {
        return this.process;
    }

    public void setProcess(java.lang.String newProcess)  {
        this.process = newProcess;
    }

    public java.lang.String getReprocessJobCode() {
        return this.reprocessJobCode;
    }

    public void setReprocessJobCode(java.lang.String newReprocessJobCode)  {
        this.reprocessJobCode = newReprocessJobCode;
    }

}

