
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Mon Jun 08 17:37:32 IST 2015
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "setFeedBackApproval", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "setFeedBackApproval", namespace = "http://webservice.service.wise.remote/")

public class SetFeedBackApproval {

    @XmlElement(name = "reqObj")
    private remote.wise.service.datacontract.TestimonialFeedBackReqContract reqObj;

    public remote.wise.service.datacontract.TestimonialFeedBackReqContract getReqObj() {
        return this.reqObj;
    }

    public void setReqObj(remote.wise.service.datacontract.TestimonialFeedBackReqContract newReqObj)  {
        this.reqObj = newReqObj;
    }

}

