
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Jun 23 10:43:21 IST 2015
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "setJcbnews", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "setJcbnews", namespace = "http://webservice.service.wise.remote/")

public class SetJcbnews {

    @XmlElement(name = "reqObj")
    private remote.wise.service.datacontract.JcbNewsReqContract reqObj;

    public remote.wise.service.datacontract.JcbNewsReqContract getReqObj() {
        return this.reqObj;
    }

    public void setReqObj(remote.wise.service.datacontract.JcbNewsReqContract newReqObj)  {
        this.reqObj = newReqObj;
    }

}

