
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Mon Apr 15 11:58:33 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "SetLandmarkDetails", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SetLandmarkDetails", namespace = "http://webservice.service.wise.remote/")

public class SetLandmarkDetails {

    @XmlElement(name = "RespObj")
    private remote.wise.service.datacontract.LandmarkDetailsRespContract RespObj;

    public remote.wise.service.datacontract.LandmarkDetailsRespContract getRespObj() {
        return this.RespObj;
    }

    public void setRespObj(remote.wise.service.datacontract.LandmarkDetailsRespContract newRespObj)  {
        this.RespObj = newRespObj;
    }

}

