
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Mar 27 12:44:36 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "setLandmarkCategory1", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "setLandmarkCategory1", namespace = "http://webservice.service.wise.remote/")

public class SetLandmarkCategory1 {

    @XmlElement(name = "respObj")
    private remote.wise.service.datacontract.LandmarkCategoryRespContract respObj;

    public remote.wise.service.datacontract.LandmarkCategoryRespContract getRespObj() {
        return this.respObj;
    }

    public void setRespObj(remote.wise.service.datacontract.LandmarkCategoryRespContract newRespObj)  {
        this.respObj = newRespObj;
    }

}

