
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Thu Apr 25 17:28:39 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "SetMasterServiceScheduleService", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SetMasterServiceScheduleService", namespace = "http://webservice.service.wise.remote/")

public class SetMasterServiceScheduleService {

    @XmlElement(name = "setServiceSchedule")
    private remote.wise.service.datacontract.MasterServiceScheduleResponseContract setServiceSchedule;

    public remote.wise.service.datacontract.MasterServiceScheduleResponseContract getSetServiceSchedule() {
        return this.setServiceSchedule;
    }

    public void setSetServiceSchedule(remote.wise.service.datacontract.MasterServiceScheduleResponseContract newSetServiceSchedule)  {
        this.setServiceSchedule = newSetServiceSchedule;
    }

}

