
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Thu Aug 29 16:46:59 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "setMasterServiceScheduleDetails", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "setMasterServiceScheduleDetails", namespace = "http://webservice.service.wise.remote/", propOrder = {"servicePlan", "serviceName", "scheduleName", "dbmsPartCode", "assetGroupCode", "assetTypeCode", "engineTypeCode", "engineHours", "days", "messageId", "fileRef", "process", "reprocessJobCode"})

public class SetMasterServiceScheduleDetails {

    @XmlElement(name = "servicePlan")
    private java.lang.String servicePlan;
    @XmlElement(name = "serviceName")
    private java.lang.String serviceName;
    @XmlElement(name = "scheduleName")
    private java.lang.String scheduleName;
    @XmlElement(name = "dbmsPartCode")
    private java.lang.String dbmsPartCode;
    @XmlElement(name = "assetGroupCode")
    private java.lang.String assetGroupCode;
    @XmlElement(name = "assetTypeCode")
    private java.lang.String assetTypeCode;
    @XmlElement(name = "engineTypeCode")
    private java.lang.String engineTypeCode;
    @XmlElement(name = "engineHours")
    private java.lang.String engineHours;
    @XmlElement(name = "days")
    private java.lang.String days;
    @XmlElement(name = "messageId")
    private java.lang.String messageId;
    @XmlElement(name = "fileRef")
    private java.lang.String fileRef;
    @XmlElement(name = "process")
    private java.lang.String process;
    @XmlElement(name = "reprocessJobCode")
    private java.lang.String reprocessJobCode;

    public java.lang.String getServicePlan() {
        return this.servicePlan;
    }

    public void setServicePlan(java.lang.String newServicePlan)  {
        this.servicePlan = newServicePlan;
    }

    public java.lang.String getServiceName() {
        return this.serviceName;
    }

    public void setServiceName(java.lang.String newServiceName)  {
        this.serviceName = newServiceName;
    }

    public java.lang.String getScheduleName() {
        return this.scheduleName;
    }

    public void setScheduleName(java.lang.String newScheduleName)  {
        this.scheduleName = newScheduleName;
    }

    public java.lang.String getDbmsPartCode() {
        return this.dbmsPartCode;
    }

    public void setDbmsPartCode(java.lang.String newDbmsPartCode)  {
        this.dbmsPartCode = newDbmsPartCode;
    }

    public java.lang.String getAssetGroupCode() {
        return this.assetGroupCode;
    }

    public void setAssetGroupCode(java.lang.String newAssetGroupCode)  {
        this.assetGroupCode = newAssetGroupCode;
    }

    public java.lang.String getAssetTypeCode() {
        return this.assetTypeCode;
    }

    public void setAssetTypeCode(java.lang.String newAssetTypeCode)  {
        this.assetTypeCode = newAssetTypeCode;
    }

    public java.lang.String getEngineTypeCode() {
        return this.engineTypeCode;
    }

    public void setEngineTypeCode(java.lang.String newEngineTypeCode)  {
        this.engineTypeCode = newEngineTypeCode;
    }

    public java.lang.String getEngineHours() {
        return this.engineHours;
    }

    public void setEngineHours(java.lang.String newEngineHours)  {
        this.engineHours = newEngineHours;
    }

    public java.lang.String getDays() {
        return this.days;
    }

    public void setDays(java.lang.String newDays)  {
        this.days = newDays;
    }

    public java.lang.String getMessageId() {
        return this.messageId;
    }

    public void setMessageId(java.lang.String newMessageId)  {
        this.messageId = newMessageId;
    }

    public java.lang.String getFileRef() {
        return this.fileRef;
    }

    public void setFileRef(java.lang.String newFileRef)  {
        this.fileRef = newFileRef;
    }

    public java.lang.String getProcess() {
        return this.process;
    }

    public void setProcess(java.lang.String newProcess)  {
        this.process = newProcess;
    }

    public java.lang.String getReprocessJobCode() {
        return this.reprocessJobCode;
    }

    public void setReprocessJobCode(java.lang.String newReprocessJobCode)  {
        this.reprocessJobCode = newReprocessJobCode;
    }

}

