
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Apr 16 11:00:59 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "SetReportSubscriptionService", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SetReportSubscriptionService", namespace = "http://webservice.service.wise.remote/")

public class SetReportSubscriptionService {

    @XmlElement(name = "response")
    private java.util.List<remote.wise.service.datacontract.ReportSubscriptionRespContract> response;

    public java.util.List<remote.wise.service.datacontract.ReportSubscriptionRespContract> getResponse() {
        return this.response;
    }

    public void setResponse(java.util.List<remote.wise.service.datacontract.ReportSubscriptionRespContract> newResponse)  {
        this.response = newResponse;
    }

}

