
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Mon Feb 11 11:32:11 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "SetServiceScheduleService", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SetServiceScheduleService", namespace = "http://webservice.service.wise.remote/")

public class SetServiceScheduleService {

    @XmlElement(name = "setServiceSchedule")
    private remote.wise.service.datacontract.ServiceScheduleRespContract setServiceSchedule;

    public remote.wise.service.datacontract.ServiceScheduleRespContract getSetServiceSchedule() {
        return this.setServiceSchedule;
    }

    public void setSetServiceSchedule(remote.wise.service.datacontract.ServiceScheduleRespContract newSetServiceSchedule)  {
        this.setServiceSchedule = newSetServiceSchedule;
    }

}

