
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Jan 29 18:29:46 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "SetUserAlertPreference", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SetUserAlertPreference", namespace = "http://webservice.service.wise.remote/")

public class SetUserAlertPreference {

    @XmlElement(name = "reqObj")
    private java.util.List<remote.wise.service.datacontract.UserAlertPreferenceRespContract> reqObj;

    public java.util.List<remote.wise.service.datacontract.UserAlertPreferenceRespContract> getReqObj() {
        return this.reqObj;
    }

    public void setReqObj(java.util.List<remote.wise.service.datacontract.UserAlertPreferenceRespContract> newReqObj)  {
        this.reqObj = newReqObj;
    }

}

