
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Sat Feb 16 04:24:33 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "SetUserDetails", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SetUserDetails", namespace = "http://webservice.service.wise.remote/")

public class SetUserDetails {

    @XmlElement(name = "setUserDetails")
    private remote.wise.service.datacontract.UserDetailsRespContract setUserDetails;

    public remote.wise.service.datacontract.UserDetailsRespContract getSetUserDetails() {
        return this.setUserDetails;
    }

    public void setSetUserDetails(remote.wise.service.datacontract.UserDetailsRespContract newSetUserDetails)  {
        this.setUserDetails = newSetUserDetails;
    }

}

