
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Mon Jan 20 16:08:00 IST 2014
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "setVinMachineNameMapping", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "setVinMachineNameMapping", namespace = "http://webservice.service.wise.remote/", propOrder = {"serialNumber", "engineNumber", "chasisNumber", "messageId", "fileRef", "process", "reprocessJobCode", "make", "builtDate", "machineNumber"})

public class SetVinMachineNameMapping {

    @XmlElement(name = "serialNumber")
    private java.lang.String serialNumber;
    @XmlElement(name = "engineNumber")
    private java.lang.String engineNumber;
    @XmlElement(name = "chasisNumber")
    private java.lang.String chasisNumber;
    @XmlElement(name = "messageId")
    private java.lang.String messageId;
    @XmlElement(name = "fileRef")
    private java.lang.String fileRef;
    @XmlElement(name = "process")
    private java.lang.String process;
    @XmlElement(name = "reprocessJobCode")
    private java.lang.String reprocessJobCode;
    @XmlElement(name = "make")
    private java.lang.String make;
    @XmlElement(name = "builtDate")
    private java.lang.String builtDate;
    @XmlElement(name = "machineNumber")
    private java.lang.String machineNumber;

    public java.lang.String getSerialNumber() {
        return this.serialNumber;
    }

    public void setSerialNumber(java.lang.String newSerialNumber)  {
        this.serialNumber = newSerialNumber;
    }

    public java.lang.String getEngineNumber() {
        return this.engineNumber;
    }

    public void setEngineNumber(java.lang.String newEngineNumber)  {
        this.engineNumber = newEngineNumber;
    }

    public java.lang.String getChasisNumber() {
        return this.chasisNumber;
    }

    public void setChasisNumber(java.lang.String newChasisNumber)  {
        this.chasisNumber = newChasisNumber;
    }

    public java.lang.String getMessageId() {
        return this.messageId;
    }

    public void setMessageId(java.lang.String newMessageId)  {
        this.messageId = newMessageId;
    }

    public java.lang.String getFileRef() {
        return this.fileRef;
    }

    public void setFileRef(java.lang.String newFileRef)  {
        this.fileRef = newFileRef;
    }

    public java.lang.String getProcess() {
        return this.process;
    }

    public void setProcess(java.lang.String newProcess)  {
        this.process = newProcess;
    }

    public java.lang.String getReprocessJobCode() {
        return this.reprocessJobCode;
    }

    public void setReprocessJobCode(java.lang.String newReprocessJobCode)  {
        this.reprocessJobCode = newReprocessJobCode;
    }

    public java.lang.String getMake() {
        return this.make;
    }

    public void setMake(java.lang.String newMake)  {
        this.make = newMake;
    }

    public java.lang.String getBuiltDate() {
        return this.builtDate;
    }

    public void setBuiltDate(java.lang.String newBuiltDate)  {
        this.builtDate = newBuiltDate;
    }

    public java.lang.String getMachineNumber() {
        return this.machineNumber;
    }

    public void setMachineNumber(java.lang.String newMachineNumber)  {
        this.machineNumber = newMachineNumber;
    }

}

