
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Sep 18 14:15:22 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "updateNotificationFact", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateNotificationFact", namespace = "http://webservice.service.wise.remote/")

public class UpdateNotificationFact {


}

