
package remote.wise.service.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Fri Feb 01 15:17:10 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "UserAuthentication", namespace = "http://webservice.service.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserAuthentication", namespace = "http://webservice.service.wise.remote/")

public class UserAuthentication {

    @XmlElement(name = "reqobj")
    private remote.wise.service.datacontract.UserAuthenticationReqContract reqobj;

    public remote.wise.service.datacontract.UserAuthenticationReqContract getReqobj() {
        return this.reqobj;
    }

    public void setReqobj(remote.wise.service.datacontract.UserAuthenticationReqContract newReqobj)  {
        this.reqobj = newReqobj;
    }

}

