package remote.EAscheduler.RDealerMapping;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Fri Jan 02 13:06:42 IST 2015
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservices.EAintegration.wise.remote/", name = "RDealerMappingSample")
@XmlSeeAlso({ObjectFactory.class})
public interface RDealerMappingSample {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "reprocessEADealerMappingData", targetNamespace = "http://webservices.EAintegration.wise.remote/", className = "remote.EAscheduler.RDealerMapping.ReprocessEADealerMappingData")
    @WebMethod(action = "reprocessEADealerMappingData")
    @ResponseWrapper(localName = "reprocessEADealerMappingDataResponse", targetNamespace = "http://webservices.EAintegration.wise.remote/", className = "remote.EAscheduler.RDealerMapping.ReprocessEADealerMappingDataResponse")
    public java.lang.String reprocessEADealerMappingData(
        @WebParam(name = "msg", targetNamespace = "")
        java.lang.String msg
    );
}
