
/*
 * 
 */

package remote.EAscheduler.RDealerMapping;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Fri Jan 02 13:06:42 IST 2015
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "RDealerMappingSampleService", 
                  wsdlLocation = "http://localhost:27000/WISE/RDealerMappingSample?wsdl",
                  targetNamespace = "http://webservices.EAintegration.wise.remote/") 
public class RDealerMappingSampleService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservices.EAintegration.wise.remote/", "RDealerMappingSampleService");
    public final static QName RDealerMappingSamplePort = new QName("http://webservices.EAintegration.wise.remote/", "RDealerMappingSamplePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/RDealerMappingSample?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/RDealerMappingSample?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public RDealerMappingSampleService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RDealerMappingSampleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RDealerMappingSampleService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public RDealerMappingSampleService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public RDealerMappingSampleService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public RDealerMappingSampleService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns RDealerMappingSample
     */
    @WebEndpoint(name = "RDealerMappingSamplePort")
    public RDealerMappingSample getRDealerMappingSamplePort() {
        return super.getPort(RDealerMappingSamplePort, RDealerMappingSample.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RDealerMappingSample
     */
    @WebEndpoint(name = "RDealerMappingSamplePort")
    public RDealerMappingSample getRDealerMappingSamplePort(WebServiceFeature... features) {
        return super.getPort(RDealerMappingSamplePort, RDealerMappingSample.class, features);
    }

}
