
package remote.wise.EAintegration.clientPackage.ZonalInformationService;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Mon Feb 24 15:26:21 IST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */

@WebFault(name = "ParseException", targetNamespace = "http://webservice.service.wise.remote/")
public class ParseException_Exception extends Exception {
    public static final long serialVersionUID = 20140224152621L;
    
    private remote.wise.EAintegration.clientPackage.ZonalInformationService.ParseException parseException;

    public ParseException_Exception() {
        super();
    }
    
    public ParseException_Exception(String message) {
        super(message);
    }
    
    public ParseException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ParseException_Exception(String message, remote.wise.EAintegration.clientPackage.ZonalInformationService.ParseException parseException) {
        super(message);
        this.parseException = parseException;
    }

    public ParseException_Exception(String message, remote.wise.EAintegration.clientPackage.ZonalInformationService.ParseException parseException, Throwable cause) {
        super(message, cause);
        this.parseException = parseException;
    }

    public remote.wise.EAintegration.clientPackage.ZonalInformationService.ParseException getFaultInfo() {
        return this.parseException;
    }
}
