
/*
 * 
 */

package remote.wise.EAintegration.clientPackage.ZonalInformationService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Mon Feb 24 15:26:21 IST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "ZonalInformationServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/ZonalInformationService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class ZonalInformationServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "ZonalInformationServiceService");
    public final static QName ZonalInformationServicePort = new QName("http://webservice.service.wise.remote/", "ZonalInformationServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/ZonalInformationService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/ZonalInformationService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public ZonalInformationServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZonalInformationServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZonalInformationServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ZonalInformationServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public ZonalInformationServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public ZonalInformationServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ZonalInformationService
     */
    @WebEndpoint(name = "ZonalInformationServicePort")
    public ZonalInformationService getZonalInformationServicePort() {
        return super.getPort(ZonalInformationServicePort, ZonalInformationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZonalInformationService
     */
    @WebEndpoint(name = "ZonalInformationServicePort")
    public ZonalInformationService getZonalInformationServicePort(WebServiceFeature... features) {
        return super.getPort(ZonalInformationServicePort, ZonalInformationService.class, features);
    }

}
