package remote.wise.client.FotaFinalAlertService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Sep 25 13:53:21 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "FotaFinalAlertService")
@XmlSeeAlso({ObjectFactory.class})
public interface FotaFinalAlertService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "FotaFinalAlert", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.FotaFinalAlertService.FotaFinalAlert")
    @WebMethod(operationName = "FotaFinalAlert", action = "FotaFinalAlert")
    @ResponseWrapper(localName = "FotaFinalAlertResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.FotaFinalAlertService.FotaFinalAlertResponse")
    public remote.wise.client.FotaFinalAlertService.FotaFinalAlertRespContract fotaFinalAlert(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.FotaFinalAlertService.FotaFinalAlertReqContract reqObj
    ) throws CustomFault;
}
