
/*
 * 
 */

package remote.wise.client.FotaFinalAlertService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Sep 25 13:53:21 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "FotaFinalAlertServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/FotaFinalAlertService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class FotaFinalAlertServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "FotaFinalAlertServiceService");
    public final static QName FotaFinalAlertServicePort = new QName("http://webservice.service.wise.remote/", "FotaFinalAlertServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/FotaFinalAlertService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/FotaFinalAlertService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public FotaFinalAlertServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FotaFinalAlertServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FotaFinalAlertServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public FotaFinalAlertServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public FotaFinalAlertServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public FotaFinalAlertServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns FotaFinalAlertService
     */
    @WebEndpoint(name = "FotaFinalAlertServicePort")
    public FotaFinalAlertService getFotaFinalAlertServicePort() {
        return super.getPort(FotaFinalAlertServicePort, FotaFinalAlertService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FotaFinalAlertService
     */
    @WebEndpoint(name = "FotaFinalAlertServicePort")
    public FotaFinalAlertService getFotaFinalAlertServicePort(WebServiceFeature... features) {
        return super.getPort(FotaFinalAlertServicePort, FotaFinalAlertService.class, features);
    }

}
