package remote.wise.client.LandmarkAssetService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Sat Jun 08 18:51:43 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "LandmarkAssetService")
@XmlSeeAlso({ObjectFactory.class})
public interface LandmarkAssetService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "SetLandmarkAsset", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.LandmarkAssetService.SetLandmarkAsset")
    @WebMethod(operationName = "SetLandmarkAsset", action = "SetLandmarkAsset")
    @ResponseWrapper(localName = "SetLandmarkAssetResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.LandmarkAssetService.SetLandmarkAssetResponse")
    public java.lang.String setLandmarkAsset(
        @WebParam(name = "setLandmarkAsset", targetNamespace = "")
        remote.wise.client.LandmarkAssetService.LandmarkAssetRespContract setLandmarkAsset
    ) throws CustomFault;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetLandmarkAsset", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.LandmarkAssetService.GetLandmarkAsset")
    @WebMethod(operationName = "GetLandmarkAsset", action = "GetLandmarkAsset")
    @ResponseWrapper(localName = "GetLandmarkAssetResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.LandmarkAssetService.GetLandmarkAssetResponse")
    public java.util.List<remote.wise.client.LandmarkAssetService.LandmarkAssetRespContract> getLandmarkAsset(
        @WebParam(name = "arg0", targetNamespace = "")
        remote.wise.client.LandmarkAssetService.LandmarkAssetReqContract arg0
    ) throws CustomFault;
}
