package remote.wise.client.SMSAlertsService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Thu Dec 04 16:45:25 IST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "SMSAlertsService")
@XmlSeeAlso({ObjectFactory.class})
public interface SMSAlertsService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSMSAlerts", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.SMSAlertsService.GetSMSAlerts")
    @WebMethod(action = "getSMSAlerts")
    @ResponseWrapper(localName = "getSMSAlertsResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.SMSAlertsService.GetSMSAlertsResponse")
    public java.util.List<remote.wise.client.SMSAlertsService.SmsAlertsRespContract> getSMSAlerts(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.SMSAlertsService.SmsAlertsReqContract reqObj
    );
}
