package remote.wise.client.DetailedUsercommunicationReportService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Mon Feb 24 15:43:26 IST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "DetailedUsercommunicationReportService")
@XmlSeeAlso({ObjectFactory.class})
public interface DetailedUsercommunicationReportService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetDetailedUsercommunicationReport", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.DetailedUsercommunicationReportService.GetDetailedUsercommunicationReport")
    @WebMethod(operationName = "GetDetailedUsercommunicationReport", action = "GetDetailedUsercommunicationReport")
    @ResponseWrapper(localName = "GetDetailedUsercommunicationReportResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.DetailedUsercommunicationReportService.GetDetailedUsercommunicationReportResponse")
    public java.util.List<remote.wise.client.DetailedUsercommunicationReportService.DetailedUsercommunicationReportOutputContract> getDetailedUsercommunicationReport(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.DetailedUsercommunicationReportService.DetailedUsercommunicationReportInputContract reqObj
    ) throws CustomFault;
}
