
/*
 * 
 */

package remote.wise.client.DetailedUsercommunicationReportService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Mon Feb 24 15:43:26 IST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "DetailedUsercommunicationReportServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/DetailedUsercommunicationReportService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class DetailedUsercommunicationReportServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "DetailedUsercommunicationReportServiceService");
    public final static QName DetailedUsercommunicationReportServicePort = new QName("http://webservice.service.wise.remote/", "DetailedUsercommunicationReportServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/DetailedUsercommunicationReportService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/DetailedUsercommunicationReportService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public DetailedUsercommunicationReportServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DetailedUsercommunicationReportServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DetailedUsercommunicationReportServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public DetailedUsercommunicationReportServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public DetailedUsercommunicationReportServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public DetailedUsercommunicationReportServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns DetailedUsercommunicationReportService
     */
    @WebEndpoint(name = "DetailedUsercommunicationReportServicePort")
    public DetailedUsercommunicationReportService getDetailedUsercommunicationReportServicePort() {
        return super.getPort(DetailedUsercommunicationReportServicePort, DetailedUsercommunicationReportService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DetailedUsercommunicationReportService
     */
    @WebEndpoint(name = "DetailedUsercommunicationReportServicePort")
    public DetailedUsercommunicationReportService getDetailedUsercommunicationReportServicePort(WebServiceFeature... features) {
        return super.getPort(DetailedUsercommunicationReportServicePort, DetailedUsercommunicationReportService.class, features);
    }

}
