package remote.wise.client.ResetPasswordService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Mar 12 15:11:03 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "ResetPasswordService")
@XmlSeeAlso({ObjectFactory.class})
public interface ResetPasswordService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "ResetPassword", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.ResetPasswordService.ResetPassword")
    @WebMethod(operationName = "ResetPassword", action = "ResetPassword")
    @ResponseWrapper(localName = "ResetPasswordResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.ResetPasswordService.ResetPasswordResponse")
    public java.lang.String resetPassword(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.ResetPasswordService.ResetPasswordReqContract reqObj
    ) throws CustomFault;
}
