package remote.wise.client.MachineServiceDueOverDueReportService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Thu Dec 19 11:33:14 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "MachineServiceDueOverDueReportService")
@XmlSeeAlso({ObjectFactory.class})
public interface MachineServiceDueOverDueReportService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetMachineServiceDueOverDueCount", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.MachineServiceDueOverDueReportService.GetMachineServiceDueOverDueCount")
    @WebMethod(operationName = "GetMachineServiceDueOverDueCount", action = "GetMachineServiceDueOverDueCount")
    @ResponseWrapper(localName = "GetMachineServiceDueOverDueCountResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.MachineServiceDueOverDueReportService.GetMachineServiceDueOverDueCountResponse")
    public java.util.List<remote.wise.client.MachineServiceDueOverDueReportService.MachineServiceDueOverDueRespContract> getMachineServiceDueOverDueCount(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.MachineServiceDueOverDueReportService.MachineServiceDueOverDueReqContract reqObj
    ) throws CustomFault;
}
