package remote.wise.EAintegration.clientPackage.AssetGateOut;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Aug 20 15:53:54 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "AssetGateoutService")
@XmlSeeAlso({ObjectFactory.class})
public interface AssetGateoutService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "setAssetGateoutService", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.EAintegration.clientPackage.AssetGateOut.SetAssetGateoutService")
    @WebMethod(action = "setAssetGateoutService")
    @ResponseWrapper(localName = "setAssetGateoutServiceResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.EAintegration.clientPackage.AssetGateOut.SetAssetGateoutServiceResponse")
    public java.lang.String setAssetGateoutService(
        @WebParam(name = "dealerCode", targetNamespace = "")
        java.lang.String dealerCode,
        @WebParam(name = "customerCode", targetNamespace = "")
        java.lang.String customerCode,
        @WebParam(name = "engineNumber", targetNamespace = "")
        java.lang.String engineNumber,
        @WebParam(name = "serialNumber", targetNamespace = "")
        java.lang.String serialNumber,
        @WebParam(name = "messageId", targetNamespace = "")
        java.lang.String messageId,
        @WebParam(name = "fileRef", targetNamespace = "")
        java.lang.String fileRef,
        @WebParam(name = "process", targetNamespace = "")
        java.lang.String process,
        @WebParam(name = "reprocessJobCode", targetNamespace = "")
        java.lang.String reprocessJobCode
    );
}
