package remote.wise.client.UtilizationSummaryReportService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Fri Dec 13 17:48:39 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "UtilizationSummaryReportService")
@XmlSeeAlso({ObjectFactory.class})
public interface UtilizationSummaryReportService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetUtilizationSummaryReport", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.UtilizationSummaryReportService.GetUtilizationSummaryReport")
    @WebMethod(operationName = "GetUtilizationSummaryReport", action = "GetUtilizationSummaryReport")
    @ResponseWrapper(localName = "GetUtilizationSummaryReportResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.UtilizationSummaryReportService.GetUtilizationSummaryReportResponse")
    public java.util.List<remote.wise.client.UtilizationSummaryReportService.UtilizationSummaryReportRespContract> getUtilizationSummaryReport(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.UtilizationSummaryReportService.UtilizationSummaryReportReqContract reqObj
    ) throws CustomFault;
}
