
/*
 * 
 */

package remote.wise.EAintegration.clientPackage.CustomerInformationService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Jul 31 14:34:53 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "CustomerInformationServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/CustomerInformationService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class CustomerInformationServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "CustomerInformationServiceService");
    public final static QName CustomerInformationServicePort = new QName("http://webservice.service.wise.remote/", "CustomerInformationServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/CustomerInformationService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/CustomerInformationService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public CustomerInformationServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CustomerInformationServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerInformationServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CustomerInformationServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public CustomerInformationServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public CustomerInformationServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns CustomerInformationService
     */
    @WebEndpoint(name = "CustomerInformationServicePort")
    public CustomerInformationService getCustomerInformationServicePort() {
        return super.getPort(CustomerInformationServicePort, CustomerInformationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerInformationService
     */
    @WebEndpoint(name = "CustomerInformationServicePort")
    public CustomerInformationService getCustomerInformationServicePort(WebServiceFeature... features) {
        return super.getPort(CustomerInformationServicePort, CustomerInformationService.class, features);
    }

}
