
/*
 * 
 */

package remote.EAscheduler.AssetInstallationDetails;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Fri Jun 19 11:45:09 IST 2015
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "AssetInstallationDetailsSampleService", 
                  wsdlLocation = "http://localhost:27000/WISE/AssetInstallationDetailsSample?wsdl",
                  targetNamespace = "http://webservices.EAintegration.wise.remote/") 
public class AssetInstallationDetailsSampleService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservices.EAintegration.wise.remote/", "AssetInstallationDetailsSampleService");
    public final static QName AssetInstallationDetailsSamplePort = new QName("http://webservices.EAintegration.wise.remote/", "AssetInstallationDetailsSamplePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/AssetInstallationDetailsSample?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/AssetInstallationDetailsSample?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public AssetInstallationDetailsSampleService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AssetInstallationDetailsSampleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AssetInstallationDetailsSampleService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public AssetInstallationDetailsSampleService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public AssetInstallationDetailsSampleService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public AssetInstallationDetailsSampleService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns AssetInstallationDetailsSample
     */
    @WebEndpoint(name = "AssetInstallationDetailsSamplePort")
    public AssetInstallationDetailsSample getAssetInstallationDetailsSamplePort() {
        return super.getPort(AssetInstallationDetailsSamplePort, AssetInstallationDetailsSample.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AssetInstallationDetailsSample
     */
    @WebEndpoint(name = "AssetInstallationDetailsSamplePort")
    public AssetInstallationDetailsSample getAssetInstallationDetailsSamplePort(WebServiceFeature... features) {
        return super.getPort(AssetInstallationDetailsSamplePort, AssetInstallationDetailsSample.class, features);
    }

}
