package remote.wise.client.RoleService;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Thu Mar 28 11:17:19 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "RoleService")
@XmlSeeAlso({ObjectFactory.class})
public interface RoleService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetRoles", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.RoleService.GetRoles")
    @WebMethod(operationName = "GetRoles", action = "GetRoles")
    @ResponseWrapper(localName = "GetRolesResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.RoleService.GetRolesResponse")
    public java.util.List<remote.wise.client.RoleService.RoleRespContract> getRoles();
}
