
/*
 * 
 */

package remote.wise.client.MachineDueOverdueReportService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Mon Dec 16 15:12:03 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "MachineDueOverdueReportServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/MachineDueOverdueReportService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class MachineDueOverdueReportServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "MachineDueOverdueReportServiceService");
    public final static QName MachineDueOverdueReportServicePort = new QName("http://webservice.service.wise.remote/", "MachineDueOverdueReportServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/MachineDueOverdueReportService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/MachineDueOverdueReportService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public MachineDueOverdueReportServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MachineDueOverdueReportServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MachineDueOverdueReportServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public MachineDueOverdueReportServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public MachineDueOverdueReportServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public MachineDueOverdueReportServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns MachineDueOverdueReportService
     */
    @WebEndpoint(name = "MachineDueOverdueReportServicePort")
    public MachineDueOverdueReportService getMachineDueOverdueReportServicePort() {
        return super.getPort(MachineDueOverdueReportServicePort, MachineDueOverdueReportService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MachineDueOverdueReportService
     */
    @WebEndpoint(name = "MachineDueOverdueReportServicePort")
    public MachineDueOverdueReportService getMachineDueOverdueReportServicePort(WebServiceFeature... features) {
        return super.getPort(MachineDueOverdueReportServicePort, MachineDueOverdueReportService.class, features);
    }

}
