
/*
 * 
 */

package remote.wise.client.SavedReportsService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Jun 05 11:52:19 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "SavedReportServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/SavedReportService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class SavedReportServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "SavedReportServiceService");
    public final static QName SavedReportServicePort = new QName("http://webservice.service.wise.remote/", "SavedReportServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/SavedReportService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/SavedReportService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SavedReportServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SavedReportServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SavedReportServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SavedReportServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public SavedReportServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public SavedReportServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns SavedReportService
     */
    @WebEndpoint(name = "SavedReportServicePort")
    public SavedReportService getSavedReportServicePort() {
        return super.getPort(SavedReportServicePort, SavedReportService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SavedReportService
     */
    @WebEndpoint(name = "SavedReportServicePort")
    public SavedReportService getSavedReportServicePort(WebServiceFeature... features) {
        return super.getPort(SavedReportServicePort, SavedReportService.class, features);
    }

}
