package remote.wise.client.SavedReportsService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Jun 05 11:52:19 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "SavedReportService")
@XmlSeeAlso({ObjectFactory.class})
public interface SavedReportService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetSavedReportService", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.SavedReportsService.GetSavedReportService")
    @WebMethod(operationName = "GetSavedReportService", action = "GetSavedReportService")
    @ResponseWrapper(localName = "GetSavedReportServiceResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.SavedReportsService.GetSavedReportServiceResponse")
    public java.util.List<remote.wise.client.SavedReportsService.SavedReportRespContract> getSavedReportService(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.SavedReportsService.SavedReportReqContract reqObj
    ) throws CustomFault;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "SetSavedReportService", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.SavedReportsService.SetSavedReportService")
    @WebMethod(operationName = "SetSavedReportService", action = "SetSavedReportService")
    @ResponseWrapper(localName = "SetSavedReportServiceResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.SavedReportsService.SetSavedReportServiceResponse")
    public java.lang.String setSavedReportService(
        @WebParam(name = "respObj", targetNamespace = "")
        remote.wise.client.SavedReportsService.SavedReportRespContract respObj
    ) throws CustomFault;
}
