package remote.wise.client.FuelUtilizationDetailService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Sat Sep 14 09:43:23 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "FuelUtilizationDetailService")
@XmlSeeAlso({ObjectFactory.class})
public interface FuelUtilizationDetailService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetFuelUtilizationDetail", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.FuelUtilizationDetailService.GetFuelUtilizationDetail")
    @WebMethod(operationName = "GetFuelUtilizationDetail", action = "GetFuelUtilizationDetail")
    @ResponseWrapper(localName = "GetFuelUtilizationDetailResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.FuelUtilizationDetailService.GetFuelUtilizationDetailResponse")
    public java.util.List<remote.wise.client.FuelUtilizationDetailService.FuelUtilizationDetailRespContract> getFuelUtilizationDetail(
        @WebParam(name = "ReqObj", targetNamespace = "")
        remote.wise.client.FuelUtilizationDetailService.FuelUtilizationDetailReqContract reqObj
    ) throws CustomFault;
}
