package remote.wise.client.StateService;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Mar 09 16:18:20 IST 2016
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "StateService")
@XmlSeeAlso({ObjectFactory.class})
public interface StateService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetStates", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.StateService.GetStates")
    @WebMethod(operationName = "GetStates", action = "GetStates")
    @ResponseWrapper(localName = "GetStatesResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.StateService.GetStatesResponse")
    public java.util.List<remote.wise.client.StateService.StateRespContract> getStates() throws CustomFault;
}
