
/*
 * 
 */

package remote.wise.client.StateService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Mar 09 16:18:20 IST 2016
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "StateServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/StateService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class StateServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "StateServiceService");
    public final static QName StateServicePort = new QName("http://webservice.service.wise.remote/", "StateServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/StateService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/StateService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public StateServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StateServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StateServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public StateServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public StateServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public StateServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns StateService
     */
    @WebEndpoint(name = "StateServicePort")
    public StateService getStateServicePort() {
        return super.getPort(StateServicePort, StateService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StateService
     */
    @WebEndpoint(name = "StateServicePort")
    public StateService getStateServicePort(WebServiceFeature... features) {
        return super.getPort(StateServicePort, StateService.class, features);
    }

}
