
/*
 * 
 */

package remote.wise.client.MachineHourMeterTrendDataReportService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Dec 17 15:04:47 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "MachineHourMeterTrendDataReportServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/MachineHourMeterTrendDataReportService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class MachineHourMeterTrendDataReportServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "MachineHourMeterTrendDataReportServiceService");
    public final static QName MachineHourMeterTrendDataReportServicePort = new QName("http://webservice.service.wise.remote/", "MachineHourMeterTrendDataReportServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/MachineHourMeterTrendDataReportService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/MachineHourMeterTrendDataReportService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public MachineHourMeterTrendDataReportServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MachineHourMeterTrendDataReportServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MachineHourMeterTrendDataReportServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public MachineHourMeterTrendDataReportServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public MachineHourMeterTrendDataReportServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public MachineHourMeterTrendDataReportServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns MachineHourMeterTrendDataReportService
     */
    @WebEndpoint(name = "MachineHourMeterTrendDataReportServicePort")
    public MachineHourMeterTrendDataReportService getMachineHourMeterTrendDataReportServicePort() {
        return super.getPort(MachineHourMeterTrendDataReportServicePort, MachineHourMeterTrendDataReportService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MachineHourMeterTrendDataReportService
     */
    @WebEndpoint(name = "MachineHourMeterTrendDataReportServicePort")
    public MachineHourMeterTrendDataReportService getMachineHourMeterTrendDataReportServicePort(WebServiceFeature... features) {
        return super.getPort(MachineHourMeterTrendDataReportServicePort, MachineHourMeterTrendDataReportService.class, features);
    }

}
