package remote.wise.client.MachineHourMeterTrendDataReportService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Dec 17 15:04:47 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "MachineHourMeterTrendDataReportService")
@XmlSeeAlso({ObjectFactory.class})
public interface MachineHourMeterTrendDataReportService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getMachineTrendDataForAllZones", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.MachineHourMeterTrendDataReportService.GetMachineTrendDataForAllZones")
    @WebMethod(action = "getMachineTrendDataForAllZones")
    @ResponseWrapper(localName = "getMachineTrendDataForAllZonesResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.MachineHourMeterTrendDataReportService.GetMachineTrendDataForAllZonesResponse")
    public java.util.List<remote.wise.client.MachineHourMeterTrendDataReportService.MachineHourMeterTrendDataReportRespContract> getMachineTrendDataForAllZones(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.MachineHourMeterTrendDataReportService.MachineHourMeterTrendDataReportReqContract reqObj
    ) throws CustomFault;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getMachineHourMeterTrendData", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.MachineHourMeterTrendDataReportService.GetMachineHourMeterTrendData")
    @WebMethod(action = "getMachineHourMeterTrendData")
    @ResponseWrapper(localName = "getMachineHourMeterTrendDataResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.MachineHourMeterTrendDataReportService.GetMachineHourMeterTrendDataResponse")
    public java.util.List<remote.wise.client.MachineHourMeterTrendDataReportService.MachineHourMeterTrendDataReportRespContract> getMachineHourMeterTrendData(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.MachineHourMeterTrendDataReportService.MachineHourMeterTrendDataReportReqContract reqObj
    ) throws CustomFault;
}
