package remote.wise.EAintegration.clientPackage.DealerMappingService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Dec 24 13:01:37 IST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "DealerMappingService")
@XmlSeeAlso({ObjectFactory.class})
public interface DealerMappingService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "setDealerMapping", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.EAintegration.clientPackage.DealerMappingService.SetDealerMapping")
    @WebMethod(action = "setDealerMapping")
    @ResponseWrapper(localName = "setDealerMappingResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.EAintegration.clientPackage.DealerMappingService.SetDealerMappingResponse")
    public java.lang.String setDealerMapping(
        @WebParam(name = "eccCode", targetNamespace = "")
        java.lang.String eccCode,
        @WebParam(name = "crmCode", targetNamespace = "")
        java.lang.String crmCode,
        @WebParam(name = "llCode", targetNamespace = "")
        java.lang.String llCode,
        @WebParam(name = "dealerName", targetNamespace = "")
        java.lang.String dealerName,
        @WebParam(name = "messageId", targetNamespace = "")
        java.lang.String messageId,
        @WebParam(name = "fileRef", targetNamespace = "")
        java.lang.String fileRef,
        @WebParam(name = "process", targetNamespace = "")
        java.lang.String process,
        @WebParam(name = "reprocessJobCode", targetNamespace = "")
        java.lang.String reprocessJobCode
    );
}
