
/*
 * 
 */

package remote.wise.EAintegration.clientPackage.DealerMappingService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Dec 24 13:01:37 IST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "DealerMappingServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/DealerMappingService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class DealerMappingServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "DealerMappingServiceService");
    public final static QName DealerMappingServicePort = new QName("http://webservice.service.wise.remote/", "DealerMappingServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/DealerMappingService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/DealerMappingService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public DealerMappingServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DealerMappingServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DealerMappingServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public DealerMappingServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public DealerMappingServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public DealerMappingServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns DealerMappingService
     */
    @WebEndpoint(name = "DealerMappingServicePort")
    public DealerMappingService getDealerMappingServicePort() {
        return super.getPort(DealerMappingServicePort, DealerMappingService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DealerMappingService
     */
    @WebEndpoint(name = "DealerMappingServicePort")
    public DealerMappingService getDealerMappingServicePort(WebServiceFeature... features) {
        return super.getPort(DealerMappingServicePort, DealerMappingService.class, features);
    }

}
