package remote.wise.client.MachineHealthDetailsService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Mar 13 18:57:54 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "MachineHealthDetailsService")
@XmlSeeAlso({ObjectFactory.class})
public interface MachineHealthDetailsService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetMachineHealthDetails", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.MachineHealthDetailsService.GetMachineHealthDetails")
    @WebMethod(operationName = "GetMachineHealthDetails", action = "GetMachineHealthDetails")
    @ResponseWrapper(localName = "GetMachineHealthDetailsResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.MachineHealthDetailsService.GetMachineHealthDetailsResponse")
    public java.util.List<remote.wise.client.MachineHealthDetailsService.MachineHealthDetailsRespContract> getMachineHealthDetails(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.MachineHealthDetailsService.MachineHealthDetailsReqContract reqObj
    ) throws CustomFault;
}
