
/*
 * 
 */

package remote.wise.client.ReportMasterListService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Mar 12 16:27:58 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "ReportMasterListServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/ReportMasterListService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class ReportMasterListServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "ReportMasterListServiceService");
    public final static QName ReportMasterListServicePort = new QName("http://webservice.service.wise.remote/", "ReportMasterListServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/ReportMasterListService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/ReportMasterListService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public ReportMasterListServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ReportMasterListServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReportMasterListServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ReportMasterListServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public ReportMasterListServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public ReportMasterListServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ReportMasterListService
     */
    @WebEndpoint(name = "ReportMasterListServicePort")
    public ReportMasterListService getReportMasterListServicePort() {
        return super.getPort(ReportMasterListServicePort, ReportMasterListService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReportMasterListService
     */
    @WebEndpoint(name = "ReportMasterListServicePort")
    public ReportMasterListService getReportMasterListServicePort(WebServiceFeature... features) {
        return super.getPort(ReportMasterListServicePort, ReportMasterListService.class, features);
    }

}
