package remote.wise.client.RolledOffMachinesService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Fri Oct 10 12:11:52 IST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "RolledOffMachinesService")
@XmlSeeAlso({ObjectFactory.class})
public interface RolledOffMachinesService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRolledOffMachines", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.RolledOffMachinesService.GetRolledOffMachines")
    @WebMethod(action = "getRolledOffMachines")
    @ResponseWrapper(localName = "getRolledOffMachinesResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.RolledOffMachinesService.GetRolledOffMachinesResponse")
    public java.util.List<remote.wise.client.RolledOffMachinesService.RolledOffMachinesRespContract> getRolledOffMachines(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.RolledOffMachinesService.RolledOffMachinesReqContract reqObj
    ) throws CustomFault;
}
