package remote.wise.client.FotaUpgradedHistoryDetailsService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Feb 12 16:45:32 IST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "FotaUpgradedHistoryDetailsService")
@XmlSeeAlso({ObjectFactory.class})
public interface FotaUpgradedHistoryDetailsService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getFotaUpgradedDetails", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.FotaUpgradedHistoryDetailsService.GetFotaUpgradedDetails")
    @WebMethod(action = "getFotaUpgradedDetails")
    @ResponseWrapper(localName = "getFotaUpgradedDetailsResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.FotaUpgradedHistoryDetailsService.GetFotaUpgradedDetailsResponse")
    public java.util.List<remote.wise.client.FotaUpgradedHistoryDetailsService.FotaUpgradedHistoryDetailsRespContract> getFotaUpgradedDetails(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.FotaUpgradedHistoryDetailsService.FotaUpgradedHistoryDetailsReqContract reqObj
    ) throws CustomFault;
}
