package remote.wise.client.MachinePerformanceReportService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Fri Dec 13 18:11:29 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "MachinePerformanceReportService")
@XmlSeeAlso({ObjectFactory.class})
public interface MachinePerformanceReportService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "MachinePerformanceReportService", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.MachinePerformanceReportService.MachinePerformanceReportService_Type")
    @WebMethod(operationName = "MachinePerformanceReportService", action = "MachinePerformanceReportService")
    @ResponseWrapper(localName = "MachinePerformanceReportServiceResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.MachinePerformanceReportService.MachinePerformanceReportServiceResponse")
    public java.util.List<remote.wise.client.MachinePerformanceReportService.MachinePerformanceReportRespContract> machinePerformanceReportService(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.MachinePerformanceReportService.MachinePerformanceReportReqContract reqObj
    );
}
