package remote.wise.client.MachineProfileService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Mar 12 16:20:23 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "MachineProfileService")
@XmlSeeAlso({ObjectFactory.class})
public interface MachineProfileService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "SetMachineProfileService", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.MachineProfileService.SetMachineProfileService")
    @WebMethod(operationName = "SetMachineProfileService", action = "SetMachineProfileService")
    @ResponseWrapper(localName = "SetMachineProfileServiceResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.MachineProfileService.SetMachineProfileServiceResponse")
    public java.lang.String setMachineProfileService(
        @WebParam(name = "respObj", targetNamespace = "")
        remote.wise.client.MachineProfileService.MachineProfileRespContract respObj
    ) throws CustomFault;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetMachineProfileService", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.MachineProfileService.GetMachineProfileService")
    @WebMethod(operationName = "GetMachineProfileService", action = "GetMachineProfileService")
    @ResponseWrapper(localName = "GetMachineProfileServiceResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.MachineProfileService.GetMachineProfileServiceResponse")
    public java.util.List<remote.wise.client.MachineProfileService.MachineProfileRespContract> getMachineProfileService(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.MachineProfileService.MachineProfileReqContract reqObj
    ) throws CustomFault;
}
