
/*
 * 
 */

package remote.wise.client.MachineProfileService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Mar 12 16:20:23 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "MachineProfileServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/MachineProfileService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class MachineProfileServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "MachineProfileServiceService");
    public final static QName MachineProfileServicePort = new QName("http://webservice.service.wise.remote/", "MachineProfileServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/MachineProfileService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/MachineProfileService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public MachineProfileServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MachineProfileServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MachineProfileServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public MachineProfileServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public MachineProfileServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public MachineProfileServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns MachineProfileService
     */
    @WebEndpoint(name = "MachineProfileServicePort")
    public MachineProfileService getMachineProfileServicePort() {
        return super.getPort(MachineProfileServicePort, MachineProfileService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MachineProfileService
     */
    @WebEndpoint(name = "MachineProfileServicePort")
    public MachineProfileService getMachineProfileServicePort(WebServiceFeature... features) {
        return super.getPort(MachineProfileServicePort, MachineProfileService.class, features);
    }

}
