
/*
 * 
 */

package remote.wise.client.FotaAuthenticationService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Aug 28 12:28:59 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "FotaAuthenticationServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/FotaAuthenticationService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class FotaAuthenticationServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "FotaAuthenticationServiceService");
    public final static QName FotaAuthenticationServicePort = new QName("http://webservice.service.wise.remote/", "FotaAuthenticationServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/FotaAuthenticationService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/FotaAuthenticationService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public FotaAuthenticationServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FotaAuthenticationServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FotaAuthenticationServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public FotaAuthenticationServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public FotaAuthenticationServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public FotaAuthenticationServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns FotaAuthenticationService
     */
    @WebEndpoint(name = "FotaAuthenticationServicePort")
    public FotaAuthenticationService getFotaAuthenticationServicePort() {
        return super.getPort(FotaAuthenticationServicePort, FotaAuthenticationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FotaAuthenticationService
     */
    @WebEndpoint(name = "FotaAuthenticationServicePort")
    public FotaAuthenticationService getFotaAuthenticationServicePort(WebServiceFeature... features) {
        return super.getPort(FotaAuthenticationServicePort, FotaAuthenticationService.class, features);
    }

}
