package remote.wise.client.ServiceHistoryDetailsService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Apr 03 10:48:33 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "ServiceHistoryDetailsService")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceHistoryDetailsService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "SetServiceHistoryDetails", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.ServiceHistoryDetailsService.SetServiceHistoryDetails")
    @WebMethod(operationName = "SetServiceHistoryDetails", action = "SetServiceHistoryDetails")
    @ResponseWrapper(localName = "SetServiceHistoryDetailsResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.ServiceHistoryDetailsService.SetServiceHistoryDetailsResponse")
    public java.lang.String setServiceHistoryDetails(
        @WebParam(name = "setServiceSchedule", targetNamespace = "")
        remote.wise.client.ServiceHistoryDetailsService.ServiceScheduleRespContract setServiceSchedule
    ) throws CustomFault;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetServiceHistoryDetails", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.ServiceHistoryDetailsService.GetServiceHistoryDetails")
    @WebMethod(operationName = "GetServiceHistoryDetails", action = "GetServiceHistoryDetails")
    @ResponseWrapper(localName = "GetServiceHistoryDetailsResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.ServiceHistoryDetailsService.GetServiceHistoryDetailsResponse")
    public java.util.List<remote.wise.client.ServiceHistoryDetailsService.ServiceHistoryRespContract> getServiceHistoryDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        remote.wise.client.ServiceHistoryDetailsService.ServiceHistoryReqContract arg0
    ) throws CustomFault;
}
