
/*
 * 
 */

package remote.wise.client.CustomerRequiringService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Fri Mar 15 11:34:38 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "CustomerRequiringServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/CustomerRequiringService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class CustomerRequiringServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "CustomerRequiringServiceService");
    public final static QName CustomerRequiringServicePort = new QName("http://webservice.service.wise.remote/", "CustomerRequiringServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/CustomerRequiringService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/CustomerRequiringService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public CustomerRequiringServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CustomerRequiringServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerRequiringServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CustomerRequiringServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public CustomerRequiringServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public CustomerRequiringServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns CustomerRequiringService
     */
    @WebEndpoint(name = "CustomerRequiringServicePort")
    public CustomerRequiringService getCustomerRequiringServicePort() {
        return super.getPort(CustomerRequiringServicePort, CustomerRequiringService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerRequiringService
     */
    @WebEndpoint(name = "CustomerRequiringServicePort")
    public CustomerRequiringService getCustomerRequiringServicePort(WebServiceFeature... features) {
        return super.getPort(CustomerRequiringServicePort, CustomerRequiringService.class, features);
    }

}
