
/*
 * 
 */

package remote.wise.client.PricolRollOffService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue May 21 09:55:28 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "PricolRollOffServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/PricolRollOffService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class PricolRollOffServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "PricolRollOffServiceService");
    public final static QName PricolRollOffServicePort = new QName("http://webservice.service.wise.remote/", "PricolRollOffServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/PricolRollOffService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/PricolRollOffService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public PricolRollOffServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PricolRollOffServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PricolRollOffServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public PricolRollOffServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public PricolRollOffServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public PricolRollOffServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns PricolRollOffService
     */
    @WebEndpoint(name = "PricolRollOffServicePort")
    public PricolRollOffService getPricolRollOffServicePort() {
        return super.getPort(PricolRollOffServicePort, PricolRollOffService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PricolRollOffService
     */
    @WebEndpoint(name = "PricolRollOffServicePort")
    public PricolRollOffService getPricolRollOffServicePort(WebServiceFeature... features) {
        return super.getPort(PricolRollOffServicePort, PricolRollOffService.class, features);
    }

}
