
/*
 * 
 */

package remote.wise.client.NotificationReportDetailsService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Fri Mar 07 10:18:27 IST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "NotificationReportDetailsServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/NotificationReportDetailsService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class NotificationReportDetailsServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "NotificationReportDetailsServiceService");
    public final static QName NotificationReportDetailsServicePort = new QName("http://webservice.service.wise.remote/", "NotificationReportDetailsServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/NotificationReportDetailsService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/NotificationReportDetailsService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public NotificationReportDetailsServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NotificationReportDetailsServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NotificationReportDetailsServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public NotificationReportDetailsServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public NotificationReportDetailsServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public NotificationReportDetailsServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns NotificationReportDetailsService
     */
    @WebEndpoint(name = "NotificationReportDetailsServicePort")
    public NotificationReportDetailsService getNotificationReportDetailsServicePort() {
        return super.getPort(NotificationReportDetailsServicePort, NotificationReportDetailsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NotificationReportDetailsService
     */
    @WebEndpoint(name = "NotificationReportDetailsServicePort")
    public NotificationReportDetailsService getNotificationReportDetailsServicePort(WebServiceFeature... features) {
        return super.getPort(NotificationReportDetailsServicePort, NotificationReportDetailsService.class, features);
    }

}
