package remote.wise.client.NotificationReportDetailsService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Fri Mar 07 10:18:27 IST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "NotificationReportDetailsService")
@XmlSeeAlso({ObjectFactory.class})
public interface NotificationReportDetailsService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetNotificationReportDetailsService", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.NotificationReportDetailsService.GetNotificationReportDetailsService")
    @WebMethod(operationName = "GetNotificationReportDetailsService", action = "GetNotificationReportDetailsService")
    @ResponseWrapper(localName = "GetNotificationReportDetailsServiceResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.NotificationReportDetailsService.GetNotificationReportDetailsServiceResponse")
    public java.util.List<remote.wise.client.NotificationReportDetailsService.NotificationReportDetailsRespContract> getNotificationReportDetailsService(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.NotificationReportDetailsService.NotificationReportDetailsReqContract reqObj
    );
}
