package remote.wise.client.DetailMachineInfoService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Nov 05 10:09:48 IST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "DetailMachineInfoService")
@XmlSeeAlso({ObjectFactory.class})
public interface DetailMachineInfoService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDetailMachineInfo", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.DetailMachineInfoService.GetDetailMachineInfo")
    @WebMethod(action = "getDetailMachineInfo")
    @ResponseWrapper(localName = "getDetailMachineInfoResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.DetailMachineInfoService.GetDetailMachineInfoResponse")
    public java.util.List<remote.wise.client.DetailMachineInfoService.DetailMachineInfoRespContract> getDetailMachineInfo(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.DetailMachineInfoService.DetailMachineInfoReqContract reqObj
    ) throws CustomFault;
}
