
/*
 * 
 */

package remote.wise.client.DetailMachineInfoService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Nov 05 10:09:48 IST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "DetailMachineInfoServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/DetailMachineInfoService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class DetailMachineInfoServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "DetailMachineInfoServiceService");
    public final static QName DetailMachineInfoServicePort = new QName("http://webservice.service.wise.remote/", "DetailMachineInfoServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/DetailMachineInfoService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/DetailMachineInfoService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public DetailMachineInfoServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DetailMachineInfoServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DetailMachineInfoServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public DetailMachineInfoServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public DetailMachineInfoServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public DetailMachineInfoServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns DetailMachineInfoService
     */
    @WebEndpoint(name = "DetailMachineInfoServicePort")
    public DetailMachineInfoService getDetailMachineInfoServicePort() {
        return super.getPort(DetailMachineInfoServicePort, DetailMachineInfoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DetailMachineInfoService
     */
    @WebEndpoint(name = "DetailMachineInfoServicePort")
    public DetailMachineInfoService getDetailMachineInfoServicePort(WebServiceFeature... features) {
        return super.getPort(DetailMachineInfoServicePort, DetailMachineInfoService.class, features);
    }

}
