
/*
 * 
 */

package remote.wise.client.ServiceScheduleService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Mar 12 16:47:21 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "ServiceScheduleServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/ServiceScheduleService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class ServiceScheduleServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "ServiceScheduleServiceService");
    public final static QName ServiceScheduleServicePort = new QName("http://webservice.service.wise.remote/", "ServiceScheduleServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/ServiceScheduleService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/ServiceScheduleService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public ServiceScheduleServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServiceScheduleServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceScheduleServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ServiceScheduleServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public ServiceScheduleServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public ServiceScheduleServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ServiceScheduleService
     */
    @WebEndpoint(name = "ServiceScheduleServicePort")
    public ServiceScheduleService getServiceScheduleServicePort() {
        return super.getPort(ServiceScheduleServicePort, ServiceScheduleService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceScheduleService
     */
    @WebEndpoint(name = "ServiceScheduleServicePort")
    public ServiceScheduleService getServiceScheduleServicePort(WebServiceFeature... features) {
        return super.getPort(ServiceScheduleServicePort, ServiceScheduleService.class, features);
    }

}
