
/*
 * 
 */

package remote.EAscheduler.AssetSaleFromD2C;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Fri Jun 19 11:51:31 IST 2015
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "AssetSaleFromD2CSampleService", 
                  wsdlLocation = "http://localhost:27000/WISE/AssetSaleFromD2CSample?wsdl",
                  targetNamespace = "http://webservices.EAintegration.wise.remote/") 
public class AssetSaleFromD2CSampleService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservices.EAintegration.wise.remote/", "AssetSaleFromD2CSampleService");
    public final static QName AssetSaleFromD2CSamplePort = new QName("http://webservices.EAintegration.wise.remote/", "AssetSaleFromD2CSamplePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/AssetSaleFromD2CSample?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/AssetSaleFromD2CSample?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public AssetSaleFromD2CSampleService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AssetSaleFromD2CSampleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AssetSaleFromD2CSampleService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public AssetSaleFromD2CSampleService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public AssetSaleFromD2CSampleService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public AssetSaleFromD2CSampleService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns AssetSaleFromD2CSample
     */
    @WebEndpoint(name = "AssetSaleFromD2CSamplePort")
    public AssetSaleFromD2CSample getAssetSaleFromD2CSamplePort() {
        return super.getPort(AssetSaleFromD2CSamplePort, AssetSaleFromD2CSample.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AssetSaleFromD2CSample
     */
    @WebEndpoint(name = "AssetSaleFromD2CSamplePort")
    public AssetSaleFromD2CSample getAssetSaleFromD2CSamplePort(WebServiceFeature... features) {
        return super.getPort(AssetSaleFromD2CSamplePort, AssetSaleFromD2CSample.class, features);
    }

}
