package remote.EAscheduler.AssetSaleFromD2C;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Fri Jun 19 11:51:31 IST 2015
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservices.EAintegration.wise.remote/", name = "AssetSaleFromD2CSample")
@XmlSeeAlso({ObjectFactory.class})
public interface AssetSaleFromD2CSample {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "processEAsaleFromD2C", targetNamespace = "http://webservices.EAintegration.wise.remote/", className = "remote.EAscheduler.AssetSaleFromD2C.ProcessEAsaleFromD2C")
    @WebMethod(action = "processEAsaleFromD2C")
    @ResponseWrapper(localName = "processEAsaleFromD2CResponse", targetNamespace = "http://webservices.EAintegration.wise.remote/", className = "remote.EAscheduler.AssetSaleFromD2C.ProcessEAsaleFromD2CResponse")
    public java.lang.String processEAsaleFromD2C(
        @WebParam(name = "msg", targetNamespace = "")
        java.lang.String msg
    );
}
