
/*
 * 
 */

package remote.wise.client.EAInterfaceService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Aug 13 17:38:05 IST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "EAInterfaceServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/EAInterfaceService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class EAInterfaceServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "EAInterfaceServiceService");
    public final static QName EAInterfaceServicePort = new QName("http://webservice.service.wise.remote/", "EAInterfaceServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/EAInterfaceService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/EAInterfaceService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public EAInterfaceServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EAInterfaceServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EAInterfaceServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public EAInterfaceServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public EAInterfaceServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public EAInterfaceServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns EAInterfaceService
     */
    @WebEndpoint(name = "EAInterfaceServicePort")
    public EAInterfaceService getEAInterfaceServicePort() {
        return super.getPort(EAInterfaceServicePort, EAInterfaceService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EAInterfaceService
     */
    @WebEndpoint(name = "EAInterfaceServicePort")
    public EAInterfaceService getEAInterfaceServicePort(WebServiceFeature... features) {
        return super.getPort(EAInterfaceServicePort, EAInterfaceService.class, features);
    }

}
