package remote.wise.client.EAInterfaceService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Aug 13 17:38:05 IST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "EAInterfaceService")
@XmlSeeAlso({ObjectFactory.class})
public interface EAInterfaceService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetEADetailData", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.EAInterfaceService.GetEADetailData")
    @WebMethod(operationName = "GetEADetailData", action = "GetEADetailData")
    @ResponseWrapper(localName = "GetEADetailDataResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.EAInterfaceService.GetEADetailDataResponse")
    public java.util.List<remote.wise.client.EAInterfaceService.EaInterfaceDetailRespContract> getEADetailData(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.EAInterfaceService.EaInterfaceDetailReqContract reqObj
    ) throws CustomFault;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetEASummaryData", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.EAInterfaceService.GetEASummaryData")
    @WebMethod(operationName = "GetEASummaryData", action = "GetEASummaryData")
    @ResponseWrapper(localName = "GetEASummaryDataResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.EAInterfaceService.GetEASummaryDataResponse")
    public java.util.List<remote.wise.client.EAInterfaceService.EaInterfaceRespContract> getEASummaryData(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.EAInterfaceService.EaInterfaceReqContract reqObj
    ) throws CustomFault;
}
