package remote.wise.client.AssetExtendedService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Mar 04 15:00:03 IST 2015
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "AssetExtendedService")
@XmlSeeAlso({ObjectFactory.class})
public interface AssetExtendedService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "UpdateCHMRDetails", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.AssetExtendedService.UpdateCHMRDetails")
    @WebMethod(operationName = "UpdateCHMRDetails", action = "UpdateCHMRDetails")
    @ResponseWrapper(localName = "UpdateCHMRDetailsResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.AssetExtendedService.UpdateCHMRDetailsResponse")
    public java.lang.String updateCHMRDetails(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.AssetExtendedService.AssetExtendedRespContract reqObj
    ) throws CustomFault;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "SetAssetExtendedDetails", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.AssetExtendedService.SetAssetExtendedDetails")
    @WebMethod(operationName = "SetAssetExtendedDetails", action = "SetAssetExtendedDetails")
    @ResponseWrapper(localName = "SetAssetExtendedDetailsResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.AssetExtendedService.SetAssetExtendedDetailsResponse")
    public java.lang.String setAssetExtendedDetails(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.AssetExtendedService.AssetExtendedRespContract reqObj
    ) throws CustomFault;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetAssetExtendedDetails", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.AssetExtendedService.GetAssetExtendedDetails")
    @WebMethod(operationName = "GetAssetExtendedDetails", action = "GetAssetExtendedDetails")
    @ResponseWrapper(localName = "GetAssetExtendedDetailsResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.AssetExtendedService.GetAssetExtendedDetailsResponse")
    public remote.wise.client.AssetExtendedService.AssetExtendedRespContract getAssetExtendedDetails(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.AssetExtendedService.AssetExtendedReqContract reqObj
    ) throws CustomFault;
}
