package remote.wise.client.MachineHoursServiceReportService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Thu Mar 10 16:47:43 IST 2016
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "MachineHoursServiceReportService")
@XmlSeeAlso({ObjectFactory.class})
public interface MachineHoursServiceReportService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetMachineHoursServiceReportService", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.MachineHoursServiceReportService.GetMachineHoursServiceReportService")
    @WebMethod(operationName = "GetMachineHoursServiceReportService", action = "GetMachineHoursServiceReportService")
    @ResponseWrapper(localName = "GetMachineHoursServiceReportServiceResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.MachineHoursServiceReportService.GetMachineHoursServiceReportServiceResponse")
    public java.util.List<remote.wise.client.MachineHoursServiceReportService.MachineHoursServiceReportRespContract> getMachineHoursServiceReportService(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.MachineHoursServiceReportService.MachineHoursServiceReportReqContract reqObj
    ) throws CustomFault;
}
