package remote.wise.client.FotaUpdateService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Aug 28 12:33:58 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "FotaUpdateService")
@XmlSeeAlso({ObjectFactory.class})
public interface FotaUpdateService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "FotaUpdate", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.FotaUpdateService.FotaUpdate")
    @WebMethod(operationName = "FotaUpdate", action = "FotaUpdate")
    @ResponseWrapper(localName = "FotaUpdateResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.FotaUpdateService.FotaUpdateResponse")
    public remote.wise.client.FotaUpdateService.FotaUpdateRespContract fotaUpdate(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.FotaUpdateService.FotaUpdateReqContract reqObj
    );
}
