
/*
 * 
 */

package remote.wise.EAintegration.clientPackage.PrimaryDealerTransfer;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Fri Feb 21 16:29:35 IST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "PrimaryDealerTransferServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/PrimaryDealerTransferService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class PrimaryDealerTransferServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "PrimaryDealerTransferServiceService");
    public final static QName PrimaryDealerTransferServicePort = new QName("http://webservice.service.wise.remote/", "PrimaryDealerTransferServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/PrimaryDealerTransferService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/PrimaryDealerTransferService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public PrimaryDealerTransferServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PrimaryDealerTransferServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PrimaryDealerTransferServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public PrimaryDealerTransferServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public PrimaryDealerTransferServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public PrimaryDealerTransferServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns PrimaryDealerTransferService
     */
    @WebEndpoint(name = "PrimaryDealerTransferServicePort")
    public PrimaryDealerTransferService getPrimaryDealerTransferServicePort() {
        return super.getPort(PrimaryDealerTransferServicePort, PrimaryDealerTransferService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PrimaryDealerTransferService
     */
    @WebEndpoint(name = "PrimaryDealerTransferServicePort")
    public PrimaryDealerTransferService getPrimaryDealerTransferServicePort(WebServiceFeature... features) {
        return super.getPort(PrimaryDealerTransferServicePort, PrimaryDealerTransferService.class, features);
    }

}
