package remote.wise.client.AssetGroupVersionVolumeSummaryService;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Thu Mar 20 11:56:48 IST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "AssetGroupVersionVolumeSummaryService")
@XmlSeeAlso({ObjectFactory.class})
public interface AssetGroupVersionVolumeSummaryService {

    @RequestWrapper(localName = "setGroupVersionVolume", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.AssetGroupVersionVolumeSummaryService.SetGroupVersionVolume")
    @WebMethod(action = "setGroupVersionVolume")
    @ResponseWrapper(localName = "setGroupVersionVolumeResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.AssetGroupVersionVolumeSummaryService.SetGroupVersionVolumeResponse")
    public void setGroupVersionVolume();

    @RequestWrapper(localName = "setGropTypeForDeviceStatusInfo", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.AssetGroupVersionVolumeSummaryService.SetGropTypeForDeviceStatusInfo")
    @WebMethod
    @ResponseWrapper(localName = "setGropTypeForDeviceStatusInfoResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.AssetGroupVersionVolumeSummaryService.SetGropTypeForDeviceStatusInfoResponse")
    public void setGropTypeForDeviceStatusInfo();
}
