
/*
 * 
 */

package remote.wise.EAintegration.clientPackage.JcbRollOffService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Mon Feb 17 13:54:04 IST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "JcbRollOffServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/JcbRollOffService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class JcbRollOffServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "JcbRollOffServiceService");
    public final static QName JcbRollOffServicePort = new QName("http://webservice.service.wise.remote/", "JcbRollOffServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/JcbRollOffService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/JcbRollOffService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public JcbRollOffServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public JcbRollOffServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JcbRollOffServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public JcbRollOffServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public JcbRollOffServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public JcbRollOffServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns JcbRollOffService
     */
    @WebEndpoint(name = "JcbRollOffServicePort")
    public JcbRollOffService getJcbRollOffServicePort() {
        return super.getPort(JcbRollOffServicePort, JcbRollOffService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JcbRollOffService
     */
    @WebEndpoint(name = "JcbRollOffServicePort")
    public JcbRollOffService getJcbRollOffServicePort(WebServiceFeature... features) {
        return super.getPort(JcbRollOffServicePort, JcbRollOffService.class, features);
    }

}
