package remote.wise.EAintegration.clientPackage.JcbRollOffService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Mon Feb 17 13:54:04 IST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "JcbRollOffService")
@XmlSeeAlso({ObjectFactory.class})
public interface JcbRollOffService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "setVinMachineNameMapping", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.EAintegration.clientPackage.JcbRollOffService.SetVinMachineNameMapping")
    @WebMethod(action = "setVinMachineNameMapping")
    @ResponseWrapper(localName = "setVinMachineNameMappingResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.EAintegration.clientPackage.JcbRollOffService.SetVinMachineNameMappingResponse")
    public java.lang.String setVinMachineNameMapping(
        @WebParam(name = "serialNumber", targetNamespace = "")
        java.lang.String serialNumber,
        @WebParam(name = "engineNumber", targetNamespace = "")
        java.lang.String engineNumber,
        @WebParam(name = "chasisNumber", targetNamespace = "")
        java.lang.String chasisNumber,
        @WebParam(name = "messageId", targetNamespace = "")
        java.lang.String messageId,
        @WebParam(name = "fileRef", targetNamespace = "")
        java.lang.String fileRef,
        @WebParam(name = "process", targetNamespace = "")
        java.lang.String process,
        @WebParam(name = "reprocessJobCode", targetNamespace = "")
        java.lang.String reprocessJobCode,
        @WebParam(name = "make", targetNamespace = "")
        java.lang.String make,
        @WebParam(name = "builtDate", targetNamespace = "")
        java.lang.String builtDate,
        @WebParam(name = "machineNumber", targetNamespace = "")
        java.lang.String machineNumber
    ) throws CustomFault;
}
