package remote.wise.client.FleetSummaryService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Thu Dec 19 11:09:17 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "FleetSummaryService")
@XmlSeeAlso({ObjectFactory.class})
public interface FleetSummaryService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetFleetSummaryService", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.FleetSummaryService.GetFleetSummaryService")
    @WebMethod(operationName = "GetFleetSummaryService", action = "GetFleetSummaryService")
    @ResponseWrapper(localName = "GetFleetSummaryServiceResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.FleetSummaryService.GetFleetSummaryServiceResponse")
    public java.util.List<remote.wise.client.FleetSummaryService.FleetSummaryRespContract> getFleetSummaryService(
        @WebParam(name = "request", targetNamespace = "")
        remote.wise.client.FleetSummaryService.FleetSummaryReqContract request
    );
}
