
/*
 * 
 */

package remote.wise.client.FleetSummaryService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Thu Dec 19 11:09:17 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "FleetSummaryServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/FleetSummaryService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class FleetSummaryServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "FleetSummaryServiceService");
    public final static QName FleetSummaryServicePort = new QName("http://webservice.service.wise.remote/", "FleetSummaryServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/FleetSummaryService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/FleetSummaryService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public FleetSummaryServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FleetSummaryServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FleetSummaryServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public FleetSummaryServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public FleetSummaryServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public FleetSummaryServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns FleetSummaryService
     */
    @WebEndpoint(name = "FleetSummaryServicePort")
    public FleetSummaryService getFleetSummaryServicePort() {
        return super.getPort(FleetSummaryServicePort, FleetSummaryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FleetSummaryService
     */
    @WebEndpoint(name = "FleetSummaryServicePort")
    public FleetSummaryService getFleetSummaryServicePort(WebServiceFeature... features) {
        return super.getPort(FleetSummaryServicePort, FleetSummaryService.class, features);
    }

}
