
/*
 * 
 */

package remote.wise.client.ServiceDueOverDueService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Fri Feb 07 15:11:54 IST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "ServiceDueOverDueServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/ServiceDueOverDueService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class ServiceDueOverDueServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "ServiceDueOverDueServiceService");
    public final static QName ServiceDueOverDueServicePort = new QName("http://webservice.service.wise.remote/", "ServiceDueOverDueServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/ServiceDueOverDueService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/ServiceDueOverDueService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public ServiceDueOverDueServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServiceDueOverDueServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceDueOverDueServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ServiceDueOverDueServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public ServiceDueOverDueServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public ServiceDueOverDueServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ServiceDueOverDueService
     */
    @WebEndpoint(name = "ServiceDueOverDueServicePort")
    public ServiceDueOverDueService getServiceDueOverDueServicePort() {
        return super.getPort(ServiceDueOverDueServicePort, ServiceDueOverDueService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceDueOverDueService
     */
    @WebEndpoint(name = "ServiceDueOverDueServicePort")
    public ServiceDueOverDueService getServiceDueOverDueServicePort(WebServiceFeature... features) {
        return super.getPort(ServiceDueOverDueServicePort, ServiceDueOverDueService.class, features);
    }

}
