package remote.wise.client.ServiceDueOverDueService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Fri Feb 07 15:11:53 IST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "ServiceDueOverDueService")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceDueOverDueService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetServiceDueOverDueDetails", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.ServiceDueOverDueService.GetServiceDueOverDueDetails")
    @WebMethod(operationName = "GetServiceDueOverDueDetails", action = "GetServiceDueOverDueDetails")
    @ResponseWrapper(localName = "GetServiceDueOverDueDetailsResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.ServiceDueOverDueService.GetServiceDueOverDueDetailsResponse")
    public remote.wise.client.ServiceDueOverDueService.ServiceDueOverDueRespContract getServiceDueOverDueDetails(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.ServiceDueOverDueService.ServiceDueOverDueReqContract reqObj
    ) throws CustomFault;
    
    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetExtendedWarrantyServiceDueOverDueDetails", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.ServiceDueOverDueService.GetExtendedWarrantyServiceDueOverDueDetails")
    @WebMethod(operationName = "GetExtendedWarrantyServiceDueOverDueDetails", action = "GetExtendedWarrantyServiceDueOverDueDetails")
    @ResponseWrapper(localName = "GetServiceDueOverDueDetailsResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.ServiceDueOverDueService.GetServiceDueOverDueDetailsResponse")
    public remote.wise.client.ServiceDueOverDueService.ServiceDueOverDueRespContract GetExtendedWarrantyServiceDueOverDueDetails(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.ServiceDueOverDueService.ServiceDueOverDueReqContract reqObj
    ) throws CustomFault;
}
