
/*
 * 
 */

package remote.wise.client.MachineHoursReportService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Fri Dec 13 18:06:34 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "MachineHoursReportServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/MachineHoursReportService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class MachineHoursReportServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "MachineHoursReportServiceService");
    public final static QName MachineHoursReportServicePort = new QName("http://webservice.service.wise.remote/", "MachineHoursReportServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/MachineHoursReportService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/MachineHoursReportService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public MachineHoursReportServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MachineHoursReportServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MachineHoursReportServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public MachineHoursReportServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public MachineHoursReportServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public MachineHoursReportServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns MachineHoursReportService
     */
    @WebEndpoint(name = "MachineHoursReportServicePort")
    public MachineHoursReportService getMachineHoursReportServicePort() {
        return super.getPort(MachineHoursReportServicePort, MachineHoursReportService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MachineHoursReportService
     */
    @WebEndpoint(name = "MachineHoursReportServicePort")
    public MachineHoursReportService getMachineHoursReportServicePort(WebServiceFeature... features) {
        return super.getPort(MachineHoursReportServicePort, MachineHoursReportService.class, features);
    }

}
