package remote.wise.client.TenancyDetailsService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Mon Jan 20 13:01:05 IST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "TenancyDetailsService")
@XmlSeeAlso({ObjectFactory.class})
public interface TenancyDetailsService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetTenancyDetails", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.TenancyDetailsService.GetTenancyDetails")
    @WebMethod(operationName = "GetTenancyDetails", action = "GetTenancyDetails")
    @ResponseWrapper(localName = "GetTenancyDetailsResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.TenancyDetailsService.GetTenancyDetailsResponse")
    public java.util.List<remote.wise.client.TenancyDetailsService.TenancyDetailsRespContract> getTenancyDetails(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.TenancyDetailsService.TenancyDetailsReqContract reqObj
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "setTenancyDetails", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.TenancyDetailsService.SetTenancyDetails")
    @WebMethod(action = "setTenancyDetails")
    @ResponseWrapper(localName = "setTenancyDetailsResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.TenancyDetailsService.SetTenancyDetailsResponse")
    public java.lang.String setTenancyDetails(
        @WebParam(name = "reqObj", targetNamespace = "")
        remote.wise.client.TenancyDetailsService.TenancyCreationReqContract reqObj
    ) throws CustomFault, ParseException_Exception, IOException_Exception;
}
