
package remote.wise.EAintegration.webservices.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Aug 28 18:53:23 IST 2013
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "reprocessEAassetTypeDataResponse", namespace = "http://webservices.EAintegration.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reprocessEAassetTypeDataResponse", namespace = "http://webservices.EAintegration.wise.remote/")

public class ReprocessEAassetTypeDataResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

