
package remote.wise.EAintegration.webservices.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Fri Jan 02 12:55:41 IST 2015
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "reprocessEADealerMappingData", namespace = "http://webservices.EAintegration.wise.remote/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reprocessEADealerMappingData", namespace = "http://webservices.EAintegration.wise.remote/")

public class ReprocessEADealerMappingData {

    @XmlElement(name = "msg")
    private java.lang.String msg;

    public java.lang.String getMsg() {
        return this.msg;
    }

    public void setMsg(java.lang.String newMsg)  {
        this.msg = newMsg;
    }

}

