
/*
 * 
 */

package remote.wise.client.UpdateAssetOwnerDetails;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Thu Dec 04 11:26:07 IST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "CurrentAssetOwnerDetailsServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/CurrentAssetOwnerDetailsService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class CurrentAssetOwnerDetailsServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "CurrentAssetOwnerDetailsServiceService");
    public final static QName CurrentAssetOwnerDetailsServicePort = new QName("http://webservice.service.wise.remote/", "CurrentAssetOwnerDetailsServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/CurrentAssetOwnerDetailsService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/CurrentAssetOwnerDetailsService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public CurrentAssetOwnerDetailsServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CurrentAssetOwnerDetailsServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CurrentAssetOwnerDetailsServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CurrentAssetOwnerDetailsServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public CurrentAssetOwnerDetailsServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public CurrentAssetOwnerDetailsServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns CurrentAssetOwnerDetailsService
     */
    @WebEndpoint(name = "CurrentAssetOwnerDetailsServicePort")
    public CurrentAssetOwnerDetailsService getCurrentAssetOwnerDetailsServicePort() {
        return super.getPort(CurrentAssetOwnerDetailsServicePort, CurrentAssetOwnerDetailsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CurrentAssetOwnerDetailsService
     */
    @WebEndpoint(name = "CurrentAssetOwnerDetailsServicePort")
    public CurrentAssetOwnerDetailsService getCurrentAssetOwnerDetailsServicePort(WebServiceFeature... features) {
        return super.getPort(CurrentAssetOwnerDetailsServicePort, CurrentAssetOwnerDetailsService.class, features);
    }

}
