package remote.wise.client.HAJassetContactDetailsService;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed May 27 18:34:31 IST 2015
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "HAJassetContactDetailsService")
@XmlSeeAlso({ObjectFactory.class})
public interface HAJassetContactDetailsService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "SetHAJassetContactDetails", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.HAJassetContactDetailsService.SetHAJassetContactDetails")
    @WebMethod(operationName = "SetHAJassetContactDetails", action = "http://webservice.service.wise.remote/SetHAJassetContactDetails")
    @ResponseWrapper(localName = "SetHAJassetContactDetailsResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.HAJassetContactDetailsService.SetHAJassetContactDetailsResponse")
    public java.lang.String setHAJassetContactDetails() throws CustomFault;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetHAJassetContactDetails", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.HAJassetContactDetailsService.GetHAJassetContactDetails")
    @WebMethod(operationName = "GetHAJassetContactDetails", action = "GetHAJassetContactDetails")
    @ResponseWrapper(localName = "GetHAJassetContactDetailsResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.HAJassetContactDetailsService.GetHAJassetContactDetailsResponse")
    public java.util.List<remote.wise.client.HAJassetContactDetailsService.HajAssetContactDetailsRespContract> getHAJassetContactDetails() throws CustomFault;
}
