package remote.wise.client.MachineActivityReportService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Mon Dec 16 15:15:56 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "MachineActivityReportService")
@XmlSeeAlso({ObjectFactory.class})
public interface MachineActivityReportService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetMachineActivityReport", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.MachineActivityReportService.GetMachineActivityReport")
    @WebMethod(operationName = "GetMachineActivityReport", action = "GetMachineActivityReport")
    @ResponseWrapper(localName = "GetMachineActivityReportResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.MachineActivityReportService.GetMachineActivityReportResponse")
    public java.util.List<remote.wise.client.MachineActivityReportService.MachineActivityReportRespContract> getMachineActivityReport(
        @WebParam(name = "ReqObj", targetNamespace = "")
        remote.wise.client.MachineActivityReportService.MachineActivityReportReqContract reqObj
    ) throws CustomFault;
}
