
/*
 * 
 */

package remote.wise.client.LoginRegistrationService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Thu Mar 14 15:03:22 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "LoginRegistrationServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/LoginRegistrationService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class LoginRegistrationServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "LoginRegistrationServiceService");
    public final static QName LoginRegistrationServicePort = new QName("http://webservice.service.wise.remote/", "LoginRegistrationServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/LoginRegistrationService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/LoginRegistrationService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public LoginRegistrationServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LoginRegistrationServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoginRegistrationServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public LoginRegistrationServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public LoginRegistrationServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public LoginRegistrationServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns LoginRegistrationService
     */
    @WebEndpoint(name = "LoginRegistrationServicePort")
    public LoginRegistrationService getLoginRegistrationServicePort() {
        return super.getPort(LoginRegistrationServicePort, LoginRegistrationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoginRegistrationService
     */
    @WebEndpoint(name = "LoginRegistrationServicePort")
    public LoginRegistrationService getLoginRegistrationServicePort(WebServiceFeature... features) {
        return super.getPort(LoginRegistrationServicePort, LoginRegistrationService.class, features);
    }

}
