package remote.wise.client.UserAuthenticationService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Jul 03 14:32:30 IST 2013
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.service.wise.remote/", name = "UserAuthenticationService")
@XmlSeeAlso({ObjectFactory.class})
public interface UserAuthenticationService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "UserAuthentication", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.UserAuthenticationService.UserAuthentication")
    @WebMethod(operationName = "UserAuthentication", action = "UserAuthentication")
    @ResponseWrapper(localName = "UserAuthenticationResponse", targetNamespace = "http://webservice.service.wise.remote/", className = "remote.wise.client.UserAuthenticationService.UserAuthenticationResponse")
    public remote.wise.client.UserAuthenticationService.UserAuthenticationRespContract userAuthentication(
        @WebParam(name = "reqobj", targetNamespace = "")
        remote.wise.client.UserAuthenticationService.UserAuthenticationReqContract reqobj
    ) throws CustomFault, IOException_Exception;
}
