
/*
 * 
 */

package remote.wise.client.AlertSummaryService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Fri Feb 07 15:02:13 IST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "AlertSummaryServiceService", 
                  wsdlLocation = "http://localhost:27000/WISE/AlertSummaryService?wsdl",
                  targetNamespace = "http://webservice.service.wise.remote/") 
public class AlertSummaryServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.service.wise.remote/", "AlertSummaryServiceService");
    public final static QName AlertSummaryServicePort = new QName("http://webservice.service.wise.remote/", "AlertSummaryServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:27000/WISE/AlertSummaryService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:27000/WISE/AlertSummaryService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public AlertSummaryServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AlertSummaryServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AlertSummaryServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public AlertSummaryServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public AlertSummaryServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public AlertSummaryServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns AlertSummaryService
     */
    @WebEndpoint(name = "AlertSummaryServicePort")
    public AlertSummaryService getAlertSummaryServicePort() {
        return super.getPort(AlertSummaryServicePort, AlertSummaryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AlertSummaryService
     */
    @WebEndpoint(name = "AlertSummaryServicePort")
    public AlertSummaryService getAlertSummaryServicePort(WebServiceFeature... features) {
        return super.getPort(AlertSummaryServicePort, AlertSummaryService.class, features);
    }

}
